// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: betreiber.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const clearElsterGemeldetAm = `-- name: ClearElsterGemeldetAm :exec
UPDATE betreiber
SET elster_gemeldet_am = NULL,
    updated_at         = NOW()
WHERE id = 1
`

func (q *Queries) ClearElsterGemeldetAm(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearElsterGemeldetAm)
	return err
}

const getBetreiber = `-- name: GetBetreiber :one
SELECT vereinsname, strasse, plz, ort, steuernummer, ust_id, elster_gemeldet_am, updated_at
FROM betreiber
LIMIT 1
`

type GetBetreiberRow struct {
	Vereinsname      string
	Strasse          string
	Plz              string
	Ort              string
	Steuernummer     sql.NullString
	UstID            sql.NullString
	ElsterGemeldetAm sql.NullTime
	UpdatedAt        time.Time
}

func (q *Queries) GetBetreiber(ctx context.Context) (GetBetreiberRow, error) {
	row := q.db.QueryRowContext(ctx, getBetreiber)
	var i GetBetreiberRow
	err := row.Scan(
		&i.Vereinsname,
		&i.Strasse,
		&i.Plz,
		&i.Ort,
		&i.Steuernummer,
		&i.UstID,
		&i.ElsterGemeldetAm,
		&i.UpdatedAt,
	)
	return i, err
}

const setElsterGemeldetAm = `-- name: SetElsterGemeldetAm :exec
UPDATE betreiber
SET elster_gemeldet_am = CURRENT_DATE,
    updated_at         = NOW()
WHERE id = 1
`

func (q *Queries) SetElsterGemeldetAm(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, setElsterGemeldetAm)
	return err
}

const upsertBetreiber = `-- name: UpsertBetreiber :exec
INSERT INTO betreiber (id, vereinsname, strasse, plz, ort, steuernummer, ust_id, updated_at)
VALUES (1, $1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (id) DO UPDATE SET
    vereinsname  = EXCLUDED.vereinsname,
    strasse      = EXCLUDED.strasse,
    plz          = EXCLUDED.plz,
    ort          = EXCLUDED.ort,
    steuernummer = EXCLUDED.steuernummer,
    ust_id       = EXCLUDED.ust_id,
    updated_at   = EXCLUDED.updated_at
`

type UpsertBetreiberParams struct {
	Vereinsname  string
	Strasse      string
	Plz          string
	Ort          string
	Steuernummer sql.NullString
	UstID        sql.NullString
}

func (q *Queries) UpsertBetreiber(ctx context.Context, arg UpsertBetreiberParams) error {
	_, err := q.db.ExecContext(ctx, upsertBetreiber,
		arg.Vereinsname,
		arg.Strasse,
		arg.Plz,
		arg.Ort,
		arg.Steuernummer,
		arg.UstID,
	)
	return err
}
