// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bondruck_einstellungen.sql

package dbgen

import (
	"context"
	"time"
)

const getBondruckEinstellungen = `-- name: GetBondruckEinstellungen :one
SELECT kassenbeleg_drucker_ip, updated_at
FROM bondruck_einstellungen
WHERE id = 1
`

type GetBondruckEinstellungenRow struct {
	KassenbelegDruckerIp string
	UpdatedAt            time.Time
}

func (q *Queries) GetBondruckEinstellungen(ctx context.Context) (GetBondruckEinstellungenRow, error) {
	row := q.db.QueryRowContext(ctx, getBondruckEinstellungen)
	var i GetBondruckEinstellungenRow
	err := row.Scan(&i.KassenbelegDruckerIp, &i.UpdatedAt)
	return i, err
}

const upsertBondruckEinstellungen = `-- name: UpsertBondruckEinstellungen :exec
INSERT INTO bondruck_einstellungen (id, kassenbeleg_drucker_ip, updated_at)
VALUES (1, $1, NOW())
ON CONFLICT (id) DO UPDATE SET
    kassenbeleg_drucker_ip = EXCLUDED.kassenbeleg_drucker_ip,
    updated_at = EXCLUDED.updated_at
`

func (q *Queries) UpsertBondruckEinstellungen(ctx context.Context, kassenbelegDruckerIp string) error {
	_, err := q.db.ExecContext(ctx, upsertBondruckEinstellungen, kassenbelegDruckerIp)
	return err
}
