// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: drucker.sql

package dbgen

import (
	"context"
)

const getKategorieDrucker = `-- name: GetKategorieDrucker :many
SELECT kategorie, drucker_ip, bonmodus
FROM kategorie_drucker
`

type GetKategorieDruckerRow struct {
	Kategorie Produktkategorie
	DruckerIp string
	Bonmodus  string
}

func (q *Queries) GetKategorieDrucker(ctx context.Context) ([]GetKategorieDruckerRow, error) {
	rows, err := q.db.QueryContext(ctx, getKategorieDrucker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetKategorieDruckerRow{}
	for rows.Next() {
		var i GetKategorieDruckerRow
		if err := rows.Scan(&i.Kategorie, &i.DruckerIp, &i.Bonmodus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKonfigurierteKategorieDrucker = `-- name: GetKonfigurierteKategorieDrucker :many
SELECT kategorie, drucker_ip, bonmodus
FROM kategorie_drucker
WHERE drucker_ip != ''
`

type GetKonfigurierteKategorieDruckerRow struct {
	Kategorie Produktkategorie
	DruckerIp string
	Bonmodus  string
}

func (q *Queries) GetKonfigurierteKategorieDrucker(ctx context.Context) ([]GetKonfigurierteKategorieDruckerRow, error) {
	rows, err := q.db.QueryContext(ctx, getKonfigurierteKategorieDrucker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetKonfigurierteKategorieDruckerRow{}
	for rows.Next() {
		var i GetKonfigurierteKategorieDruckerRow
		if err := rows.Scan(&i.Kategorie, &i.DruckerIp, &i.Bonmodus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertKategorieDrucker = `-- name: UpsertKategorieDrucker :exec
INSERT INTO kategorie_drucker (kategorie, drucker_ip, bonmodus, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (kategorie) DO UPDATE SET
    drucker_ip = EXCLUDED.drucker_ip,
    bonmodus = EXCLUDED.bonmodus,
    updated_at = NOW()
`

type UpsertKategorieDruckerParams struct {
	Kategorie Produktkategorie
	DruckerIp string
	Bonmodus  string
}

func (q *Queries) UpsertKategorieDrucker(ctx context.Context, arg UpsertKategorieDruckerParams) error {
	_, err := q.db.ExecContext(ctx, upsertKategorieDrucker, arg.Kategorie, arg.DruckerIp, arg.Bonmodus)
	return err
}
