// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: druckstation.sql

package dbgen

import (
	"context"
)

const getDruckstationen = `-- name: GetDruckstationen :many
SELECT kategorie, drucker_ip, bonmodus
FROM druckstationen
`

type GetDruckstationenRow struct {
	Kategorie Produktkategorie
	DruckerIp string
	Bonmodus  string
}

func (q *Queries) GetDruckstationen(ctx context.Context) ([]GetDruckstationenRow, error) {
	rows, err := q.db.QueryContext(ctx, getDruckstationen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDruckstationenRow{}
	for rows.Next() {
		var i GetDruckstationenRow
		if err := rows.Scan(&i.Kategorie, &i.DruckerIp, &i.Bonmodus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKonfigurierteDruckstationen = `-- name: GetKonfigurierteDruckstationen :many
SELECT kategorie, drucker_ip, bonmodus
FROM druckstationen
WHERE drucker_ip != ''
`

type GetKonfigurierteDruckstationenRow struct {
	Kategorie Produktkategorie
	DruckerIp string
	Bonmodus  string
}

func (q *Queries) GetKonfigurierteDruckstationen(ctx context.Context) ([]GetKonfigurierteDruckstationenRow, error) {
	rows, err := q.db.QueryContext(ctx, getKonfigurierteDruckstationen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetKonfigurierteDruckstationenRow{}
	for rows.Next() {
		var i GetKonfigurierteDruckstationenRow
		if err := rows.Scan(&i.Kategorie, &i.DruckerIp, &i.Bonmodus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDruckstation = `-- name: UpsertDruckstation :exec
INSERT INTO druckstationen (kategorie, drucker_ip, bonmodus, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (kategorie) DO UPDATE SET
    drucker_ip = EXCLUDED.drucker_ip,
    bonmodus = EXCLUDED.bonmodus,
    updated_at = NOW()
`

type UpsertDruckstationParams struct {
	Kategorie Produktkategorie
	DruckerIp string
	Bonmodus  string
}

func (q *Queries) UpsertDruckstation(ctx context.Context, arg UpsertDruckstationParams) error {
	_, err := q.db.ExecContext(ctx, upsertDruckstation, arg.Kategorie, arg.DruckerIp, arg.Bonmodus)
	return err
}
