// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const getMaxVersion = `-- name: GetMaxVersion :one
SELECT COALESCE(MAX(version), 0)::int AS version FROM events WHERE subject = $1
`

func (q *Queries) GetMaxVersion(ctx context.Context, subject string) (int, error) {
	row := q.db.QueryRowContext(ctx, getMaxVersion, subject)
	var version int
	err := row.Scan(&version)
	return version, err
}

const readEvent = `-- name: ReadEvent :one
SELECT id, user_id, user_name, version, type, subject, data, timestamp
FROM events WHERE id = $1
`

type ReadEventRow struct {
	ID        int
	UserID    int
	UserName  string
	Version   int
	Type      string
	Subject   string
	Data      json.RawMessage
	Timestamp time.Time
}

func (q *Queries) ReadEvent(ctx context.Context, id int) (ReadEventRow, error) {
	row := q.db.QueryRowContext(ctx, readEvent, id)
	var i ReadEventRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Version,
		&i.Type,
		&i.Subject,
		&i.Data,
		&i.Timestamp,
	)
	return i, err
}

const readEventsBySubject = `-- name: ReadEventsBySubject :many
SELECT id, user_id, user_name, version, type, subject, data, timestamp
FROM events WHERE subject = $1 ORDER BY id ASC
`

type ReadEventsBySubjectRow struct {
	ID        int
	UserID    int
	UserName  string
	Version   int
	Type      string
	Subject   string
	Data      json.RawMessage
	Timestamp time.Time
}

func (q *Queries) ReadEventsBySubject(ctx context.Context, subject string) ([]ReadEventsBySubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, readEventsBySubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadEventsBySubjectRow{}
	for rows.Next() {
		var i ReadEventsBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.Version,
			&i.Type,
			&i.Subject,
			&i.Data,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeEvent = `-- name: WriteEvent :one
INSERT INTO events (user_id, user_name, type, subject, version, data, timestamp)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id
`

type WriteEventParams struct {
	UserID    int
	UserName  string
	Type      string
	Subject   string
	Version   int
	Data      json.RawMessage
	Timestamp time.Time
}

func (q *Queries) WriteEvent(ctx context.Context, arg WriteEventParams) (int, error) {
	row := q.db.QueryRowContext(ctx, writeEvent,
		arg.UserID,
		arg.UserName,
		arg.Type,
		arg.Subject,
		arg.Version,
		arg.Data,
		arg.Timestamp,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}
