// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const getLastSnapshotID = `-- name: GetLastSnapshotID :one
SELECT COALESCE(MAX(id), 0)::int AS id FROM events WHERE subject = $1 AND type = $2
`

type GetLastSnapshotIDParams struct {
	Subject string
	Type    string
}

func (q *Queries) GetLastSnapshotID(ctx context.Context, arg GetLastSnapshotIDParams) (int, error) {
	row := q.db.QueryRowContext(ctx, getLastSnapshotID, arg.Subject, arg.Type)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getMaxVersion = `-- name: GetMaxVersion :one
SELECT COALESCE(MAX(version), 0)::int AS version FROM events WHERE subject = $1
`

func (q *Queries) GetMaxVersion(ctx context.Context, subject string) (int, error) {
	row := q.db.QueryRowContext(ctx, getMaxVersion, subject)
	var version int
	err := row.Scan(&version)
	return version, err
}

const readEvent = `-- name: ReadEvent :one
SELECT id, user_id, user_name, version, type, subject, data, timestamp
FROM events WHERE id = $1
`

type ReadEventRow struct {
	ID        int
	UserID    int
	UserName  string
	Version   int
	Type      string
	Subject   string
	Data      json.RawMessage
	Timestamp time.Time
}

func (q *Queries) ReadEvent(ctx context.Context, id int) (ReadEventRow, error) {
	row := q.db.QueryRowContext(ctx, readEvent, id)
	var i ReadEventRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Version,
		&i.Type,
		&i.Subject,
		&i.Data,
		&i.Timestamp,
	)
	return i, err
}

const readEventsBySubject = `-- name: ReadEventsBySubject :many
SELECT id, user_id, user_name, version, type, subject, data, timestamp
FROM events WHERE subject = $1 ORDER BY id ASC
`

type ReadEventsBySubjectRow struct {
	ID        int
	UserID    int
	UserName  string
	Version   int
	Type      string
	Subject   string
	Data      json.RawMessage
	Timestamp time.Time
}

func (q *Queries) ReadEventsBySubject(ctx context.Context, subject string) ([]ReadEventsBySubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, readEventsBySubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadEventsBySubjectRow{}
	for rows.Next() {
		var i ReadEventsBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.Version,
			&i.Type,
			&i.Subject,
			&i.Data,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readEventsSinceID = `-- name: ReadEventsSinceID :many
SELECT id, user_id, user_name, version, type, subject, data, timestamp
FROM events WHERE subject = $1 AND id >= $2 ORDER BY id ASC
`

type ReadEventsSinceIDParams struct {
	Subject string
	ID      int
}

type ReadEventsSinceIDRow struct {
	ID        int
	UserID    int
	UserName  string
	Version   int
	Type      string
	Subject   string
	Data      json.RawMessage
	Timestamp time.Time
}

func (q *Queries) ReadEventsSinceID(ctx context.Context, arg ReadEventsSinceIDParams) ([]ReadEventsSinceIDRow, error) {
	rows, err := q.db.QueryContext(ctx, readEventsSinceID, arg.Subject, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadEventsSinceIDRow{}
	for rows.Next() {
		var i ReadEventsSinceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.Version,
			&i.Type,
			&i.Subject,
			&i.Data,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readEventsWithSnapshot = `-- name: ReadEventsWithSnapshot :many
WITH last_snapshot AS (
    SELECT COALESCE(MAX(id), 0) AS id 
    FROM events 
    WHERE events.subject = $1 AND events.type = $2
)
SELECT e.id, e.user_id, e.user_name, e.version, e.type, e.subject, e.data, e.timestamp
FROM events e, last_snapshot ls
WHERE e.subject = $1 AND e.id >= ls.id
ORDER BY e.id ASC
`

type ReadEventsWithSnapshotParams struct {
	Subject string
	Type    string
}

type ReadEventsWithSnapshotRow struct {
	ID        int
	UserID    int
	UserName  string
	Version   int
	Type      string
	Subject   string
	Data      json.RawMessage
	Timestamp time.Time
}

func (q *Queries) ReadEventsWithSnapshot(ctx context.Context, arg ReadEventsWithSnapshotParams) ([]ReadEventsWithSnapshotRow, error) {
	rows, err := q.db.QueryContext(ctx, readEventsWithSnapshot, arg.Subject, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadEventsWithSnapshotRow{}
	for rows.Next() {
		var i ReadEventsWithSnapshotRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.Version,
			&i.Type,
			&i.Subject,
			&i.Data,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeEvent = `-- name: WriteEvent :one
INSERT INTO events (user_id, user_name, type, subject, version, data, timestamp)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id
`

type WriteEventParams struct {
	UserID    int
	UserName  string
	Type      string
	Subject   string
	Version   int
	Data      json.RawMessage
	Timestamp time.Time
}

func (q *Queries) WriteEvent(ctx context.Context, arg WriteEventParams) (int, error) {
	row := q.db.QueryRowContext(ctx, writeEvent,
		arg.UserID,
		arg.UserName,
		arg.Type,
		arg.Subject,
		arg.Version,
		arg.Data,
		arg.Timestamp,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}
