// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favoriten.sql

package dbgen

import (
	"context"
)

const addFavorit = `-- name: AddFavorit :exec
INSERT INTO tisch_favoriten (user_id, tisch_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavoritParams struct {
	UserID  int
	TischID int
}

func (q *Queries) AddFavorit(ctx context.Context, arg AddFavoritParams) error {
	_, err := q.db.ExecContext(ctx, addFavorit, arg.UserID, arg.TischID)
	return err
}

const getFavoritenByUser = `-- name: GetFavoritenByUser :many
SELECT tisch_id
FROM tisch_favoriten
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetFavoritenByUser(ctx context.Context, userID int) ([]int, error) {
	rows, err := q.db.QueryContext(ctx, getFavoritenByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var tisch_id int
		if err := rows.Scan(&tisch_id); err != nil {
			return nil, err
		}
		items = append(items, tisch_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorit = `-- name: RemoveFavorit :exec
DELETE FROM tisch_favoriten
WHERE user_id = $1 AND tisch_id = $2
`

type RemoveFavoritParams struct {
	UserID  int
	TischID int
}

func (q *Queries) RemoveFavorit(ctx context.Context, arg RemoveFavoritParams) error {
	_, err := q.db.ExecContext(ctx, removeFavorit, arg.UserID, arg.TischID)
	return err
}
