// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kassensitzung_state.sql

package dbgen

import (
	"context"
	"time"
)

const deleteAllKassensitzungState = `-- name: DeleteAllKassensitzungState :exec
DELETE FROM kassensitzung_state
`

func (q *Queries) DeleteAllKassensitzungState(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllKassensitzungState)
	return err
}

const getKassensitzungBySubject = `-- name: GetKassensitzungBySubject :one
SELECT subject, z_nr, datum, status, last_event_id, last_event_version
FROM kassensitzung_state WHERE subject = $1
`

func (q *Queries) GetKassensitzungBySubject(ctx context.Context, subject string) (KassensitzungState, error) {
	row := q.db.QueryRowContext(ctx, getKassensitzungBySubject, subject)
	var i KassensitzungState
	err := row.Scan(
		&i.Subject,
		&i.ZNr,
		&i.Datum,
		&i.Status,
		&i.LastEventID,
		&i.LastEventVersion,
	)
	return i, err
}

const getNextZNr = `-- name: GetNextZNr :one
SELECT COALESCE(MAX(z_nr), 0) + 1 AS next_z_nr FROM kassensitzung_state
`

func (q *Queries) GetNextZNr(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextZNr)
	var next_z_nr int32
	err := row.Scan(&next_z_nr)
	return next_z_nr, err
}

const getOffeneKassensitzung = `-- name: GetOffeneKassensitzung :one
SELECT subject, z_nr, datum, status, last_event_id, last_event_version
FROM kassensitzung_state WHERE status = 'offen' LIMIT 1
`

func (q *Queries) GetOffeneKassensitzung(ctx context.Context) (KassensitzungState, error) {
	row := q.db.QueryRowContext(ctx, getOffeneKassensitzung)
	var i KassensitzungState
	err := row.Scan(
		&i.Subject,
		&i.ZNr,
		&i.Datum,
		&i.Status,
		&i.LastEventID,
		&i.LastEventVersion,
	)
	return i, err
}

const upsertKassensitzungState = `-- name: UpsertKassensitzungState :exec
INSERT INTO kassensitzung_state (subject, z_nr, datum, status, last_event_id, last_event_version)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (subject) DO UPDATE SET
    z_nr = $2,
    datum = $3,
    status = $4,
    last_event_id = $5,
    last_event_version = $6
`

type UpsertKassensitzungStateParams struct {
	Subject          string
	ZNr              int
	Datum            time.Time
	Status           string
	LastEventID      int
	LastEventVersion int
}

func (q *Queries) UpsertKassensitzungState(ctx context.Context, arg UpsertKassensitzungStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertKassensitzungState,
		arg.Subject,
		arg.ZNr,
		arg.Datum,
		arg.Status,
		arg.LastEventID,
		arg.LastEventVersion,
	)
	return err
}
