// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kassensitzungen.sql

package dbgen

import (
	"context"
	"time"
)

const getAllKassensitzungen = `-- name: GetAllKassensitzungen :many
SELECT z_nr, datum, bezeichnung, status, created_at, updated_at
FROM kassensitzungen ORDER BY datum DESC, created_at DESC
`

func (q *Queries) GetAllKassensitzungen(ctx context.Context) ([]Kassensitzungen, error) {
	rows, err := q.db.QueryContext(ctx, getAllKassensitzungen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kassensitzungen{}
	for rows.Next() {
		var i Kassensitzungen
		if err := rows.Scan(
			&i.ZNr,
			&i.Datum,
			&i.Bezeichnung,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKassenbestand = `-- name: GetKassenbestand :one
SELECT COALESCE(SUM(CASE
    WHEN type = 'anfangsbestand-gesetzt:v1'
        THEN (data->>'betragCents')::INT
    WHEN type = 'zahlung-kassiert:v1'
        THEN (data->>'gesamtZahlungCents')::INT
    WHEN type = 'auszahlung-geleistet:v1'
        THEN -(data->>'betragCents')::INT
    WHEN type = 'kassenbewegung-gebucht:v1' AND data->>'art' = 'privateinlage'
        THEN (data->>'betragCents')::INT
    WHEN type = 'kassenbewegung-gebucht:v1' AND data->>'art' IN ('privatentnahme', 'geldtransit')
        THEN -(data->>'betragCents')::INT
    WHEN type = 'differenz-soll-ist-gebucht:v1'
        THEN (data->>'betragCents')::INT
    ELSE 0
END), 0)::int AS soll_bestand_cents
FROM kassenjournal
WHERE kassensitzung_nr = $1
  AND type IN (
    'anfangsbestand-gesetzt:v1',
    'zahlung-kassiert:v1',
    'auszahlung-geleistet:v1',
    'kassenbewegung-gebucht:v1',
    'differenz-soll-ist-gebucht:v1'
  )
`

// Kassenbestand (Soll): Summe aus Anfangsbestand, Zahlungen, Auszahlungen, Kassenbewegungen und Differenz-Buchungen.
func (q *Queries) GetKassenbestand(ctx context.Context, kassensitzungNr int) (int, error) {
	row := q.db.QueryRowContext(ctx, getKassenbestand, kassensitzungNr)
	var soll_bestand_cents int
	err := row.Scan(&soll_bestand_cents)
	return soll_bestand_cents, err
}

const getOffeneKassensitzung = `-- name: GetOffeneKassensitzung :one
SELECT z_nr, datum, bezeichnung, status, created_at, updated_at
FROM kassensitzungen WHERE status = 'offen' LIMIT 1
`

func (q *Queries) GetOffeneKassensitzung(ctx context.Context) (Kassensitzungen, error) {
	row := q.db.QueryRowContext(ctx, getOffeneKassensitzung)
	var i Kassensitzungen
	err := row.Scan(
		&i.ZNr,
		&i.Datum,
		&i.Bezeichnung,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertKassensitzung = `-- name: InsertKassensitzung :one
INSERT INTO kassensitzungen (datum, bezeichnung, status, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW()) RETURNING z_nr
`

type InsertKassensitzungParams struct {
	Datum       time.Time
	Bezeichnung string
	Status      string
}

func (q *Queries) InsertKassensitzung(ctx context.Context, arg InsertKassensitzungParams) (int, error) {
	row := q.db.QueryRowContext(ctx, insertKassensitzung, arg.Datum, arg.Bezeichnung, arg.Status)
	var z_nr int
	err := row.Scan(&z_nr)
	return z_nr, err
}

const updateKassensitzung = `-- name: UpdateKassensitzung :exec
UPDATE kassensitzungen SET status = $2, updated_at = NOW() WHERE z_nr = $1
`

type UpdateKassensitzungParams struct {
	ZNr    int
	Status string
}

func (q *Queries) UpdateKassensitzung(ctx context.Context, arg UpdateKassensitzungParams) error {
	_, err := q.db.ExecContext(ctx, updateKassensitzung, arg.ZNr, arg.Status)
	return err
}
