// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kassenidentitaet.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getKassenidentitaet = `-- name: GetKassenidentitaet :one
SELECT seriennummer, angelegt_am
FROM kassenidentitaet
LIMIT 1
`

type GetKassenidentitaetRow struct {
	Seriennummer uuid.UUID
	AngelegtAm   time.Time
}

func (q *Queries) GetKassenidentitaet(ctx context.Context) (GetKassenidentitaetRow, error) {
	row := q.db.QueryRowContext(ctx, getKassenidentitaet)
	var i GetKassenidentitaetRow
	err := row.Scan(&i.Seriennummer, &i.AngelegtAm)
	return i, err
}
