// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kassensitzungen.sql

package dbgen

import (
	"context"
	"time"
)

const getAktiveKassensitzung = `-- name: GetAktiveKassensitzung :one
SELECT z_nr, datum, bezeichnung, status, created_at, updated_at
FROM kassensitzungen WHERE status <> 'abgeschlossen' LIMIT 1
`

// Die aktive (nicht abgeschlossene) Kassensitzung, also 'offen' oder 'wird_abgeschlossen'.
// Dank idx_kassensitzungen_eine_aktiv gibt es davon höchstens eine.
func (q *Queries) GetAktiveKassensitzung(ctx context.Context) (Kassensitzungen, error) {
	row := q.db.QueryRowContext(ctx, getAktiveKassensitzung)
	var i Kassensitzungen
	err := row.Scan(
		&i.ZNr,
		&i.Datum,
		&i.Bezeichnung,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllKassensitzungen = `-- name: GetAllKassensitzungen :many
SELECT z_nr, datum, bezeichnung, status, created_at, updated_at
FROM kassensitzungen ORDER BY datum DESC, created_at DESC
`

func (q *Queries) GetAllKassensitzungen(ctx context.Context) ([]Kassensitzungen, error) {
	rows, err := q.db.QueryContext(ctx, getAllKassensitzungen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kassensitzungen{}
	for rows.Next() {
		var i Kassensitzungen
		if err := rows.Scan(
			&i.ZNr,
			&i.Datum,
			&i.Bezeichnung,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKassenbestand = `-- name: GetKassenbestand :one
SELECT (
    COALESCE(SUM(kj_extract_eroeffnung_cents(type, data)), 0)::int
    + COALESCE(SUM(kj_extract_zahlung_cents(type, data)), 0)::int
    - COALESCE(SUM(kj_extract_stornierung_cents(type, data)), 0)::int
    + COALESCE(SUM(kj_extract_direktverkauf_cents(type, data)), 0)::int
    - COALESCE(SUM(kj_extract_direktverkauf_storno_cents(type, data)), 0)::int
    + COALESCE(SUM(kj_extract_geldtransit_cents(type, data)), 0)::int
    - COALESCE(SUM(kj_extract_differenz_cents(type, data)), 0)::int
)::int AS soll_bestand_cents
FROM kassenjournal
WHERE kassensitzung_nr = $1
  AND type IN (
    'kassensitzung-eroeffnet:v1',
    'zahlung-kassiert:v1',
    'stornierung-erteilt:v1',
    'direktverkauf-getaetigt:v1',
    'direktverkauf-storniert:v1',
    'geldtransit-gebucht:v1',
    'differenz-soll-ist-gebucht:v1'
  )
`

// Kassenbestand (Soll): Summe aus Anfangsbestand, Zahlungen, Warenrücknahmen, Geldtransits und Differenz-Buchungen.
// Die kassenwirksame Warenrücknahme (stornierung-erteilt) gibt Bargeld zurück und mindert den Bestand;
// geldneutrale Vorgänge (bestellung-korrigiert, bestellung-umgebucht) berühren den Kassenbestand nicht.
// Die Differenz ist als Soll − Ist gebucht; ihre Bargeldwirkung ist Ist − Soll und wird deshalb
// subtrahiert: Nach der Differenzbuchung entspricht der Soll-Bestand dem gezählten Ist-Bestand.
func (q *Queries) GetKassenbestand(ctx context.Context, kassensitzungNr int) (int, error) {
	row := q.db.QueryRowContext(ctx, getKassenbestand, kassensitzungNr)
	var soll_bestand_cents int
	err := row.Scan(&soll_bestand_cents)
	return soll_bestand_cents, err
}

const getKassensitzungStatusForShare = `-- name: GetKassensitzungStatusForShare :one
SELECT status FROM kassensitzungen WHERE z_nr = $1 FOR SHARE
`

// Status-Guard für Event-Writes: sperrt die Kassensitzungs-Zeile mit FOR SHARE,
// damit der Statuswechsel auf 'wird_abgeschlossen' (UPDATE = FOR UPDATE) erst nach
// Commit der laufenden Event-Transaktion durchkommt — und umgekehrt spätere Writes
// den neuen Status sehen und abgelehnt werden.
func (q *Queries) GetKassensitzungStatusForShare(ctx context.Context, zNr int) (string, error) {
	row := q.db.QueryRowContext(ctx, getKassensitzungStatusForShare, zNr)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getOffeneKassensitzung = `-- name: GetOffeneKassensitzung :one
SELECT z_nr, datum, bezeichnung, status, created_at, updated_at
FROM kassensitzungen WHERE status = 'offen' LIMIT 1
`

func (q *Queries) GetOffeneKassensitzung(ctx context.Context) (Kassensitzungen, error) {
	row := q.db.QueryRowContext(ctx, getOffeneKassensitzung)
	var i Kassensitzungen
	err := row.Scan(
		&i.ZNr,
		&i.Datum,
		&i.Bezeichnung,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertKassensitzung = `-- name: InsertKassensitzung :one
INSERT INTO kassensitzungen (datum, bezeichnung, status, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW()) RETURNING z_nr
`

type InsertKassensitzungParams struct {
	Datum       time.Time
	Bezeichnung string
	Status      string
}

func (q *Queries) InsertKassensitzung(ctx context.Context, arg InsertKassensitzungParams) (int, error) {
	row := q.db.QueryRowContext(ctx, insertKassensitzung, arg.Datum, arg.Bezeichnung, arg.Status)
	var z_nr int
	err := row.Scan(&z_nr)
	return z_nr, err
}

const setKassensitzungOffen = `-- name: SetKassensitzungOffen :execrows
UPDATE kassensitzungen SET status = 'offen', updated_at = NOW()
WHERE z_nr = $1 AND status = 'wird_abgeschlossen'
`

// Rücksetzen der Barriere nach einem Fehler im Abschluss (best effort), damit die Sitzung
// nicht im Zwischenstatus hängen bleibt. Nur wirksam, solange sie noch nicht abgeschlossen ist.
func (q *Queries) SetKassensitzungOffen(ctx context.Context, zNr int) (int64, error) {
	result, err := q.db.ExecContext(ctx, setKassensitzungOffen, zNr)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setKassensitzungWirdAbgeschlossen = `-- name: SetKassensitzungWirdAbgeschlossen :execrows
UPDATE kassensitzungen SET status = 'wird_abgeschlossen', updated_at = NOW()
WHERE z_nr = $1 AND status IN ('offen', 'wird_abgeschlossen')
`

// Erster Schritt des Abschlusses: setzt die Barriere. Der UPDATE (FOR UPDATE) wartet auf
// alle noch laufenden Buchungs-Transaktionen (FOR SHARE) und ist idempotent, sodass ein
// Wiederholungs-Aufruf im Zwischenstatus fortsetzt. Liefert 0, wenn die Sitzung bereits
// abgeschlossen ist.
func (q *Queries) SetKassensitzungWirdAbgeschlossen(ctx context.Context, zNr int) (int64, error) {
	result, err := q.db.ExecContext(ctx, setKassensitzungWirdAbgeschlossen, zNr)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateKassensitzung = `-- name: UpdateKassensitzung :exec
UPDATE kassensitzungen SET status = $2, updated_at = NOW() WHERE z_nr = $1
`

type UpdateKassensitzungParams struct {
	ZNr    int
	Status string
}

func (q *Queries) UpdateKassensitzung(ctx context.Context, arg UpdateKassensitzungParams) error {
	_, err := q.db.ExecContext(ctx, updateKassensitzung, arg.ZNr, arg.Status)
	return err
}
