// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kassenjournal.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const getDistinctSubjects = `-- name: GetDistinctSubjects :many
SELECT DISTINCT subject FROM kassenjournal ORDER BY subject ASC
`

func (q *Queries) GetDistinctSubjects(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var subject string
		if err := rows.Scan(&subject); err != nil {
			return nil, err
		}
		items = append(items, subject)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxVersion = `-- name: GetMaxVersion :one
SELECT COALESCE(MAX(version), 0)::int AS version FROM kassenjournal WHERE subject = $1
`

func (q *Queries) GetMaxVersion(ctx context.Context, subject string) (int, error) {
	row := q.db.QueryRowContext(ctx, getMaxVersion, subject)
	var version int
	err := row.Scan(&version)
	return version, err
}

const readDirektverkaufEvents = `-- name: ReadDirektverkaufEvents :many
SELECT id, user_id, user_name, version, type, subject, data, timestamp, kassensitzung_nr
FROM kassenjournal
WHERE kassensitzung_nr = $1
  AND type IN ('direktverkauf-getaetigt:v1', 'direktverkauf-storniert:v1')
ORDER BY id ASC
`

type ReadDirektverkaufEventsRow struct {
	ID              int
	UserID          int
	UserName        string
	Version         int
	Type            string
	Subject         string
	Data            json.RawMessage
	Timestamp       time.Time
	KassensitzungNr int
}

func (q *Queries) ReadDirektverkaufEvents(ctx context.Context, kassensitzungNr int) ([]ReadDirektverkaufEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, readDirektverkaufEvents, kassensitzungNr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadDirektverkaufEventsRow{}
	for rows.Next() {
		var i ReadDirektverkaufEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.Version,
			&i.Type,
			&i.Subject,
			&i.Data,
			&i.Timestamp,
			&i.KassensitzungNr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readEventsBySubject = `-- name: ReadEventsBySubject :many
SELECT id, user_id, user_name, version, type, subject, data, timestamp, kassensitzung_nr
FROM kassenjournal WHERE subject = $1 ORDER BY id ASC
`

type ReadEventsBySubjectRow struct {
	ID              int
	UserID          int
	UserName        string
	Version         int
	Type            string
	Subject         string
	Data            json.RawMessage
	Timestamp       time.Time
	KassensitzungNr int
}

func (q *Queries) ReadEventsBySubject(ctx context.Context, subject string) ([]ReadEventsBySubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, readEventsBySubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadEventsBySubjectRow{}
	for rows.Next() {
		var i ReadEventsBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.Version,
			&i.Type,
			&i.Subject,
			&i.Data,
			&i.Timestamp,
			&i.KassensitzungNr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeEvent = `-- name: WriteEvent :one
INSERT INTO kassenjournal (user_id, user_name, type, subject, version, data, timestamp, kassensitzung_nr)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id
`

type WriteEventParams struct {
	UserID          int
	UserName        string
	Type            string
	Subject         string
	Version         int
	Data            json.RawMessage
	Timestamp       time.Time
	KassensitzungNr int
}

func (q *Queries) WriteEvent(ctx context.Context, arg WriteEventParams) (int, error) {
	row := q.db.QueryRowContext(ctx, writeEvent,
		arg.UserID,
		arg.UserName,
		arg.Type,
		arg.Subject,
		arg.Version,
		arg.Data,
		arg.Timestamp,
		arg.KassensitzungNr,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}
