// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: kassensitzungen.sql

package dbgen

import (
	"context"
	"time"
)

const deleteAllKassensitzungen = `-- name: DeleteAllKassensitzungen :exec
DELETE FROM kassensitzungen
`

func (q *Queries) DeleteAllKassensitzungen(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllKassensitzungen)
	return err
}

const getKassenbestand = `-- name: GetKassenbestand :one
SELECT COALESCE(SUM(CASE
    WHEN type = 'anfangsbestand-gesetzt:v1'
        THEN (data->>'betragCents')::INT
    WHEN type = 'zahlung-kassiert:v1'
        THEN (data->>'gesamtZahlungCents')::INT
    WHEN type = 'auszahlung-geleistet:v1'
        THEN -(data->>'betragCents')::INT
    WHEN type = 'kassenbewegung-gebucht:v1' AND data->>'art' = 'privateinlage'
        THEN (data->>'betragCents')::INT
    WHEN type = 'kassenbewegung-gebucht:v1' AND data->>'art' IN ('privatentnahme', 'geldtransit')
        THEN -(data->>'betragCents')::INT
    WHEN type = 'differenz-soll-ist-gebucht:v1'
        THEN (data->>'betragCents')::INT
    ELSE 0
END), 0)::int AS soll_bestand_cents
FROM kassenjournal
WHERE kassensitzung_nr = $1
  AND type IN (
    'anfangsbestand-gesetzt:v1',
    'zahlung-kassiert:v1',
    'auszahlung-geleistet:v1',
    'kassenbewegung-gebucht:v1',
    'differenz-soll-ist-gebucht:v1'
  )
`

// Kassenbestand (Soll): Summe aus Anfangsbestand, Zahlungen, Auszahlungen, Kassenbewegungen und Differenz-Buchungen.
func (q *Queries) GetKassenbestand(ctx context.Context, kassensitzungNr int) (int, error) {
	row := q.db.QueryRowContext(ctx, getKassenbestand, kassensitzungNr)
	var soll_bestand_cents int
	err := row.Scan(&soll_bestand_cents)
	return soll_bestand_cents, err
}

const getKassensitzungByZNr = `-- name: GetKassensitzungByZNr :one
SELECT z_nr, datum, bezeichnung, status, created_at, updated_at
FROM kassensitzungen WHERE z_nr = $1
`

func (q *Queries) GetKassensitzungByZNr(ctx context.Context, zNr int) (Kassensitzungen, error) {
	row := q.db.QueryRowContext(ctx, getKassensitzungByZNr, zNr)
	var i Kassensitzungen
	err := row.Scan(
		&i.ZNr,
		&i.Datum,
		&i.Bezeichnung,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextZNr = `-- name: GetNextZNr :one
SELECT COALESCE(MAX(z_nr), 0) + 1 AS next_z_nr FROM kassensitzungen
`

func (q *Queries) GetNextZNr(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNextZNr)
	var next_z_nr int32
	err := row.Scan(&next_z_nr)
	return next_z_nr, err
}

const getOffeneKassensitzung = `-- name: GetOffeneKassensitzung :one
SELECT z_nr, datum, bezeichnung, status, created_at, updated_at
FROM kassensitzungen WHERE status = 'offen' LIMIT 1
`

func (q *Queries) GetOffeneKassensitzung(ctx context.Context) (Kassensitzungen, error) {
	row := q.db.QueryRowContext(ctx, getOffeneKassensitzung)
	var i Kassensitzungen
	err := row.Scan(
		&i.ZNr,
		&i.Datum,
		&i.Bezeichnung,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertKassensitzung = `-- name: InsertKassensitzung :one
INSERT INTO kassensitzungen (datum, bezeichnung, status, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW()) RETURNING z_nr
`

type InsertKassensitzungParams struct {
	Datum       time.Time
	Bezeichnung string
	Status      string
}

func (q *Queries) InsertKassensitzung(ctx context.Context, arg InsertKassensitzungParams) (int, error) {
	row := q.db.QueryRowContext(ctx, insertKassensitzung, arg.Datum, arg.Bezeichnung, arg.Status)
	var z_nr int
	err := row.Scan(&z_nr)
	return z_nr, err
}

const updateKassensitzungStatus = `-- name: UpdateKassensitzungStatus :exec
UPDATE kassensitzungen SET status = $2, updated_at = NOW() WHERE z_nr = $1
`

type UpdateKassensitzungStatusParams struct {
	ZNr    int
	Status string
}

func (q *Queries) UpdateKassensitzungStatus(ctx context.Context, arg UpdateKassensitzungStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateKassensitzungStatus, arg.ZNr, arg.Status)
	return err
}
