// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Druckstationkategorie string

const (
	DruckstationkategorieEssen       Druckstationkategorie = "essen"
	DruckstationkategorieGetraenk    Druckstationkategorie = "getraenk"
	DruckstationkategorieSonstiges   Druckstationkategorie = "sonstiges"
	DruckstationkategorieKassenbeleg Druckstationkategorie = "kassenbeleg"
	DruckstationkategorieAbholbon    Druckstationkategorie = "abholbon"
)

func (e *Druckstationkategorie) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Druckstationkategorie(s)
	case string:
		*e = Druckstationkategorie(s)
	default:
		return fmt.Errorf("unsupported scan type for Druckstationkategorie: %T", src)
	}
	return nil
}

type NullDruckstationkategorie struct {
	Druckstationkategorie Druckstationkategorie
	Valid                 bool // Valid is true if Druckstationkategorie is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDruckstationkategorie) Scan(value interface{}) error {
	if value == nil {
		ns.Druckstationkategorie, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Druckstationkategorie.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDruckstationkategorie) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Druckstationkategorie), nil
}

type Entitystatus string

const (
	EntitystatusActive   Entitystatus = "active"
	EntitystatusInactive Entitystatus = "inactive"
	EntitystatusDeleted  Entitystatus = "deleted"
)

func (e *Entitystatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Entitystatus(s)
	case string:
		*e = Entitystatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Entitystatus: %T", src)
	}
	return nil
}

type NullEntitystatus struct {
	Entitystatus Entitystatus
	Valid        bool // Valid is true if Entitystatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitystatus) Scan(value interface{}) error {
	if value == nil {
		ns.Entitystatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Entitystatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitystatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Entitystatus), nil
}

type Produktkategorie string

const (
	ProduktkategorieEssen     Produktkategorie = "essen"
	ProduktkategorieGetraenk  Produktkategorie = "getraenk"
	ProduktkategorieSonstiges Produktkategorie = "sonstiges"
)

func (e *Produktkategorie) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Produktkategorie(s)
	case string:
		*e = Produktkategorie(s)
	default:
		return fmt.Errorf("unsupported scan type for Produktkategorie: %T", src)
	}
	return nil
}

type NullProduktkategorie struct {
	Produktkategorie Produktkategorie
	Valid            bool // Valid is true if Produktkategorie is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProduktkategorie) Scan(value interface{}) error {
	if value == nil {
		ns.Produktkategorie, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Produktkategorie.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProduktkategorie) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Produktkategorie), nil
}

type Steuersatz string

const (
	SteuersatzRegel      Steuersatz = "regel"
	SteuersatzErmaessigt Steuersatz = "ermaessigt"
	SteuersatzBefreit    Steuersatz = "befreit"
	SteuersatzKombi      Steuersatz = "kombi"
)

func (e *Steuersatz) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Steuersatz(s)
	case string:
		*e = Steuersatz(s)
	default:
		return fmt.Errorf("unsupported scan type for Steuersatz: %T", src)
	}
	return nil
}

type NullSteuersatz struct {
	Steuersatz Steuersatz
	Valid      bool // Valid is true if Steuersatz is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSteuersatz) Scan(value interface{}) error {
	if value == nil {
		ns.Steuersatz, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Steuersatz.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSteuersatz) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Steuersatz), nil
}

type Userrole string

const (
	UserroleAdmin          Userrole = "admin"
	UserroleServiceleitung Userrole = "serviceleitung"
	UserroleService        Userrole = "service"
)

func (e *Userrole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Userrole(s)
	case string:
		*e = Userrole(s)
	default:
		return fmt.Errorf("unsupported scan type for Userrole: %T", src)
	}
	return nil
}

type NullUserrole struct {
	Userrole Userrole
	Valid    bool // Valid is true if Userrole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserrole) Scan(value interface{}) error {
	if value == nil {
		ns.Userrole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Userrole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserrole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Userrole), nil
}

// Betreiber-Stammdaten (Singleton). Pflichtfeld vor erster Kassensitzung.
type Betreiber struct {
	ID int
	// Name des Vereins / Betreibers
	Vereinsname string
	// Straße und Hausnummer
	Strasse string
	// Postleitzahl
	Plz string
	// Ort
	Ort string
	// Steuernummer (optional)
	Steuernummer sql.NullString
	// USt-ID (optional)
	UstID sql.NullString
	// Letzte Änderung (UTC)
	UpdatedAt time.Time
}

// Technische Outbox-Warteschlange fuer Druckjobs (Arbeitsbon und Kassenbeleg).
type Druckauftraege struct {
	ID     int32
	ZielIp string
	// Base64-kodierter ESC/POS-Byte-String.
	Payload string
	// Druckstatus: offen -> gedruckt.
	Status string
	BonArt string
	// Fachliche Referenz (z. B. Event- oder Zahlung-ID) fuer Nachvollziehbarkeit.
	Referenz   string
	ErstelltAm time.Time
	GedrucktAm sql.NullTime
}

// Drucker-IP und (außer für Kassenbeleg) Bonmodus je Druckstation für den Bondruck.
type Druckstationen struct {
	Kategorie Druckstationkategorie
	// IPv4-Adresse des Bondruckers (leer = kein Drucker konfiguriert)
	DruckerIp string
	// Bonmodus: pro_position (1 Bon pro Position) oder pro_bestellung (1 Sammelbon) für essen/getraenk/sonstiges/abholbon; NULL für kassenbeleg.
	Bonmodus  sql.NullString
	UpdatedAt time.Time
}

// Kassenidentität (Singleton). Einmalig bei der DB-Migration eingebrannt, danach read-only (insert-once).
type Kassenidentitaet struct {
	ID int
	// UUID-v4 Seriennummer der Kasse — nie überschreiben
	Seriennummer uuid.UUID
	// Zeitpunkt der ersten Inbetriebnahme (UTC)
	AngelegtAm time.Time
}

// Append-only Kassenjournal (Event Store) for all kasse operations (event-sourcing)
type Kassenjournal struct {
	ID int
	// Actor who triggered the event
	UserID int
	// Display name of the actor at the time of the event
	UserName string
	// Event type identifier, e.g., bestellung-aufgenommen:v1
	Type string
	// Aggregate key, e.g. "kassensitzung-1/tisch-42" for a tisch session, "kassensitzung-1" for a kassensitzung
	Subject string
	// Optimistic concurrency version per subject (monotonically increasing)
	Version int
	// Event time (UTC)
	Timestamp time.Time
	// Event data (jsonb), versioned by type
	Data json.RawMessage
	// Kassensitzung number (z_nr) this event belongs to
	KassensitzungNr int
}

// CRUD entity for Kassensitzung lifecycle. Each row represents one Kassensitzung (one Betriebstag). The z_nr is the DSFinV-K-compliant sequential number.
type Kassensitzungen struct {
	// Fortlaufende Kassensitzungsnummer (Z_NR), DSFinV-K-Pflichtfeld
	ZNr int
	// Betriebstag der Kassensitzung
	Datum time.Time
	// Bezeichnung (z.B. "Sommerfest Tag 1")
	Bezeichnung string
	// Kassensitzung-Status: offen oder abgeschlossen
	Status string
	// Creation timestamp (UTC)
	CreatedAt time.Time
	// Last modification timestamp (UTC)
	UpdatedAt time.Time
}

// Varianten von Produkten (verschiedene Größen, Optionen, etc.).
type ProduktVarianten struct {
	ID        int
	ProduktID int
	// Name der Produktvariante
	Name string
	// Preis in Cent (z.B. 199 für 1,99 €)
	PreisCents int
	// Varianten-Status: active, inactive oder deleted
	Status Entitystatus
	// Creation timestamp (UTC)
	CreatedAt time.Time
	// Last modification timestamp (UTC)
	UpdatedAt time.Time
}

// Produkte, die von Gästen bestellt werden können.
type Produkte struct {
	ID int
	// Name des Produkts
	Name string
	// Kategorie des Produkts: essen, getraenk oder sonstiges
	Kategorie Produktkategorie
	// Steuersatz des Produkts: regel, ermaessigt, befreit oder kombi
	Steuersatz Steuersatz
	// Produkt-Status: active, inactive oder deleted
	Status Entitystatus
	// Creation timestamp (UTC)
	CreatedAt time.Time
	// Last modification timestamp (UTC)
	UpdatedAt time.Time
}

// Per-user favourite tables; each service user can mark tables they are responsible for.
type TischFavoriten struct {
	UserID    int
	TischID   int
	CreatedAt time.Time
}

// Synchronous CQRS projection of per-tisch-session state, session-scoped (PK: subject), updated within the event-write transaction
type TischSession struct {
	Subject                string
	TischID                int
	KassensitzungNr        int
	SaldoCents             int
	UnbezahltePositionen   json.RawMessage
	AusstehendePositionen  json.RawMessage
	GesamtZahlungenCents   int
	ErsteBestellungLogtime sql.NullTime
	LastEventID            int
	LastEventVersion       int
	UpdatedAt              time.Time
}

// Gäste sitzen an Tischen und geben dort Bestellungen auf.
type Tische struct {
	ID int
	// Name oder Nummer des Tisches (z.B. "Tisch 1")
	Name string
	// Tisch-Status: active, inactive oder deleted
	Status Entitystatus
	// Creation timestamp (UTC)
	CreatedAt time.Time
	// Last modification timestamp (UTC)
	UpdatedAt time.Time
}

// TSE-Konfiguration (Singleton). Speichert API-Zugangsdaten fuer die Cloud-TSE-Integration.
type TseKonfiguration struct {
	ID int
	// API-Key fuer den TSE-Anbieter.
	ApiKey string
	// API-Secret fuer den TSE-Anbieter.
	ApiSecret string
	// TSS-ID der TSE-Instanz.
	TssID string
	// Client-ID innerhalb der TSS.
	ClientID string
	// Letzte Aenderung (UTC)
	UpdatedAt time.Time
}

// Technische Outbox fuer Nachsignierung bei TSE-Ausfall.
type TseNachsignierAuftraege struct {
	ID int32
	// Deterministische TSE-Transaktions-ID pro Vorgang.
	TxID string
	// fiskaly process_type, z. B. Kassenbeleg-V1.
	ProcessType string
	// fiskaly process_data fuer die Nachsignierung.
	ProcessData string
	// Nachsignierstatus: offen -> erledigt.
	Status     string
	ErstelltAm time.Time
	ErledigtAm sql.NullTime
}

// Signatur-Seitentabelle fuer nachsignierte Vorgaenge (Happy Path bleibt im Event).
type TseSignaturen struct {
	ID int32
	// Deterministische TSE-Transaktions-ID (1:1 zu einem fiskalischen Vorgang).
	TxID              string
	TransaktionNummer int
	SignaturZaehler   int
	TseSeriennummer   string
	LogTimeStart      time.Time
	LogTimeEnd        time.Time
	Signatur          string
	// DSFinV-K QR-Code-Daten aus der TSE-Antwort.
	QrCodeData string
	ErstelltAm time.Time
}

// System users who perform actions in jotti
type User struct {
	ID int
	// Full name of the user
	Name string
	// Unique username
	Username string
	// Argon2id password hash; NULL if user has not set a password (on first login)
	PasswordHash sql.NullString
	// Argon2id password hash for a one-time password. That can be used to setup a new user or reset their password as an admin. NULL if not set
	OnetimePasswordHash sql.NullString
	// Role of the user, determining access rights
	Role Userrole
	// Account status: active, inactive, or deleted
	Status Entitystatus
	// Creation timestamp (UTC)
	CreatedAt time.Time
	// Last modification timestamp (UTC)
	UpdatedAt time.Time
}
