// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type Entitystatus string

const (
	EntitystatusActive   Entitystatus = "active"
	EntitystatusInactive Entitystatus = "inactive"
	EntitystatusDeleted  Entitystatus = "deleted"
)

func (e *Entitystatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Entitystatus(s)
	case string:
		*e = Entitystatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Entitystatus: %T", src)
	}
	return nil
}

type NullEntitystatus struct {
	Entitystatus Entitystatus
	Valid        bool // Valid is true if Entitystatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntitystatus) Scan(value interface{}) error {
	if value == nil {
		ns.Entitystatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Entitystatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntitystatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Entitystatus), nil
}

type Produktkategorie string

const (
	ProduktkategorieEssen     Produktkategorie = "essen"
	ProduktkategorieGetraenk  Produktkategorie = "getraenk"
	ProduktkategorieSonstiges Produktkategorie = "sonstiges"
)

func (e *Produktkategorie) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Produktkategorie(s)
	case string:
		*e = Produktkategorie(s)
	default:
		return fmt.Errorf("unsupported scan type for Produktkategorie: %T", src)
	}
	return nil
}

type NullProduktkategorie struct {
	Produktkategorie Produktkategorie
	Valid            bool // Valid is true if Produktkategorie is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProduktkategorie) Scan(value interface{}) error {
	if value == nil {
		ns.Produktkategorie, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Produktkategorie.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProduktkategorie) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Produktkategorie), nil
}

type Userrole string

const (
	UserroleAdmin          Userrole = "admin"
	UserroleServiceleitung Userrole = "serviceleitung"
	UserroleService        Userrole = "service"
)

func (e *Userrole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Userrole(s)
	case string:
		*e = Userrole(s)
	default:
		return fmt.Errorf("unsupported scan type for Userrole: %T", src)
	}
	return nil
}

type NullUserrole struct {
	Userrole Userrole
	Valid    bool // Valid is true if Userrole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserrole) Scan(value interface{}) error {
	if value == nil {
		ns.Userrole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Userrole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserrole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Userrole), nil
}

// Event log for orders/payments and admin actions (event-sourcing)
type Event struct {
	ID int
	// Actor who triggered the event
	UserID int
	// Display name of the actor at the time of the event
	UserName string
	// Event type identifier, e.g., bestellung-aufgegeben:v1
	Type string
	// Aggregate key, e.g. "table:42" for table ID 42
	Subject string
	// Optimistic concurrency version per subject (monotonically increasing)
	Version int
	// Event time (UTC)
	Timestamp time.Time
	// Event data (jsonb), versioned by type
	Data json.RawMessage
}

// Varianten von Produkten (verschiedene Größen, Optionen, etc.).
type ProduktVarianten struct {
	ID        int
	ProduktID int
	// Name der Produktvariante
	Name string
	// Preis in Cent (z.B. 199 für 1,99 €)
	PreisCents int
	// Varianten-Status: active, inactive oder deleted
	Status Entitystatus
	// Creation timestamp (UTC)
	CreatedAt time.Time
	// Last modification timestamp (UTC)
	UpdatedAt time.Time
}

// Produkte, die von Gästen bestellt werden können.
type Produkte struct {
	ID int
	// Name des Produkts
	Name string
	// Kategorie des Produkts: essen, getraenk oder sonstiges
	Kategorie Produktkategorie
	// Produkt-Status: active, inactive oder deleted
	Status Entitystatus
	// Creation timestamp (UTC)
	CreatedAt time.Time
	// Last modification timestamp (UTC)
	UpdatedAt time.Time
}

// Synchronous CQRS projection of per-table state, updated within the event-write transaction
type TableState struct {
	TischID               int
	SaldoCents            int
	UnbezahltePositionen  json.RawMessage
	AusstehendePositionen json.RawMessage
	GesamtZahlungenCents  int
	LastEventID           int
	LastEventVersion      int
	UpdatedAt             time.Time
}

// Gäste sitzen an Tischen und geben dort Bestellungen auf.
type Tische struct {
	ID int
	// Name oder Nummer des Tisches (z.B. "Tisch 1")
	Name string
	// Tisch-Status: active, inactive oder deleted
	Status Entitystatus
	// Creation timestamp (UTC)
	CreatedAt time.Time
	// Last modification timestamp (UTC)
	UpdatedAt time.Time
}

// System users who perform actions in jotti
type User struct {
	ID int
	// Full name of the user
	Name string
	// Unique username
	Username string
	// Argon2id password hash; NULL if user has not set a password (on first login)
	PasswordHash sql.NullString
	// Argon2id password hash for a one-time password. That can be used to setup a new user or reset their password as an admin. NULL if not set
	OnetimePasswordHash sql.NullString
	// Role of the user, determining access rights
	Role Userrole
	// Account status: active, inactive, or deleted
	Status Entitystatus
	// Creation timestamp (UTC)
	CreatedAt time.Time
	// Last modification timestamp (UTC)
	UpdatedAt time.Time
}
