// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, category, created_at)
VALUES ($1, $2, $3) RETURNING id
`

type CreateProductParams struct {
	Name      string
	Category  Productcategory
	CreatedAt time.Time
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Name, arg.Category, arg.CreatedAt)
	var id int
	err := row.Scan(&id)
	return id, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO product_variants (product_id, name, price_cents, status, created_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateVariantParams struct {
	ProductID  int
	Name       string
	PriceCents int
	Status     Entitystatus
	CreatedAt  time.Time
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createVariant,
		arg.ProductID,
		arg.Name,
		arg.PriceCents,
		arg.Status,
		arg.CreatedAt,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getActiveProducts = `-- name: GetActiveProducts :many
WITH variant_json AS (
    SELECT 
        product_id,
        json_agg(
            json_build_object(
                'id', id,
                'name', name,
                'price_cents', price_cents,
                'status', status,
                'created_at', created_at
            )
        ) AS variants
    FROM product_variants
    WHERE status = 'active'
    GROUP BY product_id
)
SELECT 
    p.id,
    p.name,
    p.category,
    p.created_at,
    vj.variants::json AS variants
FROM products p
INNER JOIN variant_json vj ON vj.product_id = p.id
ORDER BY p.id ASC
`

type GetActiveProductsRow struct {
	ID        int
	Name      string
	Category  Productcategory
	CreatedAt time.Time
	Variants  json.RawMessage
}

func (q *Queries) GetActiveProducts(ctx context.Context) ([]GetActiveProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveProductsRow{}
	for rows.Next() {
		var i GetActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.CreatedAt,
			&i.Variants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProducts = `-- name: GetAllProducts :many
WITH variant_json AS (
    SELECT 
        product_id,
        json_agg(
            json_build_object(
                'id', id,
                'name', name,
                'price_cents', price_cents,
                'status', status,
                'created_at', created_at
            )
        ) AS variants
    FROM product_variants
    WHERE status != 'deleted'
    GROUP BY product_id
)
SELECT 
    p.id,
    p.name,
    p.category,
    p.created_at,
    COALESCE(vj.variants, '[]')::json AS variants
FROM products p
LEFT JOIN variant_json vj ON vj.product_id = p.id
ORDER BY p.id ASC
`

type GetAllProductsRow struct {
	ID        int
	Name      string
	Category  Productcategory
	CreatedAt time.Time
	Variants  json.RawMessage
}

func (q *Queries) GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllProductsRow{}
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.CreatedAt,
			&i.Variants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT 
    p.id,
    p.name,
    p.category,
    p.created_at,
    COALESCE(
        (SELECT json_agg(
            json_build_object(
                'id', pv.id,
                'name', pv.name,
                'price_cents', pv.price_cents,
                'status', pv.status,
                'created_at', pv.created_at
            )
        )
        FROM product_variants pv
        WHERE pv.product_id = p.id AND pv.status != 'deleted'),
        '[]'
    )::json AS variants
FROM products p
WHERE p.id = $1
`

type GetProductRow struct {
	ID        int
	Name      string
	Category  Productcategory
	CreatedAt time.Time
	Variants  json.RawMessage
}

func (q *Queries) GetProduct(ctx context.Context, id int) (GetProductRow, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
		&i.Variants,
	)
	return i, err
}

const getVariant = `-- name: GetVariant :one
SELECT id, name, price_cents, status, created_at
FROM product_variants WHERE id = $1 AND status != 'deleted'
`

type GetVariantRow struct {
	ID         int
	Name       string
	PriceCents int
	Status     Entitystatus
	CreatedAt  time.Time
}

func (q *Queries) GetVariant(ctx context.Context, id int) (GetVariantRow, error) {
	row := q.db.QueryRowContext(ctx, getVariant, id)
	var i GetVariantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :execresult
UPDATE products SET name = $1, category = $2 WHERE id = $3
`

type UpdateProductParams struct {
	Name     string
	Category Productcategory
	ID       int
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProduct, arg.Name, arg.Category, arg.ID)
}

const updateVariant = `-- name: UpdateVariant :execresult
UPDATE product_variants SET name = $1, price_cents = $2, status = $3 WHERE id = $4
`

type UpdateVariantParams struct {
	Name       string
	PriceCents int
	Status     Entitystatus
	ID         int
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateVariant,
		arg.Name,
		arg.PriceCents,
		arg.Status,
		arg.ID,
	)
}
