// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: produkte.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createProdukt = `-- name: CreateProdukt :one
INSERT INTO produkte (name, kategorie, steuersatz, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type CreateProduktParams struct {
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateProdukt(ctx context.Context, arg CreateProduktParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createProdukt,
		arg.Name,
		arg.Kategorie,
		arg.Steuersatz,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const createVariante = `-- name: CreateVariante :one
INSERT INTO produkt_varianten (produkt_id, name, preis_cents, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type CreateVarianteParams struct {
	ProduktID  int
	Name       string
	PreisCents int
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateVariante(ctx context.Context, arg CreateVarianteParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createVariante,
		arg.ProduktID,
		arg.Name,
		arg.PreisCents,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getAktiveProdukte = `-- name: GetAktiveProdukte :many
WITH varianten_json AS (
    SELECT 
        produkt_id,
        json_agg(
            json_build_object(
                'id', id,
                'name', name,
                'preisCents', preis_cents,
                'status', status,
                'createdAt', created_at,
                'updatedAt', updated_at
            )
            ORDER BY id
        ) AS varianten
    FROM produkt_varianten
    WHERE status = 'active'
    GROUP BY produkt_id
)
SELECT 
    p.id,
    p.name,
    p.kategorie,
    p.steuersatz,
    p.status,
    p.created_at,
    p.updated_at,
    vj.varianten::json AS varianten
FROM produkte p
INNER JOIN varianten_json vj ON vj.produkt_id = p.id
WHERE p.status = 'active'
ORDER BY p.id ASC
`

type GetAktiveProdukteRow struct {
	ID         int
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Varianten  json.RawMessage
}

// Bestelliste fuer den Service: nur aktive Produkte mit mindestens einer aktiven Variante.
// Der INNER JOIN blendet aktive Produkte ohne aktive (bepreiste) Variante bewusst aus,
// da sie nicht bestellbar sind. Die Admin-Sicht (GetAlleProdukte) zeigt sie via LEFT JOIN.
func (q *Queries) GetAktiveProdukte(ctx context.Context) ([]GetAktiveProdukteRow, error) {
	rows, err := q.db.QueryContext(ctx, getAktiveProdukte)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAktiveProdukteRow{}
	for rows.Next() {
		var i GetAktiveProdukteRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kategorie,
			&i.Steuersatz,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Varianten,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlleProdukte = `-- name: GetAlleProdukte :many
WITH varianten_json AS (
    SELECT 
        produkt_id,
        json_agg(
            json_build_object(
                'id', id,
                'name', name,
                'preisCents', preis_cents,
                'status', status,
                'createdAt', created_at,
                'updatedAt', updated_at
            )
            ORDER BY id
        ) AS varianten
    FROM produkt_varianten
    WHERE status != 'deleted'
    GROUP BY produkt_id
)
SELECT 
    p.id,
    p.name,
    p.kategorie,
    p.steuersatz,
    p.status,
    p.created_at,
    p.updated_at,
    COALESCE(vj.varianten, '[]')::json AS varianten
FROM produkte p
LEFT JOIN varianten_json vj ON vj.produkt_id = p.id
WHERE p.status != 'deleted'
ORDER BY p.id ASC
`

type GetAlleProdukteRow struct {
	ID         int
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Varianten  json.RawMessage
}

func (q *Queries) GetAlleProdukte(ctx context.Context) ([]GetAlleProdukteRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlleProdukte)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAlleProdukteRow{}
	for rows.Next() {
		var i GetAlleProdukteRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kategorie,
			&i.Steuersatz,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Varianten,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProdukt = `-- name: GetProdukt :one
SELECT 
    p.id,
    p.name,
    p.kategorie,
    p.steuersatz,
    p.status,
    p.created_at,
    p.updated_at,
    COALESCE(
        (SELECT json_agg(
            json_build_object(
                'id', pv.id,
                'name', pv.name,
                'preisCents', pv.preis_cents,
                'status', pv.status,
                'createdAt', pv.created_at,
                'updatedAt', pv.updated_at
            )
            ORDER BY pv.id
        )
        FROM produkt_varianten pv
        WHERE pv.produkt_id = p.id AND pv.status != 'deleted'),
        '[]'
    )::json AS varianten
FROM produkte p
WHERE p.id = $1 AND p.status != 'deleted'
`

type GetProduktRow struct {
	ID         int
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Varianten  json.RawMessage
}

func (q *Queries) GetProdukt(ctx context.Context, id int) (GetProduktRow, error) {
	row := q.db.QueryRowContext(ctx, getProdukt, id)
	var i GetProduktRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kategorie,
		&i.Steuersatz,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Varianten,
	)
	return i, err
}

const getProduktIDsMitVerkaeufen = `-- name: GetProduktIDsMitVerkaeufen :many
SELECT DISTINCT pv.produkt_id AS produkt_id
FROM produkt_varianten pv
JOIN kassenjournal kj
    ON kj.type IN ('bestellung-aufgenommen:v1', 'direktverkauf-getaetigt:v1')
JOIN LATERAL jsonb_array_elements(kj.data->'positionen') AS position ON TRUE
WHERE (position->>'varianteId')::int = pv.id
`

// Liefert die IDs aller Produkte, von denen mindestens eine Variante in einem
// bestellung-aufgenommen:v1- oder direktverkauf-getaetigt:v1-Event vorkommt.
// Reine Projektion über das (immutable) Kassenjournal; jede Position trägt ihre
// varianteId, die auf produkt_varianten.produkt_id zurückführt. Auch soft-
// gelöschte Varianten zählen (ein verkauftes Produkt bleibt verkauft).
func (q *Queries) GetProduktIDsMitVerkaeufen(ctx context.Context) ([]int, error) {
	rows, err := q.db.QueryContext(ctx, getProduktIDsMitVerkaeufen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var produkt_id int
		if err := rows.Scan(&produkt_id); err != nil {
			return nil, err
		}
		items = append(items, produkt_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariante = `-- name: GetVariante :one
SELECT id, name, preis_cents, status, created_at, updated_at
FROM produkt_varianten WHERE id = $1 AND status != 'deleted'
`

type GetVarianteRow struct {
	ID         int
	Name       string
	PreisCents int
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) GetVariante(ctx context.Context, id int) (GetVarianteRow, error) {
	row := q.db.QueryRowContext(ctx, getVariante, id)
	var i GetVarianteRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PreisCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const produktHatVerkaeufe = `-- name: ProduktHatVerkaeufe :one
SELECT EXISTS (
    SELECT 1
    FROM produkt_varianten pv
    JOIN kassenjournal kj
        ON kj.type IN ('bestellung-aufgenommen:v1', 'direktverkauf-getaetigt:v1')
    JOIN LATERAL jsonb_array_elements(kj.data->'positionen') AS position ON TRUE
    WHERE pv.produkt_id = $1
      AND (position->>'varianteId')::int = pv.id
)::bool AS hat_verkaeufe
`

// Lösch-Guard: true, wenn eine Variante des Produkts in mindestens einem
// bestellung-aufgenommen:v1- oder direktverkauf-getaetigt:v1-Event vorkommt.
func (q *Queries) ProduktHatVerkaeufe(ctx context.Context, produktID int) (bool, error) {
	row := q.db.QueryRowContext(ctx, produktHatVerkaeufe, produktID)
	var hat_verkaeufe bool
	err := row.Scan(&hat_verkaeufe)
	return hat_verkaeufe, err
}

const updateProdukt = `-- name: UpdateProdukt :execresult
UPDATE produkte SET name = $1, kategorie = $2, steuersatz = $3, status = $4, updated_at = $5 WHERE id = $6
`

type UpdateProduktParams struct {
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	UpdatedAt  time.Time
	ID         int
}

func (q *Queries) UpdateProdukt(ctx context.Context, arg UpdateProduktParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProdukt,
		arg.Name,
		arg.Kategorie,
		arg.Steuersatz,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
}

const updateVariante = `-- name: UpdateVariante :execresult
UPDATE produkt_varianten SET name = $1, preis_cents = $2, status = $3, updated_at = $4 WHERE id = $5
`

type UpdateVarianteParams struct {
	Name       string
	PreisCents int
	Status     Entitystatus
	UpdatedAt  time.Time
	ID         int
}

func (q *Queries) UpdateVariante(ctx context.Context, arg UpdateVarianteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateVariante,
		arg.Name,
		arg.PreisCents,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
}
