// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: produkte.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createProdukt = `-- name: CreateProdukt :one
INSERT INTO produkte (name, kategorie, steuersatz, status, created_at, updated_at, reihenfolge)
VALUES ($1, $2, $3, $4, $5, $6,
    COALESCE((SELECT MAX(reihenfolge) + 1 FROM produkte WHERE kategorie = $2), 1))
RETURNING id
`

type CreateProduktParams struct {
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// Neue Produkte landen ans Ende ihrer Kategorie. Die Reihenfolge wird in der
// Datenbank berechnet, damit zwischen Lesen und Schreiben keine Luecke entsteht.
func (q *Queries) CreateProdukt(ctx context.Context, arg CreateProduktParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createProdukt,
		arg.Name,
		arg.Kategorie,
		arg.Steuersatz,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const createVariante = `-- name: CreateVariante :one
INSERT INTO produkt_varianten (produkt_id, name, preis_cents, status, created_at, updated_at, reihenfolge)
VALUES ($1, $2, $3, $4, $5, $6,
    COALESCE((SELECT MAX(reihenfolge) + 1 FROM produkt_varianten WHERE produkt_id = $1), 1))
RETURNING id
`

type CreateVarianteParams struct {
	ProduktID  int
	Name       string
	PreisCents int
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// Neue Varianten landen ans Ende ihres Produkts (siehe CreateProdukt).
func (q *Queries) CreateVariante(ctx context.Context, arg CreateVarianteParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createVariante,
		arg.ProduktID,
		arg.Name,
		arg.PreisCents,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getAktiveProdukte = `-- name: GetAktiveProdukte :many
WITH varianten_json AS (
    SELECT
        produkt_id,
        json_agg(
            json_build_object(
                'id', id,
                'name', name,
                'preisCents', preis_cents,
                'status', status,
                'createdAt', created_at,
                'updatedAt', updated_at
            )
            ORDER BY reihenfolge, id
        ) AS varianten
    FROM produkt_varianten
    WHERE status = 'active'
    GROUP BY produkt_id
)
SELECT
    p.id,
    p.name,
    p.kategorie,
    p.steuersatz,
    p.status,
    p.created_at,
    p.updated_at,
    vj.varianten::json AS varianten
FROM produkte p
INNER JOIN varianten_json vj ON vj.produkt_id = p.id
WHERE p.status = 'active'
ORDER BY p.kategorie, p.reihenfolge, p.id
`

type GetAktiveProdukteRow struct {
	ID         int
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Varianten  json.RawMessage
}

// Bestelliste fuer den Service: nur aktive Produkte mit mindestens einer aktiven Variante.
// Der INNER JOIN blendet aktive Produkte ohne aktive (bepreiste) Variante bewusst aus,
// da sie nicht bestellbar sind. Die Admin-Sicht (GetAlleProdukte) zeigt sie via LEFT JOIN.
func (q *Queries) GetAktiveProdukte(ctx context.Context) ([]GetAktiveProdukteRow, error) {
	rows, err := q.db.QueryContext(ctx, getAktiveProdukte)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAktiveProdukteRow{}
	for rows.Next() {
		var i GetAktiveProdukteRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kategorie,
			&i.Steuersatz,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Varianten,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlleProdukte = `-- name: GetAlleProdukte :many
WITH varianten_json AS (
    SELECT
        produkt_id,
        json_agg(
            json_build_object(
                'id', id,
                'name', name,
                'preisCents', preis_cents,
                'status', status,
                'createdAt', created_at,
                'updatedAt', updated_at
            )
            ORDER BY reihenfolge, id
        ) AS varianten
    FROM produkt_varianten
    WHERE status != 'deleted'
    GROUP BY produkt_id
)
SELECT
    p.id,
    p.name,
    p.kategorie,
    p.steuersatz,
    p.status,
    p.created_at,
    p.updated_at,
    COALESCE(vj.varianten, '[]')::json AS varianten
FROM produkte p
LEFT JOIN varianten_json vj ON vj.produkt_id = p.id
WHERE p.status != 'deleted'
ORDER BY p.kategorie, p.reihenfolge, p.id
`

type GetAlleProdukteRow struct {
	ID         int
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Varianten  json.RawMessage
}

func (q *Queries) GetAlleProdukte(ctx context.Context) ([]GetAlleProdukteRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlleProdukte)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAlleProdukteRow{}
	for rows.Next() {
		var i GetAlleProdukteRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kategorie,
			&i.Steuersatz,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Varianten,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProdukt = `-- name: GetProdukt :one
SELECT
    p.id,
    p.name,
    p.kategorie,
    p.steuersatz,
    p.status,
    p.created_at,
    p.updated_at,
    COALESCE(
        (SELECT json_agg(
            json_build_object(
                'id', pv.id,
                'name', pv.name,
                'preisCents', pv.preis_cents,
                'status', pv.status,
                'createdAt', pv.created_at,
                'updatedAt', pv.updated_at
            )
            ORDER BY pv.reihenfolge, pv.id
        )
        FROM produkt_varianten pv
        WHERE pv.produkt_id = p.id AND pv.status != 'deleted'),
        '[]'
    )::json AS varianten
FROM produkte p
WHERE p.id = $1 AND p.status != 'deleted'
`

type GetProduktRow struct {
	ID         int
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Varianten  json.RawMessage
}

func (q *Queries) GetProdukt(ctx context.Context, id int) (GetProduktRow, error) {
	row := q.db.QueryRowContext(ctx, getProdukt, id)
	var i GetProduktRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kategorie,
		&i.Steuersatz,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Varianten,
	)
	return i, err
}

const getProduktNachfolger = `-- name: GetProduktNachfolger :one
SELECT id, reihenfolge FROM produkte
WHERE kategorie = $1
  AND status != 'deleted'
  AND (reihenfolge > $2
       OR (reihenfolge = $2 AND id > $3))
ORDER BY reihenfolge ASC, id ASC
LIMIT 1
`

type GetProduktNachfolgerParams struct {
	Kategorie   Produktkategorie
	Reihenfolge int
	ID          int
}

type GetProduktNachfolgerRow struct {
	ID          int
	Reihenfolge int
}

func (q *Queries) GetProduktNachfolger(ctx context.Context, arg GetProduktNachfolgerParams) (GetProduktNachfolgerRow, error) {
	row := q.db.QueryRowContext(ctx, getProduktNachfolger, arg.Kategorie, arg.Reihenfolge, arg.ID)
	var i GetProduktNachfolgerRow
	err := row.Scan(&i.ID, &i.Reihenfolge)
	return i, err
}

const getProduktReihenfolge = `-- name: GetProduktReihenfolge :one
SELECT id, kategorie, reihenfolge FROM produkte WHERE id = $1 AND status != 'deleted'
`

type GetProduktReihenfolgeRow struct {
	ID          int
	Kategorie   Produktkategorie
	Reihenfolge int
}

func (q *Queries) GetProduktReihenfolge(ctx context.Context, id int) (GetProduktReihenfolgeRow, error) {
	row := q.db.QueryRowContext(ctx, getProduktReihenfolge, id)
	var i GetProduktReihenfolgeRow
	err := row.Scan(&i.ID, &i.Kategorie, &i.Reihenfolge)
	return i, err
}

const getProduktVorgaenger = `-- name: GetProduktVorgaenger :one
SELECT id, reihenfolge FROM produkte
WHERE kategorie = $1
  AND status != 'deleted'
  AND (reihenfolge < $2
       OR (reihenfolge = $2 AND id < $3))
ORDER BY reihenfolge DESC, id DESC
LIMIT 1
`

type GetProduktVorgaengerParams struct {
	Kategorie   Produktkategorie
	Reihenfolge int
	ID          int
}

type GetProduktVorgaengerRow struct {
	ID          int
	Reihenfolge int
}

// Das in der Sortierung (reihenfolge, id) unmittelbar davor liegende Produkt
// derselben Kategorie. Kein Treffer bedeutet: das Produkt steht bereits oben.
func (q *Queries) GetProduktVorgaenger(ctx context.Context, arg GetProduktVorgaengerParams) (GetProduktVorgaengerRow, error) {
	row := q.db.QueryRowContext(ctx, getProduktVorgaenger, arg.Kategorie, arg.Reihenfolge, arg.ID)
	var i GetProduktVorgaengerRow
	err := row.Scan(&i.ID, &i.Reihenfolge)
	return i, err
}

const getVariante = `-- name: GetVariante :one
SELECT id, name, preis_cents, status, created_at, updated_at
FROM produkt_varianten WHERE id = $1 AND status != 'deleted'
`

type GetVarianteRow struct {
	ID         int
	Name       string
	PreisCents int
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) GetVariante(ctx context.Context, id int) (GetVarianteRow, error) {
	row := q.db.QueryRowContext(ctx, getVariante, id)
	var i GetVarianteRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PreisCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVarianteNachfolger = `-- name: GetVarianteNachfolger :one
SELECT id, reihenfolge FROM produkt_varianten
WHERE produkt_id = $1
  AND status != 'deleted'
  AND (reihenfolge > $2
       OR (reihenfolge = $2 AND id > $3))
ORDER BY reihenfolge ASC, id ASC
LIMIT 1
`

type GetVarianteNachfolgerParams struct {
	ProduktID   int
	Reihenfolge int
	ID          int
}

type GetVarianteNachfolgerRow struct {
	ID          int
	Reihenfolge int
}

func (q *Queries) GetVarianteNachfolger(ctx context.Context, arg GetVarianteNachfolgerParams) (GetVarianteNachfolgerRow, error) {
	row := q.db.QueryRowContext(ctx, getVarianteNachfolger, arg.ProduktID, arg.Reihenfolge, arg.ID)
	var i GetVarianteNachfolgerRow
	err := row.Scan(&i.ID, &i.Reihenfolge)
	return i, err
}

const getVarianteReihenfolge = `-- name: GetVarianteReihenfolge :one
SELECT id, produkt_id, reihenfolge FROM produkt_varianten WHERE id = $1 AND status != 'deleted'
`

type GetVarianteReihenfolgeRow struct {
	ID          int
	ProduktID   int
	Reihenfolge int
}

func (q *Queries) GetVarianteReihenfolge(ctx context.Context, id int) (GetVarianteReihenfolgeRow, error) {
	row := q.db.QueryRowContext(ctx, getVarianteReihenfolge, id)
	var i GetVarianteReihenfolgeRow
	err := row.Scan(&i.ID, &i.ProduktID, &i.Reihenfolge)
	return i, err
}

const getVarianteVorgaenger = `-- name: GetVarianteVorgaenger :one
SELECT id, reihenfolge FROM produkt_varianten
WHERE produkt_id = $1
  AND status != 'deleted'
  AND (reihenfolge < $2
       OR (reihenfolge = $2 AND id < $3))
ORDER BY reihenfolge DESC, id DESC
LIMIT 1
`

type GetVarianteVorgaengerParams struct {
	ProduktID   int
	Reihenfolge int
	ID          int
}

type GetVarianteVorgaengerRow struct {
	ID          int
	Reihenfolge int
}

// Die in der Sortierung (reihenfolge, id) unmittelbar davor liegende Variante
// desselben Produkts. Kein Treffer bedeutet: die Variante steht bereits oben.
func (q *Queries) GetVarianteVorgaenger(ctx context.Context, arg GetVarianteVorgaengerParams) (GetVarianteVorgaengerRow, error) {
	row := q.db.QueryRowContext(ctx, getVarianteVorgaenger, arg.ProduktID, arg.Reihenfolge, arg.ID)
	var i GetVarianteVorgaengerRow
	err := row.Scan(&i.ID, &i.Reihenfolge)
	return i, err
}

const setProduktReihenfolge = `-- name: SetProduktReihenfolge :execresult
UPDATE produkte SET reihenfolge = $1, updated_at = $2 WHERE id = $3
`

type SetProduktReihenfolgeParams struct {
	Reihenfolge int
	UpdatedAt   time.Time
	ID          int
}

func (q *Queries) SetProduktReihenfolge(ctx context.Context, arg SetProduktReihenfolgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setProduktReihenfolge, arg.Reihenfolge, arg.UpdatedAt, arg.ID)
}

const setVarianteReihenfolge = `-- name: SetVarianteReihenfolge :execresult
UPDATE produkt_varianten SET reihenfolge = $1, updated_at = $2 WHERE id = $3
`

type SetVarianteReihenfolgeParams struct {
	Reihenfolge int
	UpdatedAt   time.Time
	ID          int
}

func (q *Queries) SetVarianteReihenfolge(ctx context.Context, arg SetVarianteReihenfolgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setVarianteReihenfolge, arg.Reihenfolge, arg.UpdatedAt, arg.ID)
}

const updateProdukt = `-- name: UpdateProdukt :execresult
UPDATE produkte SET name = $1, kategorie = $2, steuersatz = $3, status = $4, updated_at = $5 WHERE id = $6
`

type UpdateProduktParams struct {
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	UpdatedAt  time.Time
	ID         int
}

func (q *Queries) UpdateProdukt(ctx context.Context, arg UpdateProduktParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProdukt,
		arg.Name,
		arg.Kategorie,
		arg.Steuersatz,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
}

const updateVariante = `-- name: UpdateVariante :execresult
UPDATE produkt_varianten SET name = $1, preis_cents = $2, status = $3, updated_at = $4 WHERE id = $5
`

type UpdateVarianteParams struct {
	Name       string
	PreisCents int
	Status     Entitystatus
	UpdatedAt  time.Time
	ID         int
}

func (q *Queries) UpdateVariante(ctx context.Context, arg UpdateVarianteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateVariante,
		arg.Name,
		arg.PreisCents,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
}
