// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relay.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const discardAlleFehlgeschlagenenDruckauftraege = `-- name: DiscardAlleFehlgeschlagenenDruckauftraege :execrows
UPDATE druckauftraege
SET status = 'verworfen'
WHERE status = 'fehlgeschlagen'
`

func (q *Queries) DiscardAlleFehlgeschlagenenDruckauftraege(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, discardAlleFehlgeschlagenenDruckauftraege)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const discardDruckauftrag = `-- name: DiscardDruckauftrag :exec
UPDATE druckauftraege
SET status = 'verworfen'
WHERE id = $1 AND status = 'fehlgeschlagen'
`

func (q *Queries) DiscardDruckauftrag(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, discardDruckauftrag, id)
	return err
}

const getFehlgeschlageneDruckauftraege = `-- name: GetFehlgeschlageneDruckauftraege :many
SELECT id, ziel_ip, bon_art, referenz, versuche, letzter_fehler, erstellt_am
FROM druckauftraege
WHERE status = 'fehlgeschlagen'
ORDER BY id ASC
`

type GetFehlgeschlageneDruckauftraegeRow struct {
	ID            int
	ZielIp        string
	BonArt        string
	Referenz      string
	Versuche      int
	LetzterFehler sql.NullString
	ErstelltAm    time.Time
}

func (q *Queries) GetFehlgeschlageneDruckauftraege(ctx context.Context) ([]GetFehlgeschlageneDruckauftraegeRow, error) {
	rows, err := q.db.QueryContext(ctx, getFehlgeschlageneDruckauftraege)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFehlgeschlageneDruckauftraegeRow{}
	for rows.Next() {
		var i GetFehlgeschlageneDruckauftraegeRow
		if err := rows.Scan(
			&i.ID,
			&i.ZielIp,
			&i.BonArt,
			&i.Referenz,
			&i.Versuche,
			&i.LetzterFehler,
			&i.ErstelltAm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOffeneDruckauftraege = `-- name: GetOffeneDruckauftraege :many
SELECT id, ziel_ip, payload
FROM druckauftraege
WHERE status = 'offen'
  AND (naechster_versuch_ab IS NULL OR naechster_versuch_ab <= NOW())
ORDER BY id ASC
LIMIT 200
`

type GetOffeneDruckauftraegeRow struct {
	ID      int
	ZielIp  string
	Payload string
}

func (q *Queries) GetOffeneDruckauftraege(ctx context.Context) ([]GetOffeneDruckauftraegeRow, error) {
	rows, err := q.db.QueryContext(ctx, getOffeneDruckauftraege)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOffeneDruckauftraegeRow{}
	for rows.Next() {
		var i GetOffeneDruckauftraegeRow
		if err := rows.Scan(&i.ID, &i.ZielIp, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementDruckauftragFehlversuch = `-- name: IncrementDruckauftragFehlversuch :one
UPDATE druckauftraege
SET versuche = versuche + 1,
    letzter_fehler = $1,
    status = CASE WHEN versuche + 1 >= $2 THEN 'fehlgeschlagen' ELSE status END
WHERE id = $3 AND status = 'offen'
RETURNING versuche, status
`

type IncrementDruckauftragFehlversuchParams struct {
	LetzterFehler sql.NullString
	MaxVersuche   int
	ID            int
}

type IncrementDruckauftragFehlversuchRow struct {
	Versuche int
	Status   string
}

func (q *Queries) IncrementDruckauftragFehlversuch(ctx context.Context, arg IncrementDruckauftragFehlversuchParams) (IncrementDruckauftragFehlversuchRow, error) {
	row := q.db.QueryRowContext(ctx, incrementDruckauftragFehlversuch, arg.LetzterFehler, arg.MaxVersuche, arg.ID)
	var i IncrementDruckauftragFehlversuchRow
	err := row.Scan(&i.Versuche, &i.Status)
	return i, err
}

const insertDruckauftrag = `-- name: InsertDruckauftrag :exec
INSERT INTO druckauftraege (ziel_ip, payload, status, bon_art, referenz, erstellt_am)
VALUES ($1, $2, 'offen', $3, $4, NOW())
`

type InsertDruckauftragParams struct {
	ZielIp   string
	Payload  string
	BonArt   string
	Referenz string
}

func (q *Queries) InsertDruckauftrag(ctx context.Context, arg InsertDruckauftragParams) error {
	_, err := q.db.ExecContext(ctx, insertDruckauftrag,
		arg.ZielIp,
		arg.Payload,
		arg.BonArt,
		arg.Referenz,
	)
	return err
}

const markDruckauftragGedruckt = `-- name: MarkDruckauftragGedruckt :exec
UPDATE druckauftraege
SET status = 'gedruckt', gedruckt_am = NOW()
WHERE id = $1 AND status = 'offen'
`

func (q *Queries) MarkDruckauftragGedruckt(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, markDruckauftragGedruckt, id)
	return err
}

const retryDruckauftrag = `-- name: RetryDruckauftrag :exec
UPDATE druckauftraege
SET status = 'offen', versuche = 0, letzter_fehler = NULL, naechster_versuch_ab = NULL
WHERE id = $1 AND status = 'fehlgeschlagen'
`

func (q *Queries) RetryDruckauftrag(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, retryDruckauftrag, id)
	return err
}

const setDruckauftragFaelligkeit = `-- name: SetDruckauftragFaelligkeit :exec
UPDATE druckauftraege
SET naechster_versuch_ab = NOW() + ($1::int * INTERVAL '1 second')
WHERE id = $2 AND status = 'offen'
`

type SetDruckauftragFaelligkeitParams struct {
	Sekunden int
	ID       int
}

func (q *Queries) SetDruckauftragFaelligkeit(ctx context.Context, arg SetDruckauftragFaelligkeitParams) error {
	_, err := q.db.ExecContext(ctx, setDruckauftragFaelligkeit, arg.Sekunden, arg.ID)
	return err
}
