// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relay.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const getBestellungEventsSinceCursor = `-- name: GetBestellungEventsSinceCursor :many
SELECT id, user_name, subject, data, timestamp
FROM kassenjournal
WHERE type = 'bestellung-aufgenommen:v1'
  AND id > $1
ORDER BY id ASC
LIMIT 50
`

type GetBestellungEventsSinceCursorRow struct {
	ID        int
	UserName  string
	Subject   string
	Data      json.RawMessage
	Timestamp time.Time
}

func (q *Queries) GetBestellungEventsSinceCursor(ctx context.Context, id int) ([]GetBestellungEventsSinceCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, getBestellungEventsSinceCursor, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBestellungEventsSinceCursorRow{}
	for rows.Next() {
		var i GetBestellungEventsSinceCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Subject,
			&i.Data,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
