// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relay.sql

package dbgen

import (
	"context"
)

const getOffeneDruckauftraege = `-- name: GetOffeneDruckauftraege :many
SELECT id, ziel_ip, payload
FROM druckauftraege
WHERE status = 'offen'
ORDER BY id ASC
LIMIT 200
`

type GetOffeneDruckauftraegeRow struct {
	ID      int32
	ZielIp  string
	Payload string
}

func (q *Queries) GetOffeneDruckauftraege(ctx context.Context) ([]GetOffeneDruckauftraegeRow, error) {
	rows, err := q.db.QueryContext(ctx, getOffeneDruckauftraege)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOffeneDruckauftraegeRow{}
	for rows.Next() {
		var i GetOffeneDruckauftraegeRow
		if err := rows.Scan(&i.ID, &i.ZielIp, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDruckauftrag = `-- name: InsertDruckauftrag :exec
INSERT INTO druckauftraege (ziel_ip, payload, status, bon_art, referenz, erstellt_am)
VALUES ($1, $2, 'offen', $3, $4, NOW())
`

type InsertDruckauftragParams struct {
	ZielIp   string
	Payload  string
	BonArt   string
	Referenz string
}

func (q *Queries) InsertDruckauftrag(ctx context.Context, arg InsertDruckauftragParams) error {
	_, err := q.db.ExecContext(ctx, insertDruckauftrag,
		arg.ZielIp,
		arg.Payload,
		arg.BonArt,
		arg.Referenz,
	)
	return err
}

const markDruckauftragGedruckt = `-- name: MarkDruckauftragGedruckt :exec
UPDATE druckauftraege
SET status = 'gedruckt', gedruckt_am = NOW()
WHERE id = $1 AND status = 'offen'
`

func (q *Queries) MarkDruckauftragGedruckt(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markDruckauftragGedruckt, id)
	return err
}
