// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reporting.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const getAusstehendAuszahlungen = `-- name: GetAusstehendAuszahlungen :one
SELECT COALESCE(SUM(ABS(saldo_cents)), 0)::int AS ausstehend_auszahlungen_cents
FROM table_state
WHERE saldo_cents < 0
`

// Aktuelle Schulden: Summe aller negativen Tischsaldi (zeitraumunabhaengig).
func (q *Queries) GetAusstehendAuszahlungen(ctx context.Context) (int, error) {
	row := q.db.QueryRowContext(ctx, getAusstehendAuszahlungen)
	var ausstehend_auszahlungen_cents int
	err := row.Scan(&ausstehend_auszahlungen_cents)
	return ausstehend_auszahlungen_cents, err
}

const getEigeneUebersicht = `-- name: GetEigeneUebersicht :one
SELECT
    COALESCE(COUNT(CASE WHEN type = 'tisch.bestellung-aufgenommen:v1' THEN 1 END), 0)::int AS anzahl_bestellungen,
    COALESCE(SUM(CASE WHEN type = 'tisch.bestellung-aufgenommen:v1'
        THEN (data->>'gesamtPreisCents')::int END), 0)::int AS bestellungen_cents,
    COALESCE(COUNT(CASE WHEN type = 'tisch.zahlung-kassiert:v1' THEN 1 END), 0)::int AS anzahl_zahlungen,
    COALESCE(SUM(CASE WHEN type = 'tisch.zahlung-kassiert:v1'
        THEN (data->>'gesamtZahlungCents')::int END), 0)::int AS zahlungen_cents
FROM events
WHERE type IN ('tisch.bestellung-aufgenommen:v1', 'tisch.zahlung-kassiert:v1')
AND user_id = $1
`

type GetEigeneUebersichtRow struct {
	AnzahlBestellungen int
	BestellungenCents  int
	AnzahlZahlungen    int
	ZahlungenCents     int
}

// Service-Dashboard: Eigene KPIs der eingeloggten Servicekraft (allzeit).
func (q *Queries) GetEigeneUebersicht(ctx context.Context, userID int) (GetEigeneUebersichtRow, error) {
	row := q.db.QueryRowContext(ctx, getEigeneUebersicht, userID)
	var i GetEigeneUebersichtRow
	err := row.Scan(
		&i.AnzahlBestellungen,
		&i.BestellungenCents,
		&i.AnzahlZahlungen,
		&i.ZahlungenCents,
	)
	return i, err
}

const getOffeneSaldi = `-- name: GetOffeneSaldi :one
SELECT COALESCE(SUM(saldo_cents), 0)::int AS offene_saldi_cents
FROM table_state WHERE saldo_cents > 0
`

// Tagesabrechnung: Summe aller offenen Saldi (zeitraumunabhängig, aktueller Ist-Zustand).
func (q *Queries) GetOffeneSaldi(ctx context.Context) (int, error) {
	row := q.db.QueryRowContext(ctx, getOffeneSaldi)
	var offene_saldi_cents int
	err := row.Scan(&offene_saldi_cents)
	return offene_saldi_cents, err
}

const getOffeneTische = `-- name: GetOffeneTische :one
SELECT COALESCE(COUNT(*), 0)::int AS anzahl
FROM table_state WHERE saldo_cents > 0
`

// Dashboard: Anzahl Tische mit offenem Saldo > 0.
func (q *Queries) GetOffeneTische(ctx context.Context) (int, error) {
	row := q.db.QueryRowContext(ctx, getOffeneTische)
	var anzahl int
	err := row.Scan(&anzahl)
	return anzahl, err
}

const getReportingStats = `-- name: GetReportingStats :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'tisch.zahlung-kassiert:v1'
        THEN (data->>'gesamtZahlungCents')::int END), 0)::int
        - COALESCE(SUM(CASE WHEN type = 'tisch.auszahlung-geleistet:v1'
        THEN (data->>'betragCents')::int END), 0)::int AS gesamt_umsatz_cents,
    COALESCE(SUM(CASE WHEN type = 'tisch.auszahlung-geleistet:v1'
        THEN (data->>'betragCents')::int END), 0)::int AS gesamt_auszahlungen_cents,
    COALESCE(SUM(CASE WHEN type = 'tisch.bestellung-aufgenommen:v1'
        THEN (data->>'gesamtPreisCents')::int END), 0)::int AS gesamt_bestellungen_cents,
    COALESCE(SUM(CASE WHEN type = 'tisch.stornierung-erteilt:v1'
        THEN (data->>'gesamtStornierungCents')::int END), 0)::int AS gesamt_stornierungen_cents,
    COALESCE(COUNT(CASE WHEN type = 'tisch.bestellung-aufgenommen:v1' THEN 1 END), 0)::int AS anzahl_bestellungen,
    COALESCE(COUNT(CASE WHEN type = 'tisch.stornierung-erteilt:v1' THEN 1 END), 0)::int AS anzahl_stornierungen
FROM events
WHERE type IN (
    'tisch.bestellung-aufgenommen:v1',
    'tisch.zahlung-kassiert:v1',
    'tisch.stornierung-erteilt:v1',
    'tisch.auszahlung-geleistet:v1'
)
AND timestamp >= $1 AND timestamp < $2
`

type GetReportingStatsParams struct {
	Von time.Time
	Bis time.Time
}

type GetReportingStatsRow struct {
	GesamtUmsatzCents        int32
	GesamtAuszahlungenCents  int
	GesamtBestellungenCents  int
	GesamtStornierungenCents int
	AnzahlBestellungen       int
	AnzahlStornierungen      int
}

// Reporting: Aggregierte Kennzahlen im gewaehlten Abrechnungszeitraum.
func (q *Queries) GetReportingStats(ctx context.Context, arg GetReportingStatsParams) (GetReportingStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getReportingStats, arg.Von, arg.Bis)
	var i GetReportingStatsRow
	err := row.Scan(
		&i.GesamtUmsatzCents,
		&i.GesamtAuszahlungenCents,
		&i.GesamtBestellungenCents,
		&i.GesamtStornierungenCents,
		&i.AnzahlBestellungen,
		&i.AnzahlStornierungen,
	)
	return i, err
}

const getStornierungen = `-- name: GetStornierungen :many
SELECT
    e.timestamp,
    t.id AS tisch_id,
    t.name AS tisch_name,
    e.user_id,
    e.user_name,
    e.data
FROM events e
JOIN tische t ON t.id = CAST(SPLIT_PART(e.subject, ':', 2) AS INTEGER)
WHERE e.type = 'tisch.stornierung-erteilt:v1'
AND e.timestamp >= $1 AND e.timestamp < $2
ORDER BY e.timestamp DESC
`

type GetStornierungenParams struct {
	Von time.Time
	Bis time.Time
}

type GetStornierungenRow struct {
	Timestamp time.Time
	TischID   int
	TischName string
	UserID    int
	UserName  string
	Data      json.RawMessage
}

// Reporting: Stornierungsevents mit Tischname im Zeitraum.
// Events contain fat positions (produktName, varianteName, einzelpreis, menge) — parse in Go.
func (q *Queries) GetStornierungen(ctx context.Context, arg GetStornierungenParams) ([]GetStornierungenRow, error) {
	rows, err := q.db.QueryContext(ctx, getStornierungen, arg.Von, arg.Bis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStornierungenRow{}
	for rows.Next() {
		var i GetStornierungenRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.TischID,
			&i.TischName,
			&i.UserID,
			&i.UserName,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUmsatzProServicekraft = `-- name: GetUmsatzProServicekraft :many
SELECT
    user_id,
    MAX(user_name) AS user_name,
    COALESCE(SUM(CASE WHEN type = 'tisch.zahlung-kassiert:v1'
        THEN (data->>'gesamtZahlungCents')::int END), 0)::int AS zahlungen_cents,
    COALESCE(SUM(CASE WHEN type = 'tisch.auszahlung-geleistet:v1'
        THEN (data->>'betragCents')::int END), 0)::int AS auszahlungen_cents,
    COUNT(CASE WHEN type = 'tisch.zahlung-kassiert:v1' THEN 1 END)::int AS anzahl_zahlungen
FROM events
WHERE type IN ('tisch.zahlung-kassiert:v1', 'tisch.auszahlung-geleistet:v1')
AND timestamp >= $1 AND timestamp < $2
GROUP BY user_id
ORDER BY zahlungen_cents DESC
`

type GetUmsatzProServicekraftParams struct {
	Von time.Time
	Bis time.Time
}

type GetUmsatzProServicekraftRow struct {
	UserID            int
	UserName          interface{}
	ZahlungenCents    int
	AuszahlungenCents int
	AnzahlZahlungen   int
}

// Tagesabrechnung: Zahlungen und Auszahlungen gruppiert nach Servicekraft im Zeitraum.
// MAX(user_name) nimmt den lexikographisch letzten Namen bei Namensaenderungen.
func (q *Queries) GetUmsatzProServicekraft(ctx context.Context, arg GetUmsatzProServicekraftParams) ([]GetUmsatzProServicekraftRow, error) {
	rows, err := q.db.QueryContext(ctx, getUmsatzProServicekraft, arg.Von, arg.Bis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUmsatzProServicekraftRow{}
	for rows.Next() {
		var i GetUmsatzProServicekraftRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.ZahlungenCents,
			&i.AuszahlungenCents,
			&i.AnzahlZahlungen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUmsatzProTisch = `-- name: GetUmsatzProTisch :many
SELECT
    t.id AS tisch_id,
    t.name AS tisch_name,
    COALESCE(SUM(CASE WHEN e.type = 'tisch.zahlung-kassiert:v1'
        THEN (e.data->>'gesamtZahlungCents')::int END), 0)::int AS zahlungen_cents,
    COALESCE(SUM(CASE WHEN e.type = 'tisch.auszahlung-geleistet:v1'
        THEN (e.data->>'betragCents')::int END), 0)::int AS auszahlungen_cents,
    COUNT(CASE WHEN e.type = 'tisch.zahlung-kassiert:v1' THEN 1 END)::int AS anzahl_zahlungen
FROM events e
JOIN tische t ON t.id = CAST(SPLIT_PART(e.subject, ':', 2) AS INTEGER)
WHERE e.type IN ('tisch.zahlung-kassiert:v1', 'tisch.auszahlung-geleistet:v1')
AND e.timestamp >= $1 AND e.timestamp < $2
GROUP BY t.id, t.name
ORDER BY zahlungen_cents DESC
`

type GetUmsatzProTischParams struct {
	Von time.Time
	Bis time.Time
}

type GetUmsatzProTischRow struct {
	TischID           int
	TischName         string
	ZahlungenCents    int
	AuszahlungenCents int
	AnzahlZahlungen   int
}

// Tagesabrechnung: Zahlungen und Auszahlungen gruppiert nach Tisch im Zeitraum.
func (q *Queries) GetUmsatzProTisch(ctx context.Context, arg GetUmsatzProTischParams) ([]GetUmsatzProTischRow, error) {
	rows, err := q.db.QueryContext(ctx, getUmsatzProTisch, arg.Von, arg.Bis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUmsatzProTischRow{}
	for rows.Next() {
		var i GetUmsatzProTischRow
		if err := rows.Scan(
			&i.TischID,
			&i.TischName,
			&i.ZahlungenCents,
			&i.AuszahlungenCents,
			&i.AnzahlZahlungen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
