// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reporting.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const getAbrechnungStats = `-- name: GetAbrechnungStats :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'tisch.zahlung-registriert:v1'
        THEN (data->>'gesamtZahlungCents')::int END), 0)::int AS gesamt_umsatz_cents,
    COALESCE(SUM(CASE WHEN type = 'tisch.bestellung-aufgegeben:v1'
        THEN (data->>'gesamtPreisCents')::int END), 0)::int AS gesamt_bestellungen_cents,
    COALESCE(SUM(CASE WHEN type = 'tisch.produkte-storniert:v1'
        THEN (data->>'gesamtStornierungCents')::int END), 0)::int AS gesamt_stornierungen_cents,
    COALESCE(COUNT(CASE WHEN type = 'tisch.bestellung-aufgegeben:v1' THEN 1 END), 0)::int AS anzahl_bestellungen,
    COALESCE(COUNT(CASE WHEN type = 'tisch.produkte-storniert:v1' THEN 1 END), 0)::int AS anzahl_stornierungen
FROM events
WHERE type IN (
    'tisch.bestellung-aufgegeben:v1',
    'tisch.zahlung-registriert:v1',
    'tisch.produkte-storniert:v1'
)
AND timestamp >= $1 AND timestamp < $2
`

type GetAbrechnungStatsParams struct {
	Von time.Time
	Bis time.Time
}

type GetAbrechnungStatsRow struct {
	GesamtUmsatzCents        int
	GesamtBestellungenCents  int
	GesamtStornierungenCents int
	AnzahlBestellungen       int
	AnzahlStornierungen      int
}

// Tagesabrechnung: Aggregierte Kennzahlen im Abrechnungszeitraum.
func (q *Queries) GetAbrechnungStats(ctx context.Context, arg GetAbrechnungStatsParams) (GetAbrechnungStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAbrechnungStats, arg.Von, arg.Bis)
	var i GetAbrechnungStatsRow
	err := row.Scan(
		&i.GesamtUmsatzCents,
		&i.GesamtBestellungenCents,
		&i.GesamtStornierungenCents,
		&i.AnzahlBestellungen,
		&i.AnzahlStornierungen,
	)
	return i, err
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'tisch.zahlung-registriert:v1'
        THEN (data->>'gesamtZahlungCents')::int END), 0)::int AS gesamt_umsatz_cents,
    COALESCE(SUM(CASE WHEN type = 'tisch.bestellung-aufgegeben:v1'
        THEN (data->>'gesamtPreisCents')::int END), 0)::int AS gesamt_bestellungen_cents,
    COALESCE(SUM(CASE WHEN type = 'tisch.produkte-storniert:v1'
        THEN (data->>'gesamtStornierungCents')::int END), 0)::int AS gesamt_stornierungen_cents,
    COALESCE(COUNT(CASE WHEN type = 'tisch.bestellung-aufgegeben:v1' THEN 1 END), 0)::int AS anzahl_bestellungen,
    COALESCE(COUNT(CASE WHEN type = 'tisch.produkte-storniert:v1' THEN 1 END), 0)::int AS anzahl_stornierungen
FROM events
WHERE type IN (
    'tisch.bestellung-aufgegeben:v1',
    'tisch.zahlung-registriert:v1',
    'tisch.produkte-storniert:v1'
)
`

type GetDashboardStatsRow struct {
	GesamtUmsatzCents        int
	GesamtBestellungenCents  int
	GesamtStornierungenCents int
	AnzahlBestellungen       int
	AnzahlStornierungen      int
}

// Dashboard: Gesamtumsatz (Zahlungen), Bestellungen, Stornierungen — alle Daten (kein Zeitraumfilter).
func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.GesamtUmsatzCents,
		&i.GesamtBestellungenCents,
		&i.GesamtStornierungenCents,
		&i.AnzahlBestellungen,
		&i.AnzahlStornierungen,
	)
	return i, err
}

const getOffeneSaldi = `-- name: GetOffeneSaldi :one
SELECT COALESCE(SUM(saldo_cents), 0)::int AS offene_saldi_cents
FROM table_state WHERE saldo_cents > 0
`

// Tagesabrechnung: Summe aller offenen Saldi (zeitraumunabhängig, aktueller Ist-Zustand).
func (q *Queries) GetOffeneSaldi(ctx context.Context) (int, error) {
	row := q.db.QueryRowContext(ctx, getOffeneSaldi)
	var offene_saldi_cents int
	err := row.Scan(&offene_saldi_cents)
	return offene_saldi_cents, err
}

const getOffeneTische = `-- name: GetOffeneTische :one
SELECT COALESCE(COUNT(*), 0)::int AS anzahl
FROM table_state WHERE saldo_cents > 0
`

// Dashboard: Anzahl Tische mit offenem Saldo > 0.
func (q *Queries) GetOffeneTische(ctx context.Context) (int, error) {
	row := q.db.QueryRowContext(ctx, getOffeneTische)
	var anzahl int
	err := row.Scan(&anzahl)
	return anzahl, err
}

const getStornierungen = `-- name: GetStornierungen :many
SELECT
    e.timestamp,
    t.id AS tisch_id,
    t.name AS tisch_name,
    e.user_id,
    e.user_name,
    e.data
FROM events e
JOIN tische t ON t.id = CAST(SPLIT_PART(e.subject, ':', 2) AS INTEGER)
WHERE e.type = 'tisch.produkte-storniert:v1'
AND e.timestamp >= $1 AND e.timestamp < $2
ORDER BY e.timestamp DESC
`

type GetStornierungenParams struct {
	Von time.Time
	Bis time.Time
}

type GetStornierungenRow struct {
	Timestamp time.Time
	TischID   int
	TischName string
	UserID    int
	UserName  string
	Data      json.RawMessage
}

// Tagesabrechnung: Stornierungsevents mit Tischname im Zeitraum.
// Events contain fat positions (produktName, varianteName, einzelpreis, menge) — parse in Go.
func (q *Queries) GetStornierungen(ctx context.Context, arg GetStornierungenParams) ([]GetStornierungenRow, error) {
	rows, err := q.db.QueryContext(ctx, getStornierungen, arg.Von, arg.Bis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStornierungenRow{}
	for rows.Next() {
		var i GetStornierungenRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.TischID,
			&i.TischName,
			&i.UserID,
			&i.UserName,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUmsatzProServicekraft = `-- name: GetUmsatzProServicekraft :many
SELECT
    user_id,
    user_name,
    COALESCE(SUM((data->>'gesamtZahlungCents')::int), 0)::int AS zahlungen_cents,
    COUNT(*)::int AS anzahl_zahlungen
FROM events
WHERE type = 'tisch.zahlung-registriert:v1'
AND timestamp >= $1 AND timestamp < $2
GROUP BY user_id, user_name
ORDER BY zahlungen_cents DESC
`

type GetUmsatzProServicekraftParams struct {
	Von time.Time
	Bis time.Time
}

type GetUmsatzProServicekraftRow struct {
	UserID          int
	UserName        string
	ZahlungenCents  int
	AnzahlZahlungen int
}

// Tagesabrechnung: Zahlungen gruppiert nach Servicekraft im Zeitraum.
func (q *Queries) GetUmsatzProServicekraft(ctx context.Context, arg GetUmsatzProServicekraftParams) ([]GetUmsatzProServicekraftRow, error) {
	rows, err := q.db.QueryContext(ctx, getUmsatzProServicekraft, arg.Von, arg.Bis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUmsatzProServicekraftRow{}
	for rows.Next() {
		var i GetUmsatzProServicekraftRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.ZahlungenCents,
			&i.AnzahlZahlungen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUmsatzProTisch = `-- name: GetUmsatzProTisch :many
SELECT
    t.id AS tisch_id,
    t.name AS tisch_name,
    COALESCE(SUM((e.data->>'gesamtZahlungCents')::int), 0)::int AS zahlungen_cents,
    COUNT(*)::int AS anzahl_zahlungen
FROM events e
JOIN tische t ON t.id = CAST(SPLIT_PART(e.subject, ':', 2) AS INTEGER)
WHERE e.type = 'tisch.zahlung-registriert:v1'
AND e.timestamp >= $1 AND e.timestamp < $2
GROUP BY t.id, t.name
ORDER BY zahlungen_cents DESC
`

type GetUmsatzProTischParams struct {
	Von time.Time
	Bis time.Time
}

type GetUmsatzProTischRow struct {
	TischID         int
	TischName       string
	ZahlungenCents  int
	AnzahlZahlungen int
}

// Tagesabrechnung: Zahlungen gruppiert nach Tisch im Zeitraum.
func (q *Queries) GetUmsatzProTisch(ctx context.Context, arg GetUmsatzProTischParams) ([]GetUmsatzProTischRow, error) {
	rows, err := q.db.QueryContext(ctx, getUmsatzProTisch, arg.Von, arg.Bis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUmsatzProTischRow{}
	for rows.Next() {
		var i GetUmsatzProTischRow
		if err := rows.Scan(
			&i.TischID,
			&i.TischName,
			&i.ZahlungenCents,
			&i.AnzahlZahlungen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
