// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const seedCountKassenjournal = `-- name: SeedCountKassenjournal :one

SELECT COUNT(*)::int AS count FROM kassenjournal
`

// Queries für den Demo-Daten-Seeder (backend/seed). Die Insert-Queries setzen die IDs
// explizit (Stammdaten und Kassensitzungen referenzieren sich gegenseitig), die Reset-Queries
// ziehen die IDENTITY-Sequenzen anschließend auf den höchsten vergebenen Wert nach.
func (q *Queries) SeedCountKassenjournal(ctx context.Context) (int, error) {
	row := q.db.QueryRowContext(ctx, seedCountKassenjournal)
	var count int
	err := row.Scan(&count)
	return count, err
}

const seedInsertDruckauftrag = `-- name: SeedInsertDruckauftrag :exec
INSERT INTO druckauftraege (ziel_ip, payload, status, bon_art, referenz, versuche, letzter_fehler, erstellt_am, gedruckt_am)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type SeedInsertDruckauftragParams struct {
	ZielIp        string
	Payload       string
	Status        string
	BonArt        string
	Referenz      string
	Versuche      int
	LetzterFehler sql.NullString
	ErstelltAm    time.Time
	GedrucktAm    sql.NullTime
}

func (q *Queries) SeedInsertDruckauftrag(ctx context.Context, arg SeedInsertDruckauftragParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertDruckauftrag,
		arg.ZielIp,
		arg.Payload,
		arg.Status,
		arg.BonArt,
		arg.Referenz,
		arg.Versuche,
		arg.LetzterFehler,
		arg.ErstelltAm,
		arg.GedrucktAm,
	)
	return err
}

const seedInsertEvent = `-- name: SeedInsertEvent :exec
INSERT INTO kassenjournal (id, user_id, user_name, type, subject, version, data, timestamp, kassensitzung_nr)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type SeedInsertEventParams struct {
	ID              int
	UserID          int
	UserName        string
	Type            string
	Subject         string
	Version         int
	Data            json.RawMessage
	Timestamp       time.Time
	KassensitzungNr int
}

func (q *Queries) SeedInsertEvent(ctx context.Context, arg SeedInsertEventParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertEvent,
		arg.ID,
		arg.UserID,
		arg.UserName,
		arg.Type,
		arg.Subject,
		arg.Version,
		arg.Data,
		arg.Timestamp,
		arg.KassensitzungNr,
	)
	return err
}

const seedInsertKassensitzung = `-- name: SeedInsertKassensitzung :exec
INSERT INTO kassensitzungen (z_nr, datum, bezeichnung, status, created_at, updated_at)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4, $5, $6)
`

type SeedInsertKassensitzungParams struct {
	ZNr         int
	Datum       time.Time
	Bezeichnung string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) SeedInsertKassensitzung(ctx context.Context, arg SeedInsertKassensitzungParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertKassensitzung,
		arg.ZNr,
		arg.Datum,
		arg.Bezeichnung,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedInsertLeereTSEKonfiguration = `-- name: SeedInsertLeereTSEKonfiguration :exec
INSERT INTO tse_konfiguration (id, api_key, api_secret, tss_id, client_id, updated_at)
VALUES (1, '', '', '', '', NOW())
`

// SeedInsertLeereTSEKonfiguration stellt nach dem Truncate die leere
// Singleton-Zeile der tse_konfiguration wieder her, die die Migration beim
// Erstlauf anlegt. Ohne sie bliebe die Tabelle nach einem Reset dauerhaft leer
// und ein Folge-Reseed liefe auf einen anderen Ausgangszustand.
func (q *Queries) SeedInsertLeereTSEKonfiguration(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedInsertLeereTSEKonfiguration)
	return err
}

const seedInsertProdukt = `-- name: SeedInsertProdukt :exec
INSERT INTO produkte (id, name, kategorie, steuersatz, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SeedInsertProduktParams struct {
	ID         int
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) SeedInsertProdukt(ctx context.Context, arg SeedInsertProduktParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertProdukt,
		arg.ID,
		arg.Name,
		arg.Kategorie,
		arg.Steuersatz,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedInsertTSESignaturauftrag = `-- name: SeedInsertTSESignaturauftrag :exec
INSERT INTO tse_signaturauftraege (event_id, tx_id, process_type, process_data, status, versuche, letzter_fehler, naechster_versuch_am, erstellt_am, erledigt_am,
    transaktion_nummer, signatur_zaehler, tse_seriennummer, log_time_start, log_time_end, signatur, qr_code_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
`

type SeedInsertTSESignaturauftragParams struct {
	EventID            int
	TxID               string
	ProcessType        string
	ProcessData        string
	Status             string
	Versuche           int
	LetzterFehler      sql.NullString
	NaechsterVersuchAm time.Time
	ErstelltAm         time.Time
	ErledigtAm         sql.NullTime
	TransaktionNummer  sql.NullInt64
	SignaturZaehler    sql.NullInt64
	TseSeriennummer    sql.NullString
	LogTimeStart       sql.NullTime
	LogTimeEnd         sql.NullTime
	Signatur           sql.NullString
	QrCodeData         sql.NullString
}

func (q *Queries) SeedInsertTSESignaturauftrag(ctx context.Context, arg SeedInsertTSESignaturauftragParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertTSESignaturauftrag,
		arg.EventID,
		arg.TxID,
		arg.ProcessType,
		arg.ProcessData,
		arg.Status,
		arg.Versuche,
		arg.LetzterFehler,
		arg.NaechsterVersuchAm,
		arg.ErstelltAm,
		arg.ErledigtAm,
		arg.TransaktionNummer,
		arg.SignaturZaehler,
		arg.TseSeriennummer,
		arg.LogTimeStart,
		arg.LogTimeEnd,
		arg.Signatur,
		arg.QrCodeData,
	)
	return err
}

const seedInsertTSEStoerung = `-- name: SeedInsertTSEStoerung :exec
INSERT INTO tse_stoerungen (beginn, ende, grund_art, fehlertext)
VALUES ($1, $2, $3, $4)
`

type SeedInsertTSEStoerungParams struct {
	Beginn     time.Time
	Ende       sql.NullTime
	GrundArt   string
	Fehlertext string
}

// SeedInsertTSEStoerung schreibt einen abgeschlossenen Stoerungszeitraum des
// Demo-Szenarios (aufgeloestes Ausfallfenster) ins Stoerungsprotokoll.
func (q *Queries) SeedInsertTSEStoerung(ctx context.Context, arg SeedInsertTSEStoerungParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertTSEStoerung,
		arg.Beginn,
		arg.Ende,
		arg.GrundArt,
		arg.Fehlertext,
	)
	return err
}

const seedInsertTisch = `-- name: SeedInsertTisch :exec
INSERT INTO tische (id, name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type SeedInsertTischParams struct {
	ID        int
	Name      string
	Status    Entitystatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) SeedInsertTisch(ctx context.Context, arg SeedInsertTischParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertTisch,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedInsertUser = `-- name: SeedInsertUser :exec
INSERT INTO users (id, name, username, password_hash, role, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SeedInsertUserParams struct {
	ID           int
	Name         string
	Username     string
	PasswordHash sql.NullString
	Role         Userrole
	Status       Entitystatus
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) SeedInsertUser(ctx context.Context, arg SeedInsertUserParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedInsertVariante = `-- name: SeedInsertVariante :exec
INSERT INTO produkt_varianten (id, produkt_id, name, preis_cents, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SeedInsertVarianteParams struct {
	ID         int
	ProduktID  int
	Name       string
	PreisCents int
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) SeedInsertVariante(ctx context.Context, arg SeedInsertVarianteParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertVariante,
		arg.ID,
		arg.ProduktID,
		arg.Name,
		arg.PreisCents,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedResetKassenjournalSeq = `-- name: SeedResetKassenjournalSeq :exec
SELECT setval(pg_get_serial_sequence('kassenjournal', 'id'), COALESCE((SELECT MAX(id) FROM kassenjournal), 1))
`

func (q *Queries) SeedResetKassenjournalSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedResetKassenjournalSeq)
	return err
}

const seedResetKassensitzungenSeq = `-- name: SeedResetKassensitzungenSeq :exec
SELECT setval(pg_get_serial_sequence('kassensitzungen', 'z_nr'), COALESCE((SELECT MAX(z_nr) FROM kassensitzungen), 1))
`

func (q *Queries) SeedResetKassensitzungenSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedResetKassensitzungenSeq)
	return err
}

const seedResetProdukteSeq = `-- name: SeedResetProdukteSeq :exec
SELECT setval(pg_get_serial_sequence('produkte', 'id'), COALESCE((SELECT MAX(id) FROM produkte), 1))
`

func (q *Queries) SeedResetProdukteSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedResetProdukteSeq)
	return err
}

const seedResetTischeSeq = `-- name: SeedResetTischeSeq :exec
SELECT setval(pg_get_serial_sequence('tische', 'id'), COALESCE((SELECT MAX(id) FROM tische), 1))
`

func (q *Queries) SeedResetTischeSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedResetTischeSeq)
	return err
}

const seedResetUsersSeq = `-- name: SeedResetUsersSeq :exec
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1))
`

func (q *Queries) SeedResetUsersSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedResetUsersSeq)
	return err
}

const seedResetVariantenSeq = `-- name: SeedResetVariantenSeq :exec
SELECT setval(pg_get_serial_sequence('produkt_varianten', 'id'), COALESCE((SELECT MAX(id) FROM produkt_varianten), 1))
`

func (q *Queries) SeedResetVariantenSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedResetVariantenSeq)
	return err
}

const seedTruncateAll = `-- name: SeedTruncateAll :exec
TRUNCATE TABLE
    kassenjournal,
    tisch_sessions,
    kassensitzungen,
    tisch_favoriten,
    produkt_varianten,
    produkte,
    tische,
    users,
    betreiber,
    druckauftraege,
    druckstationen,
    tse_konfiguration,
    tse_stammdaten,
    tse_signaturauftraege,
    tse_stoerungen
RESTART IDENTITY CASCADE
`

// SeedTruncateAll leert alle Daten-Tabellen (Kassenjournal, Projektionen,
// Stammdaten, TSE-Zustand) und setzt die IDENTITY-Sequenzen zurueck. Nur fuer
// den Test-Reset-Endpoint (POST /test/reset-and-seed); danach schreibt der
// Seeder den Demo-Zustand neu. CASCADE loest die Fremdschluessel-Reihenfolge auf.
// kassenidentitaet bleibt bewusst aussen vor: sie ist die einmalig bei der
// DB-Migration eingebrannte Install-Identitaet (kein Demo-Datum, insert-once)
// und wird ausserhalb der Migration nie neu geschrieben.
func (q *Queries) SeedTruncateAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedTruncateAll)
	return err
}
