// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seed.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const seedCountKassenjournal = `-- name: SeedCountKassenjournal :one

SELECT COUNT(*)::int AS count FROM kassenjournal
`

// Queries für den Demo-Daten-Seeder (backend/seed). Die Insert-Queries setzen die IDs
// explizit (Stammdaten und Kassensitzungen referenzieren sich gegenseitig), die Reset-Queries
// ziehen die IDENTITY-Sequenzen anschließend auf den höchsten vergebenen Wert nach.
func (q *Queries) SeedCountKassenjournal(ctx context.Context) (int, error) {
	row := q.db.QueryRowContext(ctx, seedCountKassenjournal)
	var count int
	err := row.Scan(&count)
	return count, err
}

const seedInsertKassensitzung = `-- name: SeedInsertKassensitzung :exec
INSERT INTO kassensitzungen (z_nr, datum, bezeichnung, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SeedInsertKassensitzungParams struct {
	ZNr         int
	Datum       time.Time
	Bezeichnung string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) SeedInsertKassensitzung(ctx context.Context, arg SeedInsertKassensitzungParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertKassensitzung,
		arg.ZNr,
		arg.Datum,
		arg.Bezeichnung,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedInsertProdukt = `-- name: SeedInsertProdukt :exec
INSERT INTO produkte (id, name, kategorie, steuersatz, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SeedInsertProduktParams struct {
	ID         int
	Name       string
	Kategorie  Produktkategorie
	Steuersatz Steuersatz
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) SeedInsertProdukt(ctx context.Context, arg SeedInsertProduktParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertProdukt,
		arg.ID,
		arg.Name,
		arg.Kategorie,
		arg.Steuersatz,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedInsertTSENachsignierAuftrag = `-- name: SeedInsertTSENachsignierAuftrag :exec
INSERT INTO tse_nachsignier_auftraege (tx_id, process_type, process_data, status, versuche, letzter_fehler, naechster_versuch_am, erstellt_am, erledigt_am)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type SeedInsertTSENachsignierAuftragParams struct {
	TxID               string
	ProcessType        string
	ProcessData        string
	Status             string
	Versuche           int
	LetzterFehler      sql.NullString
	NaechsterVersuchAm time.Time
	ErstelltAm         time.Time
	ErledigtAm         sql.NullTime
}

func (q *Queries) SeedInsertTSENachsignierAuftrag(ctx context.Context, arg SeedInsertTSENachsignierAuftragParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertTSENachsignierAuftrag,
		arg.TxID,
		arg.ProcessType,
		arg.ProcessData,
		arg.Status,
		arg.Versuche,
		arg.LetzterFehler,
		arg.NaechsterVersuchAm,
		arg.ErstelltAm,
		arg.ErledigtAm,
	)
	return err
}

const seedInsertTSESignatur = `-- name: SeedInsertTSESignatur :exec
INSERT INTO tse_signaturen (tx_id, transaktion_nummer, signatur_zaehler, tse_seriennummer, log_time_start, log_time_end, signatur, qr_code_data, erstellt_am)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type SeedInsertTSESignaturParams struct {
	TxID              string
	TransaktionNummer int
	SignaturZaehler   int
	TseSeriennummer   string
	LogTimeStart      time.Time
	LogTimeEnd        time.Time
	Signatur          string
	QrCodeData        string
	ErstelltAm        time.Time
}

func (q *Queries) SeedInsertTSESignatur(ctx context.Context, arg SeedInsertTSESignaturParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertTSESignatur,
		arg.TxID,
		arg.TransaktionNummer,
		arg.SignaturZaehler,
		arg.TseSeriennummer,
		arg.LogTimeStart,
		arg.LogTimeEnd,
		arg.Signatur,
		arg.QrCodeData,
		arg.ErstelltAm,
	)
	return err
}

const seedInsertTisch = `-- name: SeedInsertTisch :exec
INSERT INTO tische (id, name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type SeedInsertTischParams struct {
	ID        int
	Name      string
	Status    Entitystatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) SeedInsertTisch(ctx context.Context, arg SeedInsertTischParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertTisch,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedInsertUser = `-- name: SeedInsertUser :exec
INSERT INTO users (id, name, username, password_hash, role, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SeedInsertUserParams struct {
	ID           int
	Name         string
	Username     string
	PasswordHash sql.NullString
	Role         Userrole
	Status       Entitystatus
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) SeedInsertUser(ctx context.Context, arg SeedInsertUserParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedInsertVariante = `-- name: SeedInsertVariante :exec
INSERT INTO produkt_varianten (id, produkt_id, name, preis_cents, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SeedInsertVarianteParams struct {
	ID         int
	ProduktID  int
	Name       string
	PreisCents int
	Status     Entitystatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) SeedInsertVariante(ctx context.Context, arg SeedInsertVarianteParams) error {
	_, err := q.db.ExecContext(ctx, seedInsertVariante,
		arg.ID,
		arg.ProduktID,
		arg.Name,
		arg.PreisCents,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedResetKassensitzungenSeq = `-- name: SeedResetKassensitzungenSeq :exec
SELECT setval(pg_get_serial_sequence('kassensitzungen', 'z_nr'), COALESCE((SELECT MAX(z_nr) FROM kassensitzungen), 1))
`

func (q *Queries) SeedResetKassensitzungenSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedResetKassensitzungenSeq)
	return err
}

const seedResetProdukteSeq = `-- name: SeedResetProdukteSeq :exec
SELECT setval(pg_get_serial_sequence('produkte', 'id'), COALESCE((SELECT MAX(id) FROM produkte), 1))
`

func (q *Queries) SeedResetProdukteSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedResetProdukteSeq)
	return err
}

const seedResetTischeSeq = `-- name: SeedResetTischeSeq :exec
SELECT setval(pg_get_serial_sequence('tische', 'id'), COALESCE((SELECT MAX(id) FROM tische), 1))
`

func (q *Queries) SeedResetTischeSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedResetTischeSeq)
	return err
}

const seedResetUsersSeq = `-- name: SeedResetUsersSeq :exec
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1))
`

func (q *Queries) SeedResetUsersSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedResetUsersSeq)
	return err
}

const seedResetVariantenSeq = `-- name: SeedResetVariantenSeq :exec
SELECT setval(pg_get_serial_sequence('produkt_varianten', 'id'), COALESCE((SELECT MAX(id) FROM produkt_varianten), 1))
`

func (q *Queries) SeedResetVariantenSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedResetVariantenSeq)
	return err
}
