// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_config.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSystemConfig = `-- name: GetSystemConfig :one
SELECT seriennummer, angelegt_am
FROM system_config
LIMIT 1
`

type GetSystemConfigRow struct {
	Seriennummer uuid.UUID
	AngelegtAm   time.Time
}

func (q *Queries) GetSystemConfig(ctx context.Context) (GetSystemConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getSystemConfig)
	var i GetSystemConfigRow
	err := row.Scan(&i.Seriennummer, &i.AngelegtAm)
	return i, err
}
