// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tables.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createTable = `-- name: CreateTable :one
INSERT INTO tables (name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateTableParams struct {
	Name      string
	Status    Entitystatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createTable,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getActiveTables = `-- name: GetActiveTables :many
SELECT id, name, status, created_at, updated_at
FROM tables WHERE status = 'active' ORDER BY id ASC
`

func (q *Queries) GetActiveTables(ctx context.Context) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTables = `-- name: GetAllTables :many
SELECT id, name, status, created_at, updated_at
FROM tables WHERE status != 'deleted' ORDER BY id ASC
`

func (q *Queries) GetAllTables(ctx context.Context) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, getAllTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTable = `-- name: GetTable :one
SELECT id, name, status, created_at, updated_at
FROM tables WHERE id = $1 AND status != 'deleted'
`

func (q *Queries) GetTable(ctx context.Context, id int) (Table, error) {
	row := q.db.QueryRowContext(ctx, getTable, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTable = `-- name: UpdateTable :execresult
UPDATE tables SET name = $1, status = $2, updated_at = $3 WHERE id = $4
`

type UpdateTableParams struct {
	Name      string
	Status    Entitystatus
	UpdatedAt time.Time
	ID        int
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTable,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
}
