// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: table_state.sql

package dbgen

import (
	"context"
	"encoding/json"
)

const deleteAllTableState = `-- name: DeleteAllTableState :exec
DELETE FROM table_state
`

func (q *Queries) DeleteAllTableState(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTableState)
	return err
}

const getTableState = `-- name: GetTableState :one
SELECT tisch_id, saldo_cents, unbezahlte_positionen, ungelieferte_positionen, gesamt_zahlungen_cents, last_event_id, last_event_version, updated_at
FROM table_state WHERE tisch_id = $1
`

func (q *Queries) GetTableState(ctx context.Context, tischID int) (TableState, error) {
	row := q.db.QueryRowContext(ctx, getTableState, tischID)
	var i TableState
	err := row.Scan(
		&i.TischID,
		&i.SaldoCents,
		&i.UnbezahltePositionen,
		&i.UngeliefertePositionen,
		&i.GesamtZahlungenCents,
		&i.LastEventID,
		&i.LastEventVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTableState = `-- name: UpsertTableState :exec
INSERT INTO table_state (tisch_id, saldo_cents, unbezahlte_positionen, ungelieferte_positionen, gesamt_zahlungen_cents, last_event_id, last_event_version, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
ON CONFLICT (tisch_id) DO UPDATE SET
    saldo_cents = $2,
    unbezahlte_positionen = $3,
    ungelieferte_positionen = $4,
    gesamt_zahlungen_cents = $5,
    last_event_id = $6,
    last_event_version = $7,
    updated_at = NOW()
`

type UpsertTableStateParams struct {
	TischID                int
	SaldoCents             int
	UnbezahltePositionen   json.RawMessage
	UngeliefertePositionen json.RawMessage
	GesamtZahlungenCents   int
	LastEventID            int
	LastEventVersion       int
}

func (q *Queries) UpsertTableState(ctx context.Context, arg UpsertTableStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertTableState,
		arg.TischID,
		arg.SaldoCents,
		arg.UnbezahltePositionen,
		arg.UngeliefertePositionen,
		arg.GesamtZahlungenCents,
		arg.LastEventID,
		arg.LastEventVersion,
	)
	return err
}
