// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tables.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createTisch = `-- name: CreateTisch :one
INSERT INTO tische (name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateTischParams struct {
	Name      string
	Status    Entitystatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateTisch(ctx context.Context, arg CreateTischParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createTisch,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getAktiveTische = `-- name: GetAktiveTische :many
SELECT t.id, t.name, COALESCE(ts.saldo_cents, 0)::integer AS saldo_cents
FROM tische t
LEFT JOIN table_state ts ON ts.tisch_id = t.id
WHERE t.status = 'active'
ORDER BY t.id ASC
`

type GetAktiveTischeRow struct {
	ID         int
	Name       string
	SaldoCents int
}

func (q *Queries) GetAktiveTische(ctx context.Context) ([]GetAktiveTischeRow, error) {
	rows, err := q.db.QueryContext(ctx, getAktiveTische)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAktiveTischeRow{}
	for rows.Next() {
		var i GetAktiveTischeRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SaldoCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlleTische = `-- name: GetAlleTische :many
SELECT id, name, status, created_at, updated_at
FROM tische WHERE status != 'deleted' ORDER BY id ASC
`

func (q *Queries) GetAlleTische(ctx context.Context) ([]Tische, error) {
	rows, err := q.db.QueryContext(ctx, getAlleTische)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tische{}
	for rows.Next() {
		var i Tische
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTisch = `-- name: GetTisch :one
SELECT id, name, status, created_at, updated_at
FROM tische WHERE id = $1 AND status != 'deleted'
`

func (q *Queries) GetTisch(ctx context.Context, id int) (Tische, error) {
	row := q.db.QueryRowContext(ctx, getTisch, id)
	var i Tische
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTisch = `-- name: UpdateTisch :execresult
UPDATE tische SET name = $1, status = $2, updated_at = $3 WHERE id = $4
`

type UpdateTischParams struct {
	Name      string
	Status    Entitystatus
	UpdatedAt time.Time
	ID        int
}

func (q *Queries) UpdateTisch(ctx context.Context, arg UpdateTischParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTisch,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
}
