// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tisch_sessions.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const deleteAllTischSession = `-- name: DeleteAllTischSession :exec
DELETE FROM tisch_sessions
`

func (q *Queries) DeleteAllTischSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTischSession)
	return err
}

const getTischSession = `-- name: GetTischSession :one
SELECT subject, tisch_id, kassensitzung_nr, saldo_cents, unbezahlte_positionen, gesamt_zahlungen_cents, erste_bestellung_logtime, last_event_id, last_event_version, updated_at
FROM tisch_sessions WHERE subject = $1
`

func (q *Queries) GetTischSession(ctx context.Context, subject string) (TischSession, error) {
	row := q.db.QueryRowContext(ctx, getTischSession, subject)
	var i TischSession
	err := row.Scan(
		&i.Subject,
		&i.TischID,
		&i.KassensitzungNr,
		&i.SaldoCents,
		&i.UnbezahltePositionen,
		&i.GesamtZahlungenCents,
		&i.ErsteBestellungLogtime,
		&i.LastEventID,
		&i.LastEventVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getTischSessionsByKassensitzungNr = `-- name: GetTischSessionsByKassensitzungNr :many
SELECT subject, tisch_id, kassensitzung_nr, saldo_cents, unbezahlte_positionen, gesamt_zahlungen_cents, erste_bestellung_logtime, last_event_id, last_event_version, updated_at
FROM tisch_sessions WHERE kassensitzung_nr = $1
`

func (q *Queries) GetTischSessionsByKassensitzungNr(ctx context.Context, kassensitzungNr int) ([]TischSession, error) {
	rows, err := q.db.QueryContext(ctx, getTischSessionsByKassensitzungNr, kassensitzungNr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TischSession{}
	for rows.Next() {
		var i TischSession
		if err := rows.Scan(
			&i.Subject,
			&i.TischID,
			&i.KassensitzungNr,
			&i.SaldoCents,
			&i.UnbezahltePositionen,
			&i.GesamtZahlungenCents,
			&i.ErsteBestellungLogtime,
			&i.LastEventID,
			&i.LastEventVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTischSession = `-- name: UpsertTischSession :exec
INSERT INTO tisch_sessions (subject, tisch_id, kassensitzung_nr, saldo_cents, unbezahlte_positionen, gesamt_zahlungen_cents, erste_bestellung_logtime, last_event_id, last_event_version, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
ON CONFLICT (subject) DO UPDATE SET
    tisch_id = $2,
    kassensitzung_nr = $3,
    saldo_cents = $4,
    unbezahlte_positionen = $5,
    gesamt_zahlungen_cents = $6,
    erste_bestellung_logtime = $7,
    last_event_id = $8,
    last_event_version = $9,
    updated_at = NOW()
`

type UpsertTischSessionParams struct {
	Subject                string
	TischID                int
	KassensitzungNr        int
	SaldoCents             int
	UnbezahltePositionen   json.RawMessage
	GesamtZahlungenCents   int
	ErsteBestellungLogtime sql.NullTime
	LastEventID            int
	LastEventVersion       int
}

func (q *Queries) UpsertTischSession(ctx context.Context, arg UpsertTischSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertTischSession,
		arg.Subject,
		arg.TischID,
		arg.KassensitzungNr,
		arg.SaldoCents,
		arg.UnbezahltePositionen,
		arg.GesamtZahlungenCents,
		arg.ErsteBestellungLogtime,
		arg.LastEventID,
		arg.LastEventVersion,
	)
	return err
}
