// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tisch_session_state.sql

package dbgen

import (
	"context"
	"encoding/json"
)

const deleteAllTischSessionState = `-- name: DeleteAllTischSessionState :exec
DELETE FROM tisch_session_state
`

func (q *Queries) DeleteAllTischSessionState(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTischSessionState)
	return err
}

const getTischSessionState = `-- name: GetTischSessionState :one
SELECT subject, tisch_id, kassensitzung_nr, saldo_cents, unbezahlte_positionen, ausstehende_positionen, gesamt_zahlungen_cents, last_event_id, last_event_version, updated_at
FROM tisch_session_state WHERE subject = $1
`

func (q *Queries) GetTischSessionState(ctx context.Context, subject string) (TischSessionState, error) {
	row := q.db.QueryRowContext(ctx, getTischSessionState, subject)
	var i TischSessionState
	err := row.Scan(
		&i.Subject,
		&i.TischID,
		&i.KassensitzungNr,
		&i.SaldoCents,
		&i.UnbezahltePositionen,
		&i.AusstehendePositionen,
		&i.GesamtZahlungenCents,
		&i.LastEventID,
		&i.LastEventVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getTischSessionStatesByKassensitzungNr = `-- name: GetTischSessionStatesByKassensitzungNr :many
SELECT subject, tisch_id, kassensitzung_nr, saldo_cents, unbezahlte_positionen, ausstehende_positionen, gesamt_zahlungen_cents, last_event_id, last_event_version, updated_at
FROM tisch_session_state WHERE kassensitzung_nr = $1
`

func (q *Queries) GetTischSessionStatesByKassensitzungNr(ctx context.Context, kassensitzungNr int) ([]TischSessionState, error) {
	rows, err := q.db.QueryContext(ctx, getTischSessionStatesByKassensitzungNr, kassensitzungNr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TischSessionState{}
	for rows.Next() {
		var i TischSessionState
		if err := rows.Scan(
			&i.Subject,
			&i.TischID,
			&i.KassensitzungNr,
			&i.SaldoCents,
			&i.UnbezahltePositionen,
			&i.AusstehendePositionen,
			&i.GesamtZahlungenCents,
			&i.LastEventID,
			&i.LastEventVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTischSessionState = `-- name: UpsertTischSessionState :exec
INSERT INTO tisch_session_state (subject, tisch_id, kassensitzung_nr, saldo_cents, unbezahlte_positionen, ausstehende_positionen, gesamt_zahlungen_cents, last_event_id, last_event_version, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
ON CONFLICT (subject) DO UPDATE SET
    tisch_id = $2,
    kassensitzung_nr = $3,
    saldo_cents = $4,
    unbezahlte_positionen = $5,
    ausstehende_positionen = $6,
    gesamt_zahlungen_cents = $7,
    last_event_id = $8,
    last_event_version = $9,
    updated_at = NOW()
`

type UpsertTischSessionStateParams struct {
	Subject               string
	TischID               int
	KassensitzungNr       int
	SaldoCents            int
	UnbezahltePositionen  json.RawMessage
	AusstehendePositionen json.RawMessage
	GesamtZahlungenCents  int
	LastEventID           int
	LastEventVersion      int
}

func (q *Queries) UpsertTischSessionState(ctx context.Context, arg UpsertTischSessionStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertTischSessionState,
		arg.Subject,
		arg.TischID,
		arg.KassensitzungNr,
		arg.SaldoCents,
		arg.UnbezahltePositionen,
		arg.AusstehendePositionen,
		arg.GesamtZahlungenCents,
		arg.LastEventID,
		arg.LastEventVersion,
	)
	return err
}
