// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tische.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createTisch = `-- name: CreateTisch :one
INSERT INTO tische (name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateTischParams struct {
	Name      string
	Status    Entitystatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateTisch(ctx context.Context, arg CreateTischParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createTisch,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getAktiveTische = `-- name: GetAktiveTische :many
SELECT t.id, t.name, COALESCE(tss.saldo_cents, 0)::integer AS saldo_cents
FROM tische t
LEFT JOIN tisch_sessions tss ON tss.tisch_id = t.id AND tss.kassensitzung_nr = $1
WHERE t.status = 'active'
ORDER BY t.id ASC
`

type GetAktiveTischeRow struct {
	ID         int
	Name       string
	SaldoCents int
}

func (q *Queries) GetAktiveTische(ctx context.Context, kassensitzungNr int) ([]GetAktiveTischeRow, error) {
	rows, err := q.db.QueryContext(ctx, getAktiveTische, kassensitzungNr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAktiveTischeRow{}
	for rows.Next() {
		var i GetAktiveTischeRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SaldoCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAktiveTischeMitFavoriten = `-- name: GetAktiveTischeMitFavoriten :many
SELECT t.id, t.name, COALESCE(tss.saldo_cents, 0)::integer AS saldo_cents, (f.user_id IS NOT NULL)::boolean AS ist_favorit
FROM tische t
LEFT JOIN tisch_sessions tss ON tss.tisch_id = t.id AND tss.kassensitzung_nr = $2
LEFT JOIN tisch_favoriten f ON f.tisch_id = t.id AND f.user_id = $1
WHERE t.status = 'active'
ORDER BY t.id ASC
`

type GetAktiveTischeMitFavoritenParams struct {
	UserID          int
	KassensitzungNr int
}

type GetAktiveTischeMitFavoritenRow struct {
	ID         int
	Name       string
	SaldoCents int
	IstFavorit bool
}

func (q *Queries) GetAktiveTischeMitFavoriten(ctx context.Context, arg GetAktiveTischeMitFavoritenParams) ([]GetAktiveTischeMitFavoritenRow, error) {
	rows, err := q.db.QueryContext(ctx, getAktiveTischeMitFavoriten, arg.UserID, arg.KassensitzungNr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAktiveTischeMitFavoritenRow{}
	for rows.Next() {
		var i GetAktiveTischeMitFavoritenRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SaldoCents,
			&i.IstFavorit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlleTischNamen = `-- name: GetAlleTischNamen :many
SELECT id, name FROM tische ORDER BY id ASC
`

type GetAlleTischNamenRow struct {
	ID   int
	Name string
}

// Historische Namensauflösung: ALLE Tische inklusive gelöschter. Der DSFinV-K-
// Export benennt die Abrechnungskreise vergangener Kassensitzungen; ein nach
// dem Tagesabschluss gelöschter Tisch muss dort weiterhin unter seinem Namen
// erscheinen. GetAlleTische filtert 'deleted' bewusst weg und taugt dafür nicht.
func (q *Queries) GetAlleTischNamen(ctx context.Context) ([]GetAlleTischNamenRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlleTischNamen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAlleTischNamenRow{}
	for rows.Next() {
		var i GetAlleTischNamenRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlleTische = `-- name: GetAlleTische :many
SELECT id, name, status, created_at, updated_at
FROM tische WHERE status != 'deleted' ORDER BY id ASC
`

func (q *Queries) GetAlleTische(ctx context.Context) ([]Tische, error) {
	rows, err := q.db.QueryContext(ctx, getAlleTische)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tische{}
	for rows.Next() {
		var i Tische
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTisch = `-- name: GetTisch :one
SELECT id, name, status, created_at, updated_at
FROM tische WHERE id = $1 AND status != 'deleted'
`

func (q *Queries) GetTisch(ctx context.Context, id int) (Tische, error) {
	row := q.db.QueryRowContext(ctx, getTisch, id)
	var i Tische
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTischSaldiOffeneSitzung = `-- name: GetTischSaldiOffeneSitzung :many
SELECT tss.tisch_id, tss.saldo_cents
FROM tisch_sessions tss
JOIN kassensitzungen k ON k.z_nr = tss.kassensitzung_nr AND k.status = 'offen'
WHERE tss.saldo_cents > 0
`

type GetTischSaldiOffeneSitzungRow struct {
	TischID    int
	SaldoCents int
}

// Liefert je Tisch mit offenem Saldo (> 0) den Betrag aus der tisch_sessions-
// Projektion der aktuell offenen Kassensitzung. Ohne offene Sitzung ist das
// Ergebnis leer. Reine Projektion; das Kassenjournal bleibt unberührt.
func (q *Queries) GetTischSaldiOffeneSitzung(ctx context.Context) ([]GetTischSaldiOffeneSitzungRow, error) {
	rows, err := q.db.QueryContext(ctx, getTischSaldiOffeneSitzung)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTischSaldiOffeneSitzungRow{}
	for rows.Next() {
		var i GetTischSaldiOffeneSitzungRow
		if err := rows.Scan(&i.TischID, &i.SaldoCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tischHatOffenenSaldo = `-- name: TischHatOffenenSaldo :one
SELECT EXISTS (
    SELECT 1
    FROM tisch_sessions tss
    JOIN kassensitzungen k ON k.z_nr = tss.kassensitzung_nr AND k.status = 'offen'
    WHERE tss.tisch_id = $1
      AND tss.saldo_cents > 0
)::bool AS hat_offenen_saldo
`

// Schutz-Guard: true, wenn der Tisch in der offenen Kassensitzung einen
// offenen Saldo (> 0) trägt. Ohne offene Sitzung immer false.
func (q *Queries) TischHatOffenenSaldo(ctx context.Context, tischID int) (bool, error) {
	row := q.db.QueryRowContext(ctx, tischHatOffenenSaldo, tischID)
	var hat_offenen_saldo bool
	err := row.Scan(&hat_offenen_saldo)
	return hat_offenen_saldo, err
}

const updateTisch = `-- name: UpdateTisch :execresult
UPDATE tische SET name = $1, status = $2, updated_at = $3 WHERE id = $4
`

type UpdateTischParams struct {
	Name      string
	Status    Entitystatus
	UpdatedAt time.Time
	ID        int
}

func (q *Queries) UpdateTisch(ctx context.Context, arg UpdateTischParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTisch,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
}
