// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tse_konfiguration.sql

package dbgen

import (
	"context"
	"time"
)

const getTSEKonfiguration = `-- name: GetTSEKonfiguration :one
SELECT api_key, api_secret, tss_id, client_id, updated_at
FROM tse_konfiguration
WHERE id = 1
`

type GetTSEKonfigurationRow struct {
	ApiKey    string
	ApiSecret string
	TssID     string
	ClientID  string
	UpdatedAt time.Time
}

func (q *Queries) GetTSEKonfiguration(ctx context.Context) (GetTSEKonfigurationRow, error) {
	row := q.db.QueryRowContext(ctx, getTSEKonfiguration)
	var i GetTSEKonfigurationRow
	err := row.Scan(
		&i.ApiKey,
		&i.ApiSecret,
		&i.TssID,
		&i.ClientID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTSEKonfiguration = `-- name: UpsertTSEKonfiguration :exec
INSERT INTO tse_konfiguration (id, api_key, api_secret, tss_id, client_id, updated_at)
VALUES (1, $1, $2, $3, $4, NOW())
ON CONFLICT (id) DO UPDATE SET
    api_key = EXCLUDED.api_key,
    api_secret = EXCLUDED.api_secret,
    tss_id = EXCLUDED.tss_id,
    client_id = EXCLUDED.client_id,
    updated_at = EXCLUDED.updated_at
`

type UpsertTSEKonfigurationParams struct {
	ApiKey    string
	ApiSecret string
	TssID     string
	ClientID  string
}

func (q *Queries) UpsertTSEKonfiguration(ctx context.Context, arg UpsertTSEKonfigurationParams) error {
	_, err := q.db.ExecContext(ctx, upsertTSEKonfiguration,
		arg.ApiKey,
		arg.ApiSecret,
		arg.TssID,
		arg.ClientID,
	)
	return err
}
