// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tse_nachsignier.sql

package dbgen

import (
	"context"
)

const countOffeneTSENachsignierAuftraege = `-- name: CountOffeneTSENachsignierAuftraege :one
SELECT COUNT(*)::int
FROM tse_nachsignier_auftraege
WHERE status = 'offen'
`

func (q *Queries) CountOffeneTSENachsignierAuftraege(ctx context.Context) (int, error) {
	row := q.db.QueryRowContext(ctx, countOffeneTSENachsignierAuftraege)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const getOffeneTSENachsignierAuftraege = `-- name: GetOffeneTSENachsignierAuftraege :many
SELECT id, tx_id, process_type, process_data
FROM tse_nachsignier_auftraege
WHERE status = 'offen'
ORDER BY id ASC
LIMIT $1
`

type GetOffeneTSENachsignierAuftraegeRow struct {
	ID          int32
	TxID        string
	ProcessType string
	ProcessData string
}

func (q *Queries) GetOffeneTSENachsignierAuftraege(ctx context.Context, limit int32) ([]GetOffeneTSENachsignierAuftraegeRow, error) {
	rows, err := q.db.QueryContext(ctx, getOffeneTSENachsignierAuftraege, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOffeneTSENachsignierAuftraegeRow{}
	for rows.Next() {
		var i GetOffeneTSENachsignierAuftraegeRow
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.ProcessType,
			&i.ProcessData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTSENachsignierAuftrag = `-- name: InsertTSENachsignierAuftrag :exec
INSERT INTO tse_nachsignier_auftraege (tx_id, process_type, process_data, status, erstellt_am)
VALUES ($1, $2, $3, 'offen', NOW())
ON CONFLICT (tx_id) DO NOTHING
`

type InsertTSENachsignierAuftragParams struct {
	TxID        string
	ProcessType string
	ProcessData string
}

func (q *Queries) InsertTSENachsignierAuftrag(ctx context.Context, arg InsertTSENachsignierAuftragParams) error {
	_, err := q.db.ExecContext(ctx, insertTSENachsignierAuftrag, arg.TxID, arg.ProcessType, arg.ProcessData)
	return err
}

const markTSENachsignierAuftragErledigt = `-- name: MarkTSENachsignierAuftragErledigt :exec
UPDATE tse_nachsignier_auftraege
SET status = 'erledigt',
    erledigt_am = NOW()
WHERE id = $1
`

func (q *Queries) MarkTSENachsignierAuftragErledigt(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markTSENachsignierAuftragErledigt, id)
	return err
}
