// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tse_stammdaten.sql

package dbgen

import (
	"context"
	"time"
)

const getTSEStammdaten = `-- name: GetTSEStammdaten :one
SELECT signatur_algorithmus, public_key, zertifikat, log_time_format, updated_at
FROM tse_stammdaten WHERE id = 1
`

type GetTSEStammdatenRow struct {
	SignaturAlgorithmus string
	PublicKey           string
	Zertifikat          string
	LogTimeFormat       string
	UpdatedAt           time.Time
}

func (q *Queries) GetTSEStammdaten(ctx context.Context) (GetTSEStammdatenRow, error) {
	row := q.db.QueryRowContext(ctx, getTSEStammdaten)
	var i GetTSEStammdatenRow
	err := row.Scan(
		&i.SignaturAlgorithmus,
		&i.PublicKey,
		&i.Zertifikat,
		&i.LogTimeFormat,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTSEStammdaten = `-- name: UpsertTSEStammdaten :exec
INSERT INTO tse_stammdaten (id, signatur_algorithmus, public_key, zertifikat, log_time_format, updated_at)
VALUES (1, $1, $2, $3, $4, NOW())
ON CONFLICT (id) DO UPDATE SET
    signatur_algorithmus = EXCLUDED.signatur_algorithmus,
    public_key = EXCLUDED.public_key,
    zertifikat = EXCLUDED.zertifikat,
    log_time_format = EXCLUDED.log_time_format,
    updated_at = EXCLUDED.updated_at
`

type UpsertTSEStammdatenParams struct {
	SignaturAlgorithmus string
	PublicKey           string
	Zertifikat          string
	LogTimeFormat       string
}

func (q *Queries) UpsertTSEStammdaten(ctx context.Context, arg UpsertTSEStammdatenParams) error {
	_, err := q.db.ExecContext(ctx, upsertTSEStammdaten,
		arg.SignaturAlgorithmus,
		arg.PublicKey,
		arg.Zertifikat,
		arg.LogTimeFormat,
	)
	return err
}
