// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tse_signaturen.sql

package dbgen

import (
	"context"
	"time"
)

const getTSESignaturByTxID = `-- name: GetTSESignaturByTxID :one
SELECT tx_id, transaktion_nummer, signatur_zaehler, tse_seriennummer, log_time_start, log_time_end, signatur, qr_code_data
FROM tse_signaturen
WHERE tx_id = $1
`

type GetTSESignaturByTxIDRow struct {
	TxID              string
	TransaktionNummer int
	SignaturZaehler   int
	TseSeriennummer   string
	LogTimeStart      time.Time
	LogTimeEnd        time.Time
	Signatur          string
	QrCodeData        string
}

func (q *Queries) GetTSESignaturByTxID(ctx context.Context, txID string) (GetTSESignaturByTxIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTSESignaturByTxID, txID)
	var i GetTSESignaturByTxIDRow
	err := row.Scan(
		&i.TxID,
		&i.TransaktionNummer,
		&i.SignaturZaehler,
		&i.TseSeriennummer,
		&i.LogTimeStart,
		&i.LogTimeEnd,
		&i.Signatur,
		&i.QrCodeData,
	)
	return i, err
}

const upsertTSESignatur = `-- name: UpsertTSESignatur :exec
INSERT INTO tse_signaturen (
    tx_id,
    transaktion_nummer,
    signatur_zaehler,
    tse_seriennummer,
    log_time_start,
    log_time_end,
    signatur,
    qr_code_data,
    erstellt_am
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (tx_id) DO UPDATE SET
    transaktion_nummer = EXCLUDED.transaktion_nummer,
    signatur_zaehler = EXCLUDED.signatur_zaehler,
    tse_seriennummer = EXCLUDED.tse_seriennummer,
    log_time_start = EXCLUDED.log_time_start,
    log_time_end = EXCLUDED.log_time_end,
    signatur = EXCLUDED.signatur,
    qr_code_data = EXCLUDED.qr_code_data,
    erstellt_am = EXCLUDED.erstellt_am
`

type UpsertTSESignaturParams struct {
	TxID              string
	TransaktionNummer int
	SignaturZaehler   int
	TseSeriennummer   string
	LogTimeStart      time.Time
	LogTimeEnd        time.Time
	Signatur          string
	QrCodeData        string
}

func (q *Queries) UpsertTSESignatur(ctx context.Context, arg UpsertTSESignaturParams) error {
	_, err := q.db.ExecContext(ctx, upsertTSESignatur,
		arg.TxID,
		arg.TransaktionNummer,
		arg.SignaturZaehler,
		arg.TseSeriennummer,
		arg.LogTimeStart,
		arg.LogTimeEnd,
		arg.Signatur,
		arg.QrCodeData,
	)
	return err
}
