// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tse_stoerungen.sql

package dbgen

import (
	"context"
	"time"
)

const getAktiveTSEStoerung = `-- name: GetAktiveTSEStoerung :one
SELECT beginn, grund_art, fehlertext
FROM tse_stoerungen
WHERE ende IS NULL
`

type GetAktiveTSEStoerungRow struct {
	Beginn     time.Time
	GrundArt   string
	Fehlertext string
}

// GetAktiveTSEStoerung liefert den aktiven Stoerungszeitraum (hoechstens
// einer, per partiellem Unique-Index).
func (q *Queries) GetAktiveTSEStoerung(ctx context.Context) (GetAktiveTSEStoerungRow, error) {
	row := q.db.QueryRowContext(ctx, getAktiveTSEStoerung)
	var i GetAktiveTSEStoerungRow
	err := row.Scan(&i.Beginn, &i.GrundArt, &i.Fehlertext)
	return i, err
}

const oeffneTSEStoerung = `-- name: OeffneTSEStoerung :exec
INSERT INTO tse_stoerungen (beginn, grund_art, fehlertext)
VALUES (NOW(), $1, $2)
ON CONFLICT DO NOTHING
`

type OeffneTSEStoerungParams struct {
	GrundArt   string
	Fehlertext string
}

// OeffneTSEStoerung oeffnet einen Stoerungszeitraum im Stoerungsprotokoll.
// Der partielle Unique-Index (hoechstens eine Zeile mit ende IS NULL) macht
// das Oeffnen idempotent: Bei aktivem Zeitraum ist es ein No-Op.
func (q *Queries) OeffneTSEStoerung(ctx context.Context, arg OeffneTSEStoerungParams) error {
	_, err := q.db.ExecContext(ctx, oeffneTSEStoerung, arg.GrundArt, arg.Fehlertext)
	return err
}

const schliesseTSEStoerung = `-- name: SchliesseTSEStoerung :exec
UPDATE tse_stoerungen
SET ende = NOW()
WHERE ende IS NULL AND grund_art = $1
`

// SchliesseTSEStoerung beendet den aktiven Stoerungszeitraum, falls er die
// Grund-Art des Schreibers traegt (jeder Schreiber schliesst nur Zeitraeume
// seiner Grund-Art); sonst ein No-Op.
func (q *Queries) SchliesseTSEStoerung(ctx context.Context, grundArt string) error {
	_, err := q.db.ExecContext(ctx, schliesseTSEStoerung, grundArt)
	return err
}
