// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tse_stammdaten.sql

package dbgen

import (
	"context"
)

const upsertTSEStammdaten = `-- name: UpsertTSEStammdaten :exec
INSERT INTO tse_stammdaten (id, signatur_algorithmus, public_key, zertifikat, log_time_format, version, updated_at)
VALUES (1, $1, $2, $3, $4, $5, NOW())
ON CONFLICT (id) DO UPDATE SET
    signatur_algorithmus = EXCLUDED.signatur_algorithmus,
    public_key = EXCLUDED.public_key,
    zertifikat = EXCLUDED.zertifikat,
    log_time_format = EXCLUDED.log_time_format,
    version = EXCLUDED.version,
    updated_at = EXCLUDED.updated_at
`

type UpsertTSEStammdatenParams struct {
	SignaturAlgorithmus string
	PublicKey           string
	Zertifikat          string
	LogTimeFormat       string
	Version             string
}

func (q *Queries) UpsertTSEStammdaten(ctx context.Context, arg UpsertTSEStammdatenParams) error {
	_, err := q.db.ExecContext(ctx, upsertTSEStammdaten,
		arg.SignaturAlgorithmus,
		arg.PublicKey,
		arg.Zertifikat,
		arg.LogTimeFormat,
		arg.Version,
	)
	return err
}
