// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tse_signaturauftraege.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countOffeneTSESignaturauftraege = `-- name: CountOffeneTSESignaturauftraege :one
SELECT COUNT(*)::int
FROM tse_signaturauftraege
WHERE status IN ('offen', 'fehlgeschlagen')
`

// Zaehlt noch nicht erledigte Signaturauftraege (offen und fehlgeschlagen):
// beide Status bedeuten unsignierte Vorgaenge.
func (q *Queries) CountOffeneTSESignaturauftraege(ctx context.Context) (int, error) {
	row := q.db.QueryRowContext(ctx, countOffeneTSESignaturauftraege)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const getAeltesterOffenerTSESignaturauftrag = `-- name: GetAeltesterOffenerTSESignaturauftrag :one
SELECT erstellt_am
FROM tse_signaturauftraege
WHERE status = 'offen'
ORDER BY erstellt_am ASC
LIMIT 1
`

// GetAeltesterOffenerTSESignaturauftrag liefert den Erstellungszeitpunkt des
// aeltesten offenen Auftrags — der Rueckstands-Watchdog bemisst daran den
// Signatur-Rueckstand.
func (q *Queries) GetAeltesterOffenerTSESignaturauftrag(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getAeltesterOffenerTSESignaturauftrag)
	var erstellt_am time.Time
	err := row.Scan(&erstellt_am)
	return erstellt_am, err
}

const getOffeneTSESignaturauftraege = `-- name: GetOffeneTSESignaturauftraege :many
SELECT id, tx_id, process_type, process_data
FROM tse_signaturauftraege
WHERE status = 'offen'
  AND naechster_versuch_am <= NOW()
ORDER BY id ASC
LIMIT $1
`

type GetOffeneTSESignaturauftraegeRow struct {
	ID          int
	TxID        string
	ProcessType string
	ProcessData string
}

// GetOffeneTSESignaturauftraege liefert die faelligen offenen Auftraege in
// Einreihungs-Reihenfolge (FIFO als Soll-Eigenschaft).
func (q *Queries) GetOffeneTSESignaturauftraege(ctx context.Context, limit int32) ([]GetOffeneTSESignaturauftraegeRow, error) {
	rows, err := q.db.QueryContext(ctx, getOffeneTSESignaturauftraege, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOffeneTSESignaturauftraegeRow{}
	for rows.Next() {
		var i GetOffeneTSESignaturauftraegeRow
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.ProcessType,
			&i.ProcessData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTSESignaturauftraege = `-- name: GetTSESignaturauftraege :many
SELECT id, tx_id, process_type, status, versuche, letzter_fehler, erstellt_am, erledigt_am
FROM tse_signaturauftraege
ORDER BY id DESC
LIMIT 200
`

type GetTSESignaturauftraegeRow struct {
	ID            int
	TxID          string
	ProcessType   string
	Status        string
	Versuche      int
	LetzterFehler sql.NullString
	ErstelltAm    time.Time
	ErledigtAm    sql.NullTime
}

// Admin-Ansicht aller Signaturauftraege; dient zugleich als
// TSE-Ausfalldokumentation (erstellt_am = Beginn, erledigt_am = Ende).
func (q *Queries) GetTSESignaturauftraege(ctx context.Context) ([]GetTSESignaturauftraegeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTSESignaturauftraege)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTSESignaturauftraegeRow{}
	for rows.Next() {
		var i GetTSESignaturauftraegeRow
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.ProcessType,
			&i.Status,
			&i.Versuche,
			&i.LetzterFehler,
			&i.ErstelltAm,
			&i.ErledigtAm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTSESignaturauftragZuEvent = `-- name: GetTSESignaturauftragZuEvent :one
SELECT status, erstellt_am, transaktion_nummer, signatur_zaehler, tse_seriennummer, log_time_start, log_time_end, signatur, qr_code_data
FROM tse_signaturauftraege
WHERE event_id = $1
`

type GetTSESignaturauftragZuEventRow struct {
	Status            string
	ErstelltAm        time.Time
	TransaktionNummer sql.NullInt32
	SignaturZaehler   sql.NullInt32
	TseSeriennummer   sql.NullString
	LogTimeStart      sql.NullTime
	LogTimeEnd        sql.NullTime
	Signatur          sql.NullString
	QrCodeData        sql.NullString
}

// GetTSESignaturauftragZuEvent liefert den Signatur-Stand eines Events fuer den
// Beleg-Abruf: Status plus Signaturspalten (gefuellt sobald quittiert).
// Kein Treffer heisst: Das Event ist nicht signaturpflichtig.
func (q *Queries) GetTSESignaturauftragZuEvent(ctx context.Context, eventID int) (GetTSESignaturauftragZuEventRow, error) {
	row := q.db.QueryRowContext(ctx, getTSESignaturauftragZuEvent, eventID)
	var i GetTSESignaturauftragZuEventRow
	err := row.Scan(
		&i.Status,
		&i.ErstelltAm,
		&i.TransaktionNummer,
		&i.SignaturZaehler,
		&i.TseSeriennummer,
		&i.LogTimeStart,
		&i.LogTimeEnd,
		&i.Signatur,
		&i.QrCodeData,
	)
	return i, err
}

const insertTSESignaturauftrag = `-- name: InsertTSESignaturauftrag :exec
INSERT INTO tse_signaturauftraege (event_id, tx_id, process_type, process_data, status, naechster_versuch_am, erstellt_am)
VALUES ($1, $2, $3, $4, 'offen', NOW(), NOW())
`

type InsertTSESignaturauftragParams struct {
	EventID     int
	TxID        string
	ProcessType string
	ProcessData string
}

// InsertTSESignaturauftrag reiht den Signaturauftrag eines Events ein — im
// selben Commit wie das Event (transaktionale Outbox). event_id UNIQUE sichert
// genau einen Auftrag je Event.
func (q *Queries) InsertTSESignaturauftrag(ctx context.Context, arg InsertTSESignaturauftragParams) error {
	_, err := q.db.ExecContext(ctx, insertTSESignaturauftrag,
		arg.EventID,
		arg.TxID,
		arg.ProcessType,
		arg.ProcessData,
	)
	return err
}

const quittiereTSESignaturauftrag = `-- name: QuittiereTSESignaturauftrag :exec
UPDATE tse_signaturauftraege
SET status = 'erledigt',
    erledigt_am = NOW(),
    transaktion_nummer = $1,
    signatur_zaehler = $2,
    tse_seriennummer = $3,
    log_time_start = $4,
    log_time_end = $5,
    signatur = $6,
    qr_code_data = $7
WHERE id = $8 AND status = 'offen'
`

type QuittiereTSESignaturauftragParams struct {
	TransaktionNummer sql.NullInt32
	SignaturZaehler   sql.NullInt32
	TseSeriennummer   sql.NullString
	LogTimeStart      sql.NullTime
	LogTimeEnd        sql.NullTime
	Signatur          sql.NullString
	QrCodeData        sql.NullString
	ID                int
}

// QuittiereTSESignaturauftrag schreibt die Signatur als einzelnes Update an den
// Auftrag: Signaturspalten fuellen, Status erledigt. Der Status-Guard macht die
// Quittierung idempotent (Signaturspalten werden genau einmal beschrieben).
func (q *Queries) QuittiereTSESignaturauftrag(ctx context.Context, arg QuittiereTSESignaturauftragParams) error {
	_, err := q.db.ExecContext(ctx, quittiereTSESignaturauftrag,
		arg.TransaktionNummer,
		arg.SignaturZaehler,
		arg.TseSeriennummer,
		arg.LogTimeStart,
		arg.LogTimeEnd,
		arg.Signatur,
		arg.QrCodeData,
		arg.ID,
	)
	return err
}

const tSESignaturauftragFehlversuch = `-- name: TSESignaturauftragFehlversuch :exec
UPDATE tse_signaturauftraege
SET versuche = versuche + 1,
    letzter_fehler = $1,
    naechster_versuch_am = NOW() + (5 * POWER(3, versuche)) * interval '1 second',
    status = CASE WHEN versuche + 1 >= $2 THEN 'fehlgeschlagen' ELSE status END
WHERE id = $3 AND status = 'offen'
`

type TSESignaturauftragFehlversuchParams struct {
	LetzterFehler sql.NullString
	MaxVersuche   int
	ID            int
}

// TSESignaturauftragFehlversuch verbucht einen auftragsspezifischen
// Fehlversuch mit Sekunden-Backoff (5 * 3^versuche: 5, 15, 45 s). Beim
// max_versuche-ten Fehlversuch wechselt der Auftrag auf fehlgeschlagen und
// wird nicht mehr automatisch versucht — die Kurve endet bewusst unter der
// Rueckstands-Schwelle, TSE-weite Fehler zaehlen nie auf den Auftrag.
func (q *Queries) TSESignaturauftragFehlversuch(ctx context.Context, arg TSESignaturauftragFehlversuchParams) error {
	_, err := q.db.ExecContext(ctx, tSESignaturauftragFehlversuch, arg.LetzterFehler, arg.MaxVersuche, arg.ID)
	return err
}

const tSESignaturauftragVerwerfen = `-- name: TSESignaturauftragVerwerfen :exec
UPDATE tse_signaturauftraege
SET status = 'verworfen'
WHERE id = $1 AND status = 'fehlgeschlagen'
`

func (q *Queries) TSESignaturauftragVerwerfen(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, tSESignaturauftragVerwerfen, id)
	return err
}

const tSESignaturauftragZuruecksetzen = `-- name: TSESignaturauftragZuruecksetzen :exec
UPDATE tse_signaturauftraege
SET status = 'offen', versuche = 0, letzter_fehler = NULL, naechster_versuch_am = NOW()
WHERE id = $1 AND status = 'fehlgeschlagen'
`

func (q *Queries) TSESignaturauftragZuruecksetzen(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, tSESignaturauftragZuruecksetzen, id)
	return err
}
