// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tse_signaturauftraege.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const getAeltesterOffenerTSESignaturauftrag = `-- name: GetAeltesterOffenerTSESignaturauftrag :one
SELECT erstellt_am
FROM tse_signaturauftraege
WHERE status = 'offen'
ORDER BY erstellt_am ASC
LIMIT 1
`

// GetAeltesterOffenerTSESignaturauftrag liefert den Erstellungszeitpunkt des
// aeltesten offenen Auftrags — der Rueckstands-Watchdog bemisst daran den
// Signatur-Rueckstand.
func (q *Queries) GetAeltesterOffenerTSESignaturauftrag(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getAeltesterOffenerTSESignaturauftrag)
	var erstellt_am time.Time
	err := row.Scan(&erstellt_am)
	return erstellt_am, err
}

const getOffeneSignaturauftragStaendeFuerKassensitzung = `-- name: GetOffeneSignaturauftragStaendeFuerKassensitzung :many
SELECT a.status, a.erstellt_am
FROM tse_signaturauftraege a
JOIN kassenjournal k ON k.id = a.event_id
WHERE k.kassensitzung_nr = $1 AND a.status <> 'erledigt'
ORDER BY a.erstellt_am ASC
`

type GetOffeneSignaturauftragStaendeFuerKassensitzungRow struct {
	Status     string
	ErstelltAm time.Time
}

// GetOffeneSignaturauftragStaendeFuerKassensitzung liefert die Signatur-Staende
// aller noch nicht erledigten Signaturauftraege einer Kassensitzung — die
// Grundlage des Kassenabschluss-Gates. Erledigte Auftraege sind irrelevant
// (bereits signiert); die vier nicht-erledigten Status ordnet
// BestimmeSignaturstatus in ausstehend (blockiert) bzw. Ausfall (Rest) ein.
func (q *Queries) GetOffeneSignaturauftragStaendeFuerKassensitzung(ctx context.Context, kassensitzungNr int) ([]GetOffeneSignaturauftragStaendeFuerKassensitzungRow, error) {
	rows, err := q.db.QueryContext(ctx, getOffeneSignaturauftragStaendeFuerKassensitzung, kassensitzungNr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOffeneSignaturauftragStaendeFuerKassensitzungRow{}
	for rows.Next() {
		var i GetOffeneSignaturauftragStaendeFuerKassensitzungRow
		if err := rows.Scan(&i.Status, &i.ErstelltAm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOffeneTSESignaturauftraege = `-- name: GetOffeneTSESignaturauftraege :many
SELECT id, tx_id, process_type, process_data
FROM tse_signaturauftraege
WHERE status = 'offen'
  AND naechster_versuch_am <= NOW()
ORDER BY id ASC
LIMIT $1
`

type GetOffeneTSESignaturauftraegeRow struct {
	ID          int
	TxID        string
	ProcessType string
	ProcessData string
}

// GetOffeneTSESignaturauftraege liefert die faelligen offenen Auftraege in
// Einreihungs-Reihenfolge (FIFO als Soll-Eigenschaft).
func (q *Queries) GetOffeneTSESignaturauftraege(ctx context.Context, limit int32) ([]GetOffeneTSESignaturauftraegeRow, error) {
	rows, err := q.db.QueryContext(ctx, getOffeneTSESignaturauftraege, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOffeneTSESignaturauftraegeRow{}
	for rows.Next() {
		var i GetOffeneTSESignaturauftraegeRow
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.ProcessType,
			&i.ProcessData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTSESignaturQueueZustand = `-- name: GetTSESignaturQueueZustand :one
WITH aktive_fehlgeschlagene AS (
    SELECT a.id, a.letzter_fehler
    FROM tse_signaturauftraege a
    JOIN kassenjournal k ON k.id = a.event_id
    JOIN kassensitzungen s ON s.z_nr = k.kassensitzung_nr
    WHERE a.status = 'fehlgeschlagen'
      AND s.status IN ('offen', 'wird_abgeschlossen')
)
SELECT
    COUNT(*) FILTER (WHERE status = 'offen')::int AS offene_auftraege,
    (SELECT COUNT(*) FROM aktive_fehlgeschlagene)::int AS fehlgeschlagene_auftraege,
    COALESCE((SELECT letzter_fehler FROM aktive_fehlgeschlagene ORDER BY id DESC LIMIT 1), '')::text AS letzter_fehler,
    COALESCE(EXTRACT(EPOCH FROM (NOW() - MIN(erstellt_am) FILTER (WHERE status = 'offen'))), 0)::int AS rueckstand_sekunden,
    (COUNT(*) FILTER (WHERE status = 'erledigt' AND erledigt_am >= NOW() - interval '15 minutes')::float8 / 15.0)::float8 AS signaturen_pro_minute,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (log_time_end - erstellt_am))) FILTER (WHERE status = 'erledigt' AND erledigt_am >= NOW() - interval '15 minutes'), 0)::float8 AS signierdauer_p95_sekunden
FROM tse_signaturauftraege
`

type GetTSESignaturQueueZustandRow struct {
	OffeneAuftraege          int
	FehlgeschlageneAuftraege int
	LetzterFehler            string
	RueckstandSekunden       int
	SignaturenProMinute      float64
	SignierdauerP95Sekunden  float64
}

// GetTSESignaturQueueZustand berechnet den Zustand der Signatur-Queue in einem
// Durchlauf: offene Auftraege, das Alter des aeltesten offenen Auftrags
// (Rueckstand) sowie Durchsatz (Signaturen pro Minute) und Latenz (Signierdauer
// p95, erstellt_am -> TSE-logTime) ueber ein gleitendes 15-Minuten-Fenster —
// diese Kennzahlen global. Die fehlgeschlagenen Auftraege dagegen zaehlen nur
// die der aktiven Kassensitzung (Status offen oder wird_abgeschlossen), und
// letzter_fehler traegt den Fehlertext des juengsten davon. Ohne aktive Sitzung
// ist beides leer — der Kassenabschluss weist die Ausfall-Reste aus und
// quittiert damit die Warnung. On demand aus den Auftrags- und Signaturzeiten,
// kein Metrik-Subsystem und kein In-Memory-Zustand.
func (q *Queries) GetTSESignaturQueueZustand(ctx context.Context) (GetTSESignaturQueueZustandRow, error) {
	row := q.db.QueryRowContext(ctx, getTSESignaturQueueZustand)
	var i GetTSESignaturQueueZustandRow
	err := row.Scan(
		&i.OffeneAuftraege,
		&i.FehlgeschlageneAuftraege,
		&i.LetzterFehler,
		&i.RueckstandSekunden,
		&i.SignaturenProMinute,
		&i.SignierdauerP95Sekunden,
	)
	return i, err
}

const getTSESignaturauftragZuEvent = `-- name: GetTSESignaturauftragZuEvent :one
SELECT status, erstellt_am, transaktion_nummer, signatur_zaehler, tse_seriennummer, log_time_start, log_time_end, signatur, qr_code_data
FROM tse_signaturauftraege
WHERE event_id = $1
`

type GetTSESignaturauftragZuEventRow struct {
	Status            string
	ErstelltAm        time.Time
	TransaktionNummer sql.NullInt32
	SignaturZaehler   sql.NullInt32
	TseSeriennummer   sql.NullString
	LogTimeStart      sql.NullTime
	LogTimeEnd        sql.NullTime
	Signatur          sql.NullString
	QrCodeData        sql.NullString
}

// GetTSESignaturauftragZuEvent liefert den Signatur-Stand eines Events fuer den
// Beleg-Abruf: Status plus Signaturspalten (gefuellt sobald quittiert).
// Kein Treffer heisst: Das Event ist nicht signaturpflichtig.
func (q *Queries) GetTSESignaturauftragZuEvent(ctx context.Context, eventID int) (GetTSESignaturauftragZuEventRow, error) {
	row := q.db.QueryRowContext(ctx, getTSESignaturauftragZuEvent, eventID)
	var i GetTSESignaturauftragZuEventRow
	err := row.Scan(
		&i.Status,
		&i.ErstelltAm,
		&i.TransaktionNummer,
		&i.SignaturZaehler,
		&i.TseSeriennummer,
		&i.LogTimeStart,
		&i.LogTimeEnd,
		&i.Signatur,
		&i.QrCodeData,
	)
	return i, err
}

const insertTSESignaturauftrag = `-- name: InsertTSESignaturauftrag :exec
INSERT INTO tse_signaturauftraege (event_id, tx_id, process_type, process_data, status, naechster_versuch_am, erstellt_am)
VALUES ($1, $2, $3, $4, 'offen', NOW(), NOW())
`

type InsertTSESignaturauftragParams struct {
	EventID     int
	TxID        string
	ProcessType string
	ProcessData string
}

// InsertTSESignaturauftrag reiht den Signaturauftrag eines Events ein — im
// selben Commit wie das Event (transaktionale Outbox). event_id UNIQUE sichert
// genau einen Auftrag je Event.
func (q *Queries) InsertTSESignaturauftrag(ctx context.Context, arg InsertTSESignaturauftragParams) error {
	_, err := q.db.ExecContext(ctx, insertTSESignaturauftrag,
		arg.EventID,
		arg.TxID,
		arg.ProcessType,
		arg.ProcessData,
	)
	return err
}

const markiereOffeneTSESignaturauftraegeNichtKonfiguriert = `-- name: MarkiereOffeneTSESignaturauftraegeNichtKonfiguriert :execrows
UPDATE tse_signaturauftraege
SET status = 'tse_nicht_konfiguriert'
WHERE status = 'offen'
`

// MarkiereOffeneTSESignaturauftraegeNichtKonfiguriert markiert alle offenen
// Auftraege endgueltig als tse_nicht_konfiguriert: ohne vorhandene
// TSE-Konfiguration gibt es keine Signatur, ein Nachsignieren ist ausgeschlossen
// (keine Fehlversuche, keine automatische Wiederaufnahme). Der Status-Guard
// laesst bereits endgueltig markierte Auftraege unberuehrt. Zwei Schreiber: der
// Signatur-Worker (Dauerzustand ohne Konfiguration) und der Einrichtungs-Sweep
// (Uebergang zu konfiguriert, in derselben Transaktion wie das Speichern).
func (q *Queries) MarkiereOffeneTSESignaturauftraegeNichtKonfiguriert(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, markiereOffeneTSESignaturauftraegeNichtKonfiguriert)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const quittiereTSESignaturauftrag = `-- name: QuittiereTSESignaturauftrag :exec
UPDATE tse_signaturauftraege
SET status = 'erledigt',
    erledigt_am = NOW(),
    transaktion_nummer = $1,
    signatur_zaehler = $2,
    tse_seriennummer = $3,
    log_time_start = $4,
    log_time_end = $5,
    signatur = $6,
    qr_code_data = $7
WHERE id = $8 AND status = 'offen'
`

type QuittiereTSESignaturauftragParams struct {
	TransaktionNummer sql.NullInt32
	SignaturZaehler   sql.NullInt32
	TseSeriennummer   sql.NullString
	LogTimeStart      sql.NullTime
	LogTimeEnd        sql.NullTime
	Signatur          sql.NullString
	QrCodeData        sql.NullString
	ID                int
}

// QuittiereTSESignaturauftrag schreibt die Signatur als einzelnes Update an den
// Auftrag: Signaturspalten fuellen, Status erledigt. Der Status-Guard macht die
// Quittierung idempotent (Signaturspalten werden genau einmal beschrieben).
func (q *Queries) QuittiereTSESignaturauftrag(ctx context.Context, arg QuittiereTSESignaturauftragParams) error {
	_, err := q.db.ExecContext(ctx, quittiereTSESignaturauftrag,
		arg.TransaktionNummer,
		arg.SignaturZaehler,
		arg.TseSeriennummer,
		arg.LogTimeStart,
		arg.LogTimeEnd,
		arg.Signatur,
		arg.QrCodeData,
		arg.ID,
	)
	return err
}

const tSESignaturauftragFehlversuch = `-- name: TSESignaturauftragFehlversuch :exec
UPDATE tse_signaturauftraege
SET versuche = versuche + 1,
    letzter_fehler = $1,
    naechster_versuch_am = NOW() + (5 * POWER(3, versuche)) * interval '1 second',
    status = CASE WHEN versuche + 1 >= $2 THEN 'fehlgeschlagen' ELSE status END
WHERE id = $3 AND status = 'offen'
`

type TSESignaturauftragFehlversuchParams struct {
	LetzterFehler sql.NullString
	MaxVersuche   int
	ID            int
}

// TSESignaturauftragFehlversuch verbucht einen auftragsspezifischen
// Fehlversuch mit Sekunden-Backoff (5 * 3^versuche: 5, 15, 45 s). Beim
// max_versuche-ten Fehlversuch wechselt der Auftrag auf fehlgeschlagen und
// wird nicht mehr automatisch versucht — die Kurve endet bewusst unter der
// Rueckstands-Schwelle, TSE-weite Fehler zaehlen nie auf den Auftrag.
func (q *Queries) TSESignaturauftragFehlversuch(ctx context.Context, arg TSESignaturauftragFehlversuchParams) error {
	_, err := q.db.ExecContext(ctx, tSESignaturauftragFehlversuch, arg.LetzterFehler, arg.MaxVersuche, arg.ID)
	return err
}
