// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tse_stoerungen.sql

package dbgen

import (
	"context"
	"time"
)

const closeTSEStoerung = `-- name: CloseTSEStoerung :exec
UPDATE tse_stoerungen
SET ende = NOW()
WHERE ende IS NULL AND grund_art = $1
`

// CloseTSEStoerung beendet den aktiven Stoerungszeitraum, falls er die
// Grund-Art des Schreibers traegt (jeder Schreiber schliesst nur Zeitraeume
// seiner Grund-Art); sonst ein No-Op.
func (q *Queries) CloseTSEStoerung(ctx context.Context, grundArt string) error {
	_, err := q.db.ExecContext(ctx, closeTSEStoerung, grundArt)
	return err
}

const getAktiveTSEStoerung = `-- name: GetAktiveTSEStoerung :one
SELECT beginn, grund_art, fehlertext
FROM tse_stoerungen
WHERE ende IS NULL
`

type GetAktiveTSEStoerungRow struct {
	Beginn     time.Time
	GrundArt   string
	Fehlertext string
}

// GetAktiveTSEStoerung liefert den aktiven Stoerungszeitraum (hoechstens
// einer, per partiellem Unique-Index).
func (q *Queries) GetAktiveTSEStoerung(ctx context.Context) (GetAktiveTSEStoerungRow, error) {
	row := q.db.QueryRowContext(ctx, getAktiveTSEStoerung)
	var i GetAktiveTSEStoerungRow
	err := row.Scan(&i.Beginn, &i.GrundArt, &i.Fehlertext)
	return i, err
}

const getAlleTSEStoerungen = `-- name: GetAlleTSEStoerungen :many
SELECT id, beginn, ende, grund_art, fehlertext
FROM tse_stoerungen
ORDER BY beginn DESC
LIMIT 200
`

// GetAlleTSEStoerungen liefert das Stoerungsprotokoll (Ausfalldokumentation):
// alle Stoerungszeitraeume mit Beginn, Ende und Grund, neueste zuerst.
func (q *Queries) GetAlleTSEStoerungen(ctx context.Context) ([]TseStoerungen, error) {
	rows, err := q.db.QueryContext(ctx, getAlleTSEStoerungen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TseStoerungen{}
	for rows.Next() {
		var i TseStoerungen
		if err := rows.Scan(
			&i.ID,
			&i.Beginn,
			&i.Ende,
			&i.GrundArt,
			&i.Fehlertext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openTSEStoerung = `-- name: OpenTSEStoerung :exec
INSERT INTO tse_stoerungen (beginn, grund_art, fehlertext)
VALUES (NOW(), $1, $2)
ON CONFLICT DO NOTHING
`

type OpenTSEStoerungParams struct {
	GrundArt   string
	Fehlertext string
}

// OpenTSEStoerung oeffnet einen Stoerungszeitraum im Stoerungsprotokoll.
// Der partielle Unique-Index (hoechstens eine Zeile mit ende IS NULL) macht
// das Oeffnen idempotent: Bei aktivem Zeitraum ist es ein No-Op.
func (q *Queries) OpenTSEStoerung(ctx context.Context, arg OpenTSEStoerungParams) error {
	_, err := q.db.ExecContext(ctx, openTSEStoerung, arg.GrundArt, arg.Fehlertext)
	return err
}
