// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, username, role, status, password_hash, onetime_password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id
`

type CreateUserParams struct {
	Name                string
	Username            string
	Role                Userrole
	Status              Entitystatus
	PasswordHash        sql.NullString
	OnetimePasswordHash sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Role,
		arg.Status,
		arg.PasswordHash,
		arg.OnetimePasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, username, role, status, created_at, updated_at
FROM users WHERE status != 'deleted' ORDER BY id ASC
`

type GetAllUsersRow struct {
	ID        int
	Name      string
	Username  string
	Role      Userrole
	Status    Entitystatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUsersRow{}
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, username, role, status, password_hash, onetime_password_hash, created_at, updated_at
FROM users WHERE id = $1 AND status != 'deleted'
`

type GetUserRow struct {
	ID                  int
	Name                string
	Username            string
	Role                Userrole
	Status              Entitystatus
	PasswordHash        sql.NullString
	OnetimePasswordHash sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetUser(ctx context.Context, id int) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.PasswordHash,
		&i.OnetimePasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, username, role, status, password_hash, onetime_password_hash, created_at, updated_at
FROM users WHERE username = $1 AND status != 'deleted'
`

type GetUserByUsernameRow struct {
	ID                  int
	Name                string
	Username            string
	Role                Userrole
	Status              Entitystatus
	PasswordHash        sql.NullString
	OnetimePasswordHash sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.PasswordHash,
		&i.OnetimePasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users SET name = $1, username = $2, role = $3, status = $4, password_hash = $5, onetime_password_hash = $6, updated_at = $7
WHERE id = $8
`

type UpdateUserParams struct {
	Name                string
	Username            string
	Role                Userrole
	Status              Entitystatus
	PasswordHash        sql.NullString
	OnetimePasswordHash sql.NullString
	UpdatedAt           time.Time
	ID                  int
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Username,
		arg.Role,
		arg.Status,
		arg.PasswordHash,
		arg.OnetimePasswordHash,
		arg.UpdatedAt,
		arg.ID,
	)
}
