// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vorgang_idempotenz.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getVorgangPayloadHash = `-- name: GetVorgangPayloadHash :one
SELECT payload_hash FROM vorgang_idempotenz WHERE vorgang_id = $1
`

// Liefert den gespeicherten Nutzdaten-Hash zum Schlüssel; sql.ErrNoRows bedeutet
// „Schlüssel unbekannt" und damit einen neuen Vorgang. Der Vergleich mit dem Hash
// der eingereichten Nutzdaten trennt die Duplikat-Einreichung (stille
// Erfolgsantwort) von abweichenden Nutzdaten (HTTP 409).
func (q *Queries) GetVorgangPayloadHash(ctx context.Context, vorgangID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getVorgangPayloadHash, vorgangID)
	var payload_hash []byte
	err := row.Scan(&payload_hash)
	return payload_hash, err
}

const insertVorgangIdempotenz = `-- name: InsertVorgangIdempotenz :exec
INSERT INTO vorgang_idempotenz (vorgang_id, art, user_id, payload_hash, created_at)
VALUES ($1, $2, $3, $4, now())
`

type InsertVorgangIdempotenzParams struct {
	VorgangID   uuid.UUID
	Art         string
	UserID      int
	PayloadHash []byte
}

// Hält Schlüssel und Nutzdaten-Hash eines buchenden Vorgangs fest — im selben
// Commit wie dessen Events und VOR den Event-Inserts, damit ein
// Primärschlüssel-Konflikt eindeutig eine Zweiteinreichung desselben Schlüssels
// ist (Duplikat oder abweichende Nutzdaten, entschieden über payload_hash).
func (q *Queries) InsertVorgangIdempotenz(ctx context.Context, arg InsertVorgangIdempotenzParams) error {
	_, err := q.db.ExecContext(ctx, insertVorgangIdempotenz,
		arg.VorgangID,
		arg.Art,
		arg.UserID,
		arg.PayloadHash,
	)
	return err
}
