// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vorgang_idempotenz.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const existsVorgangIdempotenz = `-- name: ExistsVorgangIdempotenz :one
SELECT EXISTS(SELECT 1 FROM vorgang_idempotenz WHERE vorgang_id = $1)
`

// Duplikat-Vorprüfung der Commands VOR der fachlichen Validierung: Ein
// Wiederholversuch nach erfolgreicher Buchung darf nicht an inzwischen
// geänderten Invarianten scheitern, sondern wiederholt die Erfolgsantwort.
func (q *Queries) ExistsVorgangIdempotenz(ctx context.Context, vorgangID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsVorgangIdempotenz, vorgangID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertVorgangIdempotenz = `-- name: InsertVorgangIdempotenz :exec
INSERT INTO vorgang_idempotenz (vorgang_id, art, user_id, created_at)
VALUES ($1, $2, $3, now())
`

type InsertVorgangIdempotenzParams struct {
	VorgangID uuid.UUID
	Art       string
	UserID    int
}

// Hält den client-gelieferten Idempotenz-Schlüssel eines buchenden Vorgangs
// fest — im selben Commit wie dessen Events und VOR den Event-Inserts, damit
// ein Primärschlüssel-Konflikt eindeutig eine Duplikat-Einreichung ist.
func (q *Queries) InsertVorgangIdempotenz(ctx context.Context, arg InsertVorgangIdempotenzParams) error {
	_, err := q.db.ExecContext(ctx, insertVorgangIdempotenz, arg.VorgangID, arg.Art, arg.UserID)
	return err
}
