//go:build unit

package table

import (
	"testing"

	e "github.com/nicograef/jotti/backend/domain/event"
)

func mustCreateOrderEvent(t *testing.T, userID, tableID int, products []Position) e.Event {
	t.Helper()
	event, err := NewBestellungAufgegebenEvent(userID, "TestUser", tableID, products, "")
	if err != nil {
		t.Fatalf("failed to create order event: %v", err)
	}
	return event
}

func mustCreatePaymentEvent(t *testing.T, userID, tableID int, refs []PositionRef, gesamtZahlungCents int) e.Event {
	t.Helper()
	event, err := NewZahlungRegistriertEvent(userID, "TestUser", tableID, refs, gesamtZahlungCents, "")
	if err != nil {
		t.Fatalf("failed to create payment event: %v", err)
	}
	return event
}

func mustCreateCancelationEvent(t *testing.T, userID, tableID int, refs []PositionRef, gesamtStornierungCents int) e.Event {
	t.Helper()
	event, err := NewProdukteStorniertEvent(userID, "TestUser", tableID, refs, gesamtStornierungCents, "")
	if err != nil {
		t.Fatalf("failed to create cancelation event: %v", err)
	}
	return event
}

func mustCreateDeliveryEvent(t *testing.T, userID, tableID int, refs []PositionRef) e.Event {
	t.Helper()
	event, err := NewProdukteGeliefertEvent(userID, "TestUser", tableID, refs, "")
	if err != nil {
		t.Fatalf("failed to create delivery event: %v", err)
	}
	return event
}

func mustCreateSnapshotEvent(t *testing.T, userID, tableID int, balance int, unpaid, undelivered []Position, totalPayments int) e.Event {
	t.Helper()
	event, err := NewSnapshotEvent(userID, "TestUser", tableID, balance, unpaid, undelivered, totalPayments)
	if err != nil {
		t.Fatalf("failed to create snapshot event: %v", err)
	}
	return event
}

// helper to create a test Position with fat event fields
func testPosition(varianteID int, produktName, varianteName, kategorie string, einzelpreis, menge int) Position {
	return Position{
		// PositionID will be generated by NewBestellungAufgegebenEvent
		VarianteID:   varianteID,
		ProduktName:  produktName,
		VarianteName: varianteName,
		Kategorie:    kategorie,
		Einzelpreis:  einzelpreis,
		Menge:        menge,
	}
}

// positionRefsFromOrder extracts PositionRefs from an order event's positions
func positionRefsFromOrder(t *testing.T, orderEvent e.Event, menge int) []PositionRef {
	t.Helper()
	bestellung, err := buildBestellungFromEvent(orderEvent)
	if err != nil {
		t.Fatalf("failed to build bestellung from event: %v", err)
	}
	refs := make([]PositionRef, len(bestellung.Positionen))
	for i, pos := range bestellung.Positionen {
		refs[i] = PositionRef{PositionID: pos.PositionID, Menge: menge}
	}
	return refs
}

func TestGetSaldoFromEvents_Empty(t *testing.T) {
	balance, err := GetSaldoFromEvents([]e.Event{})
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if balance != 0 {
		t.Fatalf("expected balance 0, got %d", balance)
	}
}

func TestGetSaldoFromEvents_OrderOnly(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	events := []e.Event{
		mustCreateOrderEvent(t, 1, 1, products),
	}

	balance, err := GetSaldoFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if balance != 1000 {
		t.Fatalf("expected balance 1000, got %d", balance)
	}
}

func TestGetSaldoFromEvents_OrderAndPayment(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, products)
	paymentRefs := positionRefsFromOrder(t, orderEvent, 1)

	events := []e.Event{
		orderEvent,
		mustCreatePaymentEvent(t, 1, 1, paymentRefs, 500),
	}

	balance, err := GetSaldoFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if balance != 500 {
		t.Fatalf("expected balance 500, got %d", balance)
	}
}

func TestGetSaldoFromEvents_OrderPaymentAndCancelation(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, products)
	refs := positionRefsFromOrder(t, orderEvent, 1)

	events := []e.Event{
		orderEvent,
		mustCreatePaymentEvent(t, 1, 1, refs, 500),
		mustCreateCancelationEvent(t, 1, 1, refs, 500),
	}

	balance, err := GetSaldoFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if balance != 0 {
		t.Fatalf("expected balance 0, got %d", balance)
	}
}

func TestGetHistoryFromEvents_Empty(t *testing.T) {
	history, err := GetHistoryFromEvents([]e.Event{})
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(history) != 0 {
		t.Fatalf("expected empty history, got %d items", len(history))
	}
}

func TestGetHistoryFromEvents_ReturnsAllEventTypes(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 1),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, products)
	refs := positionRefsFromOrder(t, orderEvent, 1)

	events := []e.Event{
		orderEvent,
		mustCreatePaymentEvent(t, 1, 1, refs, 500),
		mustCreateCancelationEvent(t, 1, 1, refs, 500),
		mustCreateDeliveryEvent(t, 1, 1, refs),
	}

	history, err := GetHistoryFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(history) != 4 {
		t.Fatalf("expected 4 history items, got %d", len(history))
	}
}

func TestGetHistoryFromEvents_ReversesOrder(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 1),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, products)
	refs := positionRefsFromOrder(t, orderEvent, 1)

	events := []e.Event{
		orderEvent,
		mustCreatePaymentEvent(t, 1, 1, refs, 500),
	}

	history, err := GetHistoryFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	// First item should be payment (last event), second should be order (first event)
	if _, ok := history[0].(Zahlung); !ok {
		t.Fatalf("expected first item to be Zahlung, got %T", history[0])
	}
	if _, ok := history[1].(Bestellung); !ok {
		t.Fatalf("expected second item to be Bestellung, got %T", history[1])
	}
}

func TestGetUnbezahltePositionenFromEvents_Empty(t *testing.T) {
	products, err := GetUnbezahltePositionenFromEvents([]e.Event{})
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 0 {
		t.Fatalf("expected empty products, got %d", len(products))
	}
}

func TestGetUnbezahltePositionenFromEvents_OrderOnly(t *testing.T) {
	orderProducts := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
		testPosition(2, "Fries", "Pommes", "essen", 300, 1),
	}
	events := []e.Event{
		mustCreateOrderEvent(t, 1, 1, orderProducts),
	}

	products, err := GetUnbezahltePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 2 {
		t.Fatalf("expected 2 products, got %d", len(products))
	}
	if products[0].Menge != 2 {
		t.Fatalf("expected menge 2, got %d", products[0].Menge)
	}
}

func TestGetUnbezahltePositionenFromEvents_PartialPayment(t *testing.T) {
	orderProducts := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 3),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, orderProducts)
	paymentRefs := positionRefsFromOrder(t, orderEvent, 1)

	events := []e.Event{
		orderEvent,
		mustCreatePaymentEvent(t, 1, 1, paymentRefs, 500),
	}

	products, err := GetUnbezahltePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 1 {
		t.Fatalf("expected 1 product, got %d", len(products))
	}
	if products[0].Menge != 2 {
		t.Fatalf("expected menge 2, got %d", products[0].Menge)
	}
}

func TestGetUnbezahltePositionenFromEvents_FullPayment(t *testing.T) {
	orderProducts := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, orderProducts)
	paymentRefs := positionRefsFromOrder(t, orderEvent, 2)

	events := []e.Event{
		orderEvent,
		mustCreatePaymentEvent(t, 1, 1, paymentRefs, 1000),
	}

	products, err := GetUnbezahltePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 0 {
		t.Fatalf("expected 0 products, got %d", len(products))
	}
}

func TestGetUnbezahltePositionenFromEvents_WithCancelation(t *testing.T) {
	orderProducts := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 3),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, orderProducts)
	cancelRefs := positionRefsFromOrder(t, orderEvent, 2)

	events := []e.Event{
		orderEvent,
		mustCreateCancelationEvent(t, 1, 1, cancelRefs, 1000),
	}

	products, err := GetUnbezahltePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 1 {
		t.Fatalf("expected 1 product, got %d", len(products))
	}
	if products[0].Menge != 1 {
		t.Fatalf("expected menge 1, got %d", products[0].Menge)
	}
}

func TestGetUnbezahltePositionenFromEvents_AccumulatesMultipleOrders(t *testing.T) {
	products1 := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	products2 := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 3),
	}
	order1 := mustCreateOrderEvent(t, 1, 1, products1)
	order2 := mustCreateOrderEvent(t, 1, 1, products2)
	events := []e.Event{order1, order2}

	products, err := GetUnbezahltePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	// Two different PositionIDs (UUIDs), so they are NOT merged
	if len(products) != 2 {
		t.Fatalf("expected 2 products (different UUIDs), got %d", len(products))
	}
}

func TestGetUngeliefertePositionenFromEvents_Empty(t *testing.T) {
	products, err := GetUngeliefertePositionenFromEvents([]e.Event{})
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 0 {
		t.Fatalf("expected empty products, got %d", len(products))
	}
}

func TestGetUngeliefertePositionenFromEvents_OrderOnly(t *testing.T) {
	orderProducts := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	events := []e.Event{
		mustCreateOrderEvent(t, 1, 1, orderProducts),
	}

	products, err := GetUngeliefertePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 1 {
		t.Fatalf("expected 1 product, got %d", len(products))
	}
	if products[0].Menge != 2 {
		t.Fatalf("expected menge 2, got %d", products[0].Menge)
	}
}

func TestGetUngeliefertePositionenFromEvents_PartialDelivery(t *testing.T) {
	orderProducts := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 3),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, orderProducts)
	deliveryRefs := positionRefsFromOrder(t, orderEvent, 1)

	events := []e.Event{
		orderEvent,
		mustCreateDeliveryEvent(t, 1, 1, deliveryRefs),
	}

	products, err := GetUngeliefertePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 1 {
		t.Fatalf("expected 1 product, got %d", len(products))
	}
	if products[0].Menge != 2 {
		t.Fatalf("expected menge 2, got %d", products[0].Menge)
	}
}

func TestGetUngeliefertePositionenFromEvents_FullDelivery(t *testing.T) {
	orderProducts := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, orderProducts)
	deliveryRefs := positionRefsFromOrder(t, orderEvent, 2)

	events := []e.Event{
		orderEvent,
		mustCreateDeliveryEvent(t, 1, 1, deliveryRefs),
	}

	products, err := GetUngeliefertePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 0 {
		t.Fatalf("expected 0 products, got %d", len(products))
	}
}

func TestGetUngeliefertePositionenFromEvents_WithCancelation(t *testing.T) {
	orderProducts := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 3),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, orderProducts)
	cancelRefs := positionRefsFromOrder(t, orderEvent, 2)

	events := []e.Event{
		orderEvent,
		mustCreateCancelationEvent(t, 1, 1, cancelRefs, 1000),
	}

	products, err := GetUngeliefertePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 1 {
		t.Fatalf("expected 1 product, got %d", len(products))
	}
	if products[0].Menge != 1 {
		t.Fatalf("expected menge 1, got %d", products[0].Menge)
	}
}

func TestGetSaldoFromEvents_WithSnapshot(t *testing.T) {
	// Snapshot represents state: balance = 500 cents
	// Then new order adds 300 cents
	unpaid := []Position{{PositionID: "00000000-0000-0000-0000-000000000001", VarianteID: 1, ProduktName: "Beer", VarianteName: "Pils", Kategorie: "getraenk", Einzelpreis: 500, Menge: 1}}
	undelivered := []Position{{PositionID: "00000000-0000-0000-0000-000000000001", VarianteID: 1, ProduktName: "Beer", VarianteName: "Pils", Kategorie: "getraenk", Einzelpreis: 500, Menge: 1}}
	newLineItems := []Position{testPosition(2, "Fries", "Pommes", "essen", 300, 1)}

	events := []e.Event{
		mustCreateSnapshotEvent(t, 1, 1, 500, unpaid, undelivered, 0),
		mustCreateOrderEvent(t, 1, 1, newLineItems),
	}

	balance, err := GetSaldoFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if balance != 800 {
		t.Fatalf("expected balance 800 (500 from snapshot + 300 from order), got %d", balance)
	}
}

func TestGetSaldoFromEvents_SnapshotResetsBalance(t *testing.T) {
	oldProducts := []Position{testPosition(1, "Beer", "Pils", "getraenk", 1000, 1)}
	unpaid := []Position{}
	undelivered := []Position{}

	events := []e.Event{
		mustCreateOrderEvent(t, 1, 1, oldProducts),
		mustCreateSnapshotEvent(t, 1, 1, 0, unpaid, undelivered, 1000),
	}

	balance, err := GetSaldoFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if balance != 0 {
		t.Fatalf("expected balance 0 (from snapshot), got %d", balance)
	}
}

func TestGetUnbezahltePositionenFromEvents_WithSnapshot(t *testing.T) {
	snapshotUnpaid := []Position{{PositionID: "00000000-0000-0000-0000-000000000002", VarianteID: 1, ProduktName: "Beer", VarianteName: "Pils", Kategorie: "getraenk", Einzelpreis: 500, Menge: 2}}
	newLineItems := []Position{testPosition(2, "Fries", "Pommes", "essen", 300, 1)}

	events := []e.Event{
		mustCreateSnapshotEvent(t, 1, 1, 1000, snapshotUnpaid, []Position{}, 0),
		mustCreateOrderEvent(t, 1, 1, newLineItems),
	}

	products, err := GetUnbezahltePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 2 {
		t.Fatalf("expected 2 products, got %d", len(products))
	}
}

func TestGetUnbezahltePositionenFromEvents_SnapshotResetsState(t *testing.T) {
	oldProducts := []Position{testPosition(1, "Beer", "Pils", "getraenk", 500, 10)}
	snapshotUnpaid := []Position{{PositionID: "00000000-0000-0000-0000-000000000003", VarianteID: 2, ProduktName: "Fries", VarianteName: "Pommes", Kategorie: "essen", Einzelpreis: 300, Menge: 1}}

	events := []e.Event{
		mustCreateOrderEvent(t, 1, 1, oldProducts),
		mustCreateSnapshotEvent(t, 1, 1, 300, snapshotUnpaid, []Position{}, 5000),
	}

	products, err := GetUnbezahltePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 1 {
		t.Fatalf("expected 1 product from snapshot, got %d", len(products))
	}
	if products[0].VarianteID != 2 {
		t.Fatalf("expected variante ID 2 (fries), got %d", products[0].VarianteID)
	}
}

func TestGetUngeliefertePositionenFromEvents_WithSnapshot(t *testing.T) {
	snapshotUndelivered := []Position{{PositionID: "00000000-0000-0000-0000-000000000004", VarianteID: 1, ProduktName: "Beer", VarianteName: "Pils", Kategorie: "getraenk", Einzelpreis: 500, Menge: 3}}
	newLineItems := []Position{testPosition(2, "Fries", "Pommes", "essen", 300, 2)}

	events := []e.Event{
		mustCreateSnapshotEvent(t, 1, 1, 1500, []Position{}, snapshotUndelivered, 0),
		mustCreateOrderEvent(t, 1, 1, newLineItems),
	}

	products, err := GetUngeliefertePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 2 {
		t.Fatalf("expected 2 products, got %d", len(products))
	}
}

func TestGetUngeliefertePositionenFromEvents_SnapshotResetsState(t *testing.T) {
	oldProducts := []Position{testPosition(1, "Beer", "Pils", "getraenk", 500, 10)}
	snapshotUndelivered := []Position{{PositionID: "00000000-0000-0000-0000-000000000005", VarianteID: 2, ProduktName: "Fries", VarianteName: "Pommes", Kategorie: "essen", Einzelpreis: 300, Menge: 2}}

	events := []e.Event{
		mustCreateOrderEvent(t, 1, 1, oldProducts),
		mustCreateSnapshotEvent(t, 1, 1, 0, []Position{}, snapshotUndelivered, 5000),
	}

	products, err := GetUngeliefertePositionenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(products) != 1 {
		t.Fatalf("expected 1 product from snapshot, got %d", len(products))
	}
	if products[0].VarianteID != 2 {
		t.Fatalf("expected variante ID 2 (fries), got %d", products[0].VarianteID)
	}
}

func TestGetGesamtZahlungenFromEvents_WithSnapshot(t *testing.T) {
	products := []Position{testPosition(1, "Beer", "Pils", "getraenk", 500, 1)}
	orderEvent := mustCreateOrderEvent(t, 1, 1, products)
	refs := positionRefsFromOrder(t, orderEvent, 1)

	events := []e.Event{
		mustCreateSnapshotEvent(t, 1, 1, 500, []Position{}, []Position{}, 1000),
		mustCreatePaymentEvent(t, 1, 1, refs, 500),
	}

	totalPayments, err := GetGesamtZahlungenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if totalPayments != 1500 {
		t.Fatalf("expected totalPayments 1500 (1000 from snapshot + 500 from payment), got %d", totalPayments)
	}
}

func TestGetGesamtZahlungenFromEvents_SnapshotResetsState(t *testing.T) {
	products := []Position{testPosition(1, "Beer", "Pils", "getraenk", 1000, 10)}
	orderEvent := mustCreateOrderEvent(t, 1, 1, products)
	refs := positionRefsFromOrder(t, orderEvent, 10)

	events := []e.Event{
		orderEvent,
		mustCreatePaymentEvent(t, 1, 1, refs, 10000),
		mustCreateSnapshotEvent(t, 1, 1, 0, []Position{}, []Position{}, 5000),
	}

	totalPayments, err := GetGesamtZahlungenFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if totalPayments != 5000 {
		t.Fatalf("expected totalPayments 5000 (from snapshot), got %d", totalPayments)
	}
}

func TestNewSnapshotEvent(t *testing.T) {
	unpaid := []Position{{PositionID: "00000000-0000-0000-0000-000000000006", VarianteID: 1, ProduktName: "Beer", VarianteName: "Pils", Kategorie: "getraenk", Einzelpreis: 500, Menge: 2}}
	undelivered := []Position{{PositionID: "00000000-0000-0000-0000-000000000007", VarianteID: 2, ProduktName: "Fries", VarianteName: "Pommes", Kategorie: "essen", Einzelpreis: 300, Menge: 1}}

	event, err := NewSnapshotEvent(1, "TestUser", 42, 1000, unpaid, undelivered, 500)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if event.Type != string(EventTypeSnapshotV1) {
		t.Fatalf("expected type %s, got %s", EventTypeSnapshotV1, event.Type)
	}
	if event.Subject != "tisch:42" {
		t.Fatalf("expected subject tisch:42, got %s", event.Subject)
	}
	if event.UserID != 1 {
		t.Fatalf("expected userID 1, got %d", event.UserID)
	}
	if event.UserName != "TestUser" {
		t.Fatalf("expected userName TestUser, got %s", event.UserName)
	}
}

func TestPositionWithFatEventFields(t *testing.T) {
	pos := Position{
		PositionID:   "test-uuid",
		VarianteID:   42,
		ProduktName:  "Beer",
		VarianteName: "Pils 0.5l",
		Kategorie:    "getraenk",
		Einzelpreis:  500,
		Menge:        3,
	}

	if pos.PositionID != "test-uuid" {
		t.Errorf("expected PositionID test-uuid, got %s", pos.PositionID)
	}
	if pos.Einzelpreis*pos.Menge != 1500 {
		t.Errorf("expected total 1500, got %d", pos.Einzelpreis*pos.Menge)
	}
}
