//go:build unit

package table

import (
	"testing"

	e "github.com/nicograef/jotti/backend/domain/event"
)

func mustCreateOrderEvent(t *testing.T, userID, tableID int, products []Position) e.Event {
	t.Helper()
	event, err := NewBestellungAufgegebenEvent(userID, "TestUser", tableID, products, "")
	if err != nil {
		t.Fatalf("failed to create order event: %v", err)
	}
	return event
}

func mustCreatePaymentEvent(t *testing.T, userID, tableID int, positions []Position, gesamtZahlungCents int) e.Event {
	t.Helper()
	event, err := NewZahlungRegistriertEvent(userID, "TestUser", tableID, positions, gesamtZahlungCents, "")
	if err != nil {
		t.Fatalf("failed to create payment event: %v", err)
	}
	return event
}

func mustCreateCancelationEvent(t *testing.T, userID, tableID int, positions []Position, gesamtStornierungCents int) e.Event {
	t.Helper()
	event, err := NewProdukteStorniertEvent(userID, "TestUser", tableID, positions, gesamtStornierungCents, "")
	if err != nil {
		t.Fatalf("failed to create cancelation event: %v", err)
	}
	return event
}

func mustCreateDeliveryEvent(t *testing.T, userID, tableID int, positions []Position) e.Event {
	t.Helper()
	event, err := NewProdukteGeliefertEvent(userID, "TestUser", tableID, positions, "")
	if err != nil {
		t.Fatalf("failed to create delivery event: %v", err)
	}
	return event
}

// helper to create a test Position with fat event fields
func testPosition(varianteID int, produktName, varianteName, kategorie string, einzelpreis, menge int) Position {
	return Position{
		// PositionID will be generated by NewBestellungAufgegebenEvent
		VarianteID:   varianteID,
		ProduktName:  produktName,
		VarianteName: varianteName,
		Kategorie:    kategorie,
		Einzelpreis:  einzelpreis,
		Menge:        menge,
	}
}

// positionsFromOrder extracts full Positions from an order event with adjusted menge
func positionsFromOrder(t *testing.T, orderEvent e.Event, menge int) []Position {
	t.Helper()
	bestellung, err := buildBestellungFromEvent(orderEvent)
	if err != nil {
		t.Fatalf("failed to build bestellung from event: %v", err)
	}
	positions := make([]Position, len(bestellung.Positionen))
	for i, pos := range bestellung.Positionen {
		positions[i] = pos
		positions[i].Menge = menge
	}
	return positions
}

func TestGetHistoryFromEvents_Empty(t *testing.T) {
	history, err := GetHistoryFromEvents([]e.Event{})
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(history) != 0 {
		t.Fatalf("expected empty history, got %d items", len(history))
	}
}

func TestGetHistoryFromEvents_ReturnsAllEventTypes(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 1),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, products)
	positions := positionsFromOrder(t, orderEvent, 1)

	events := []e.Event{
		orderEvent,
		mustCreatePaymentEvent(t, 1, 1, positions, 500),
		mustCreateCancelationEvent(t, 1, 1, positions, 500),
		mustCreateDeliveryEvent(t, 1, 1, positions),
	}

	history, err := GetHistoryFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(history) != 4 {
		t.Fatalf("expected 4 history items, got %d", len(history))
	}
}

func TestGetHistoryFromEvents_ReversesOrder(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 1),
	}
	orderEvent := mustCreateOrderEvent(t, 1, 1, products)
	positions := positionsFromOrder(t, orderEvent, 1)

	events := []e.Event{
		orderEvent,
		mustCreatePaymentEvent(t, 1, 1, positions, 500),
	}

	history, err := GetHistoryFromEvents(events)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	// First item should be payment (last event), second should be order (first event)
	if _, ok := history[0].(Zahlung); !ok {
		t.Fatalf("expected first item to be Zahlung, got %T", history[0])
	}
	if _, ok := history[1].(Bestellung); !ok {
		t.Fatalf("expected second item to be Bestellung, got %T", history[1])
	}
}

func TestPositionWithFatEventFields(t *testing.T) {
	pos := Position{
		PositionID:   "test-uuid",
		VarianteID:   42,
		ProduktName:  "Beer",
		VarianteName: "Pils 0.5l",
		Kategorie:    "getraenk",
		Einzelpreis:  500,
		Menge:        3,
	}

	if pos.PositionID != "test-uuid" {
		t.Errorf("expected PositionID test-uuid, got %s", pos.PositionID)
	}
	if pos.Einzelpreis*pos.Menge != 1500 {
		t.Errorf("expected total 1500, got %d", pos.Einzelpreis*pos.Menge)
	}
}
