// Pfade relativ zu `docs/`. Gelesen vom Glob-Loader (`content.config.ts`) und
// vom Link-Rewriter (`link-rewriter.ts`), der auf `/docs/<slug>/` abbildet.
export const publishedDocs = [
  'leitfaden/was-ist-jotti.md',
  'leitfaden/betriebsarten.md',
  'leitfaden/installation.md',
  'leitfaden/tse-einrichten.md',
  'leitfaden/veranstaltungstag.md',
  'leitfaden/aktualisieren.md',
  'leitfaden/checkliste.md',
  'leitfaden/pflichten.md',
  'leitfaden/finanzamt-anmelden.md',
  'leitfaden/belege-steuersaetze.md',
  'leitfaden/datenaufbewahrung.md',
  'leitfaden/self-hosting.md',
  'leitfaden/aktualisieren-backups.md',
  'leitfaden/tse-sonderfaelle.md',
  'leitfaden/fehlersuche.md',
  'leitfaden/haeufige-fragen.md',
  'compliance.md',
  'steuerrecht.md',
  'verfahrensdokumentation.md',
  'produktbeschreibung.md',
  'lizenzmodell.md',
] as const
