BEGIN;

CREATE EXTENSION IF NOT EXISTS citext; -- Case-insensitive text type for usernames

CREATE TYPE UserRole AS ENUM ('admin', 'service');

CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    username CITEXT UNIQUE NOT NULL,
    password_hash TEXT NULL,
    role UserRole NOT NULL,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE users IS 'System users who perform actions in jotti';
COMMENT ON COLUMN users.id IS 'Surrogate identity primary key';
COMMENT ON COLUMN users.username IS 'Unique, case-insensitive username';
COMMENT ON COLUMN users.password_hash IS 'Argon2id password hash; NULL if user has not set a password (on first login)';
COMMENT ON COLUMN users.created_at IS 'Creation timestamp (UTC)';
COMMENT ON COLUMN users.locked IS 'Indicates whether the user account is locked';
COMMENT ON COLUMN users.role IS 'Role of the user, determining access rights';

-- Create first admin user (without password; set password later)
INSERT INTO users (username, name, role) VALUES ('nico', 'Nico Gräf', 'admin') ON CONFLICT (username) DO NOTHING;

COMMIT;