BEGIN;

CREATE TABLE IF NOT EXISTS events (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    event_subject TEXT NOT NULL,
    event_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE events IS 'Event log for orders/payments and admin actions (event-sourcing)';
COMMENT ON COLUMN events.user_id IS 'Actor who triggered the event (nullable)';
COMMENT ON COLUMN events.event_type IS 'Event type identifier, e.g., bestellung-aufgegeben:v1';
COMMENT ON COLUMN events.event_subject IS 'Aggregate key, e.g., tisch:42';
COMMENT ON COLUMN events.event_timestamp IS 'Event time (UTC)';
COMMENT ON COLUMN events.payload IS 'Event data (jsonb), versioned by event_type';

-- CREATE INDEX IF NOT EXISTS idx_events_subject_time ON events (event_subject, event_timestamp DESC);
-- CREATE INDEX IF NOT EXISTS idx_events_type_time ON events (event_type, event_timestamp DESC);
-- CREATE INDEX IF NOT EXISTS idx_events_user_id ON events (user_id);

COMMIT;