BEGIN;

-- Enums
CREATE TYPE UserRole AS ENUM ('admin', 'serviceleitung', 'service');
CREATE TYPE EntityStatus AS ENUM ('active', 'inactive', 'deleted');

-- Users
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NULL,
    onetime_password_hash TEXT NULL,
    role UserRole NOT NULL,
    status EntityStatus NOT NULL ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);

COMMENT ON TABLE users IS 'System users who perform actions in jotti';
COMMENT ON COLUMN users.name IS 'Full name of the user';
COMMENT ON COLUMN users.username IS 'Unique username';
COMMENT ON COLUMN users.password_hash IS 'Argon2id password hash; NULL if user has not set a password (on first login)';
COMMENT ON COLUMN users.onetime_password_hash IS 'Argon2id password hash for a one-time password. That can be used to setup a new user or reset their password as an admin. NULL if not set';
COMMENT ON COLUMN users.role IS 'Role of the user, determining access rights';
COMMENT ON COLUMN users.status IS 'Account status: active, inactive, or deleted';
COMMENT ON COLUMN users.created_at IS 'Creation timestamp (UTC)';
COMMENT ON COLUMN users.updated_at IS 'Last modification timestamp (UTC)';

-- Create first admin user (without onetime password)
INSERT INTO users (username, name, role, onetime_password_hash, status, created_at, updated_at) VALUES (
  'admin', 'Administrator', 'admin', '$argon2id$v=19$m=64,t=2,p=2$ekV4Uzg2cUhVTTBUaTJJVw$4Sfsc6eRVIWXSzgNoWaybDBws3c830yC6IMcdUDG1ns', 'active', now(), now()
);

-- Tische
CREATE TABLE IF NOT EXISTS tische (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    status EntityStatus NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tische_status ON tische(status);

COMMENT ON TABLE tische IS 'Gäste sitzen an Tischen und geben dort Bestellungen auf.';
COMMENT ON COLUMN tische.name IS 'Name oder Nummer des Tisches (z.B. "Tisch 1")';
COMMENT ON COLUMN tische.status IS 'Tisch-Status: active, inactive oder deleted';
COMMENT ON COLUMN tische.created_at IS 'Creation timestamp (UTC)';
COMMENT ON COLUMN tische.updated_at IS 'Last modification timestamp (UTC)';

-- Produkte
CREATE TYPE ProduktKategorie AS ENUM ('essen', 'getraenk', 'sonstiges');

CREATE TABLE IF NOT EXISTS produkte (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    kategorie ProduktKategorie NOT NULL,
    status EntityStatus NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE produkte IS 'Produkte, die von Gästen bestellt werden können.';
COMMENT ON COLUMN produkte.name IS 'Name des Produkts';
COMMENT ON COLUMN produkte.kategorie IS 'Kategorie des Produkts: essen, getraenk oder sonstiges';
COMMENT ON COLUMN produkte.status IS 'Produkt-Status: active, inactive oder deleted';
COMMENT ON COLUMN produkte.created_at IS 'Creation timestamp (UTC)';
COMMENT ON COLUMN produkte.updated_at IS 'Last modification timestamp (UTC)';


-- Produkt-Varianten

CREATE TABLE IF NOT EXISTS produkt_varianten (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produkt_id INT REFERENCES produkte(id) NOT NULL,
    name TEXT NOT NULL,
    preis_cents INT NOT NULL,
    status EntityStatus NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_produkt_varianten_status ON produkt_varianten(status);

COMMENT ON TABLE produkt_varianten IS 'Varianten von Produkten (verschiedene Größen, Optionen, etc.).';
COMMENT ON COLUMN produkt_varianten.name IS 'Name der Produktvariante';
COMMENT ON COLUMN produkt_varianten.preis_cents IS 'Preis in Cent (z.B. 199 für 1,99 €)';
COMMENT ON COLUMN produkt_varianten.status IS 'Varianten-Status: active, inactive oder deleted';
COMMENT ON COLUMN produkt_varianten.created_at IS 'Creation timestamp (UTC)';
COMMENT ON COLUMN produkt_varianten.updated_at IS 'Last modification timestamp (UTC)';


-- ============================================================
-- Table: kassensitzungen (CRUD entity for Kassensitzung lifecycle)
-- ============================================================
CREATE TABLE kassensitzungen (
    z_nr INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datum DATE NOT NULL,
    bezeichnung TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('offen', 'abgeschlossen')),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL   
);

CREATE UNIQUE INDEX idx_kassensitzungen_eine_offen
    ON kassensitzungen (status) WHERE status = 'offen';

COMMENT ON TABLE kassensitzungen IS 'CRUD entity for Kassensitzung lifecycle. Each row represents one Kassensitzung (one Betriebstag). The z_nr is the DSFinV-K-compliant sequential number.';
COMMENT ON COLUMN kassensitzungen.z_nr IS 'Fortlaufende Kassensitzungsnummer (Z_NR), DSFinV-K-Pflichtfeld';
COMMENT ON COLUMN kassensitzungen.datum IS 'Betriebstag der Kassensitzung';
COMMENT ON COLUMN kassensitzungen.bezeichnung IS 'Bezeichnung (z.B. "Sommerfest Tag 1")';
COMMENT ON COLUMN kassensitzungen.status IS 'Kassensitzung-Status: offen oder abgeschlossen';
COMMENT ON COLUMN kassensitzungen.created_at IS 'Creation timestamp (UTC)';
COMMENT ON COLUMN kassensitzungen.updated_at IS 'Last modification timestamp (UTC)';

-- ============================================================
-- Table: kassenjournal (Event Store for all kasse operations)
-- ============================================================
-- Append-only, never updated or deleted (INSERT and SELECT only).
CREATE TABLE IF NOT EXISTS kassenjournal (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(id) NOT NULL,
    user_name TEXT NOT NULL,
    type TEXT NOT NULL,
    subject TEXT NOT NULL,
    version INT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    data JSONB NOT NULL,
    kassensitzung_nr INT NOT NULL REFERENCES kassensitzungen(z_nr),
    UNIQUE (subject, version)
);

CREATE INDEX IF NOT EXISTS idx_kassenjournal_user_id ON kassenjournal(user_id);
CREATE INDEX IF NOT EXISTS idx_kassenjournal_subject_type ON kassenjournal(subject, type);
CREATE INDEX IF NOT EXISTS idx_kassenjournal_type_timestamp ON kassenjournal(type, timestamp);
CREATE INDEX IF NOT EXISTS idx_kassenjournal_ks_nr ON kassenjournal(kassensitzung_nr);

-- Restrict public role to SELECT + INSERT only (defense-in-depth for non-owner roles)
REVOKE ALL ON TABLE kassenjournal FROM PUBLIC;
GRANT SELECT, INSERT ON TABLE kassenjournal TO PUBLIC;

-- Triggers to enforce append-only immutability for ALL roles, including the table owner.
-- REVOKE/GRANT alone is not sufficient because PostgreSQL table owners bypass privilege checks.
-- Generic write-protection guard, shared with the insert-once kassenidentitaet table.
CREATE OR REPLACE FUNCTION prevent_table_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'table % is write-protected: % not allowed', TG_TABLE_NAME, TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER kassenjournal_no_update
    BEFORE UPDATE ON kassenjournal FOR EACH ROW
    EXECUTE FUNCTION prevent_table_mutation();

CREATE TRIGGER kassenjournal_no_delete
    BEFORE DELETE ON kassenjournal FOR EACH ROW
    EXECUTE FUNCTION prevent_table_mutation();

CREATE TRIGGER kassenjournal_no_truncate
    BEFORE TRUNCATE ON kassenjournal FOR EACH STATEMENT
    EXECUTE FUNCTION prevent_table_mutation();

COMMENT ON TABLE kassenjournal IS 'Append-only Kassenjournal (Event Store) for all kasse operations (event-sourcing)';
COMMENT ON COLUMN kassenjournal.user_id IS 'Actor who triggered the event';
COMMENT ON COLUMN kassenjournal.user_name IS 'Display name of the actor at the time of the event';
COMMENT ON COLUMN kassenjournal.version IS 'Optimistic concurrency version per subject (monotonically increasing)';
COMMENT ON COLUMN kassenjournal.type IS 'Event type identifier, e.g., bestellung-aufgenommen:v1';
COMMENT ON COLUMN kassenjournal.subject IS 'Aggregate key, e.g. "kassensitzung-1/tisch-42" for a tisch session, "kassensitzung-1" for a kassensitzung';
COMMENT ON COLUMN kassenjournal.timestamp IS 'Event time (UTC)';
COMMENT ON COLUMN kassenjournal.data IS 'Event data (jsonb), versioned by type';
COMMENT ON COLUMN kassenjournal.kassensitzung_nr IS 'Kassensitzung number (z_nr) this event belongs to';

-- ============================================================
-- Table: tisch_sessions (CQRS projection of per-tisch-session state)
-- ============================================================
CREATE TABLE tisch_sessions (
    subject TEXT PRIMARY KEY,
    tisch_id INT NOT NULL REFERENCES tische(id),
    kassensitzung_nr INT NOT NULL REFERENCES kassensitzungen(z_nr),
    saldo_cents INTEGER NOT NULL,
    unbezahlte_positionen JSONB NOT NULL,
    ausstehende_positionen JSONB NOT NULL,
    gesamt_zahlungen_cents INTEGER NOT NULL,
    last_event_id INTEGER NOT NULL REFERENCES kassenjournal(id),
    last_event_version INTEGER NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tisch_sessions_ks_nr ON tisch_sessions(kassensitzung_nr);

COMMENT ON TABLE tisch_sessions IS 'Synchronous CQRS projection of per-tisch-session state, session-scoped (PK: subject), updated within the event-write transaction';

-- ============================================================
-- Table: tisch_favoriten (per-user favorite tables)
-- ============================================================
CREATE TABLE tisch_favoriten (
    user_id INT REFERENCES users(id) NOT NULL,
    tisch_id INT REFERENCES tische(id) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, tisch_id)
);

CREATE INDEX IF NOT EXISTS idx_tisch_favoriten_user_id ON tisch_favoriten(user_id);

COMMENT ON TABLE tisch_favoriten IS 'Per-user favourite tables; each service user can mark tables they are responsible for.';

-- ============================================================
-- Table: kategorie_drucker (Drucker-Konfiguration pro Produkt-Kategorie)
-- ============================================================
CREATE TABLE kategorie_drucker (
    kategorie   ProduktKategorie PRIMARY KEY,
    drucker_ip  VARCHAR(50) NOT NULL,
    bonmodus    TEXT NOT NULL
                CHECK (bonmodus IN ('pro_position', 'pro_bestellung')),
    updated_at  TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE kategorie_drucker IS 'Drucker-IP und Bonmodus pro Produkt-Kategorie für den Bondruck.';
COMMENT ON COLUMN kategorie_drucker.drucker_ip IS 'IPv4-Adresse des Bondruckers (leer = kein Drucker konfiguriert)';
COMMENT ON COLUMN kategorie_drucker.bonmodus IS 'Bonmodus: pro_position (1 Bon pro Position) oder pro_bestellung (1 Sammelbon)';

INSERT INTO kategorie_drucker (kategorie, drucker_ip, bonmodus, updated_at) VALUES
    ('essen',     '', 'pro_position', now()),
    ('getraenk',  '', 'pro_position', now()),
    ('sonstiges', '', 'pro_position', now());

-- ============================================================
-- Reporting helper functions
-- Encapsulate repeated CASE WHEN event-extraction logic from
-- kassenjournal queries so each monetary field is defined once.
-- ============================================================

-- Returns the Zahlung amount in cents for a matching event row, NULL otherwise.
CREATE OR REPLACE FUNCTION kj_extract_zahlung_cents(type TEXT, data JSONB) RETURNS int AS $$
    SELECT CASE WHEN type = 'zahlung-kassiert:v1' THEN (data->>'gesamtZahlungCents')::int END
$$ LANGUAGE sql IMMUTABLE;

-- Returns the Auszahlung amount in cents for a matching event row, NULL otherwise.
CREATE OR REPLACE FUNCTION kj_extract_auszahlung_cents(type TEXT, data JSONB) RETURNS int AS $$
    SELECT CASE WHEN type = 'auszahlung-geleistet:v1' THEN (data->>'betragCents')::int END
$$ LANGUAGE sql IMMUTABLE;

-- Returns the Bestellung amount in cents for a matching event row, NULL otherwise.
CREATE OR REPLACE FUNCTION kj_extract_bestellung_cents(type TEXT, data JSONB) RETURNS int AS $$
    SELECT CASE WHEN type = 'bestellung-aufgenommen:v1' THEN (data->>'gesamtPreisCents')::int END
$$ LANGUAGE sql IMMUTABLE;

-- Returns the Stornierung amount in cents for a matching event row, NULL otherwise.
CREATE OR REPLACE FUNCTION kj_extract_stornierung_cents(type TEXT, data JSONB) RETURNS int AS $$
    SELECT CASE WHEN type = 'stornierung-erteilt:v1' THEN (data->>'gesamtStornierungCents')::int END
$$ LANGUAGE sql IMMUTABLE;

-- ============================================================
-- Table: kassenidentitaet (Kassenidentität, Singleton)
-- Insert-once at first startup; afterwards fully read-only (no INSERT/UPDATE/DELETE/TRUNCATE).
-- ============================================================
CREATE TABLE kassenidentitaet (
    id          INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    seriennummer   UUID NOT NULL,
    angelegt_am TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE kassenidentitaet IS 'Kassenidentität (Singleton). Einmalig bei der DB-Migration eingebrannt, danach read-only (insert-once).';
COMMENT ON COLUMN kassenidentitaet.seriennummer IS 'UUID-v4 Seriennummer der Kasse — nie überschreiben';
COMMENT ON COLUMN kassenidentitaet.angelegt_am IS 'Zeitpunkt der ersten Inbetriebnahme (UTC)';

-- Insert the one and only identity row before the write-protection triggers are installed.
INSERT INTO kassenidentitaet (seriennummer, angelegt_am) VALUES (gen_random_uuid(), now());

-- Lock the table down: read-only for the public role (no INSERT, unlike kassenjournal).
REVOKE ALL ON TABLE kassenidentitaet FROM PUBLIC;
GRANT SELECT ON TABLE kassenidentitaet TO PUBLIC;

-- Triggers enforce insert-once immutability for ALL roles, including the table owner,
-- because REVOKE/GRANT alone does not constrain the owner.
CREATE TRIGGER kassenidentitaet_no_insert
    BEFORE INSERT ON kassenidentitaet FOR EACH ROW
    EXECUTE FUNCTION prevent_table_mutation();

CREATE TRIGGER kassenidentitaet_no_update
    BEFORE UPDATE ON kassenidentitaet FOR EACH ROW
    EXECUTE FUNCTION prevent_table_mutation();

CREATE TRIGGER kassenidentitaet_no_delete
    BEFORE DELETE ON kassenidentitaet FOR EACH ROW
    EXECUTE FUNCTION prevent_table_mutation();

CREATE TRIGGER kassenidentitaet_no_truncate
    BEFORE TRUNCATE ON kassenidentitaet FOR EACH STATEMENT
    EXECUTE FUNCTION prevent_table_mutation();

-- ============================================================
-- Table: betreiber (Betreiber-Stammdaten, Singleton)
-- Admin-managed; at most one row; required before Kassensitzung can be opened.
-- ============================================================
CREATE TABLE betreiber (
    id           INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    vereinsname  TEXT NOT NULL,
    strasse      TEXT NOT NULL,
    plz          TEXT NOT NULL,
    ort          TEXT NOT NULL,
    steuernummer TEXT NULL,
    ust_id       TEXT NULL,
    updated_at   TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE betreiber IS 'Betreiber-Stammdaten (Singleton). Pflichtfeld vor erster Kassensitzung.';
COMMENT ON COLUMN betreiber.vereinsname IS 'Name des Vereins / Betreibers';
COMMENT ON COLUMN betreiber.strasse IS 'Straße und Hausnummer';
COMMENT ON COLUMN betreiber.plz IS 'Postleitzahl';
COMMENT ON COLUMN betreiber.ort IS 'Ort';
COMMENT ON COLUMN betreiber.steuernummer IS 'Steuernummer (optional)';
COMMENT ON COLUMN betreiber.ust_id IS 'USt-ID (optional)';
COMMENT ON COLUMN betreiber.updated_at IS 'Letzte Änderung (UTC)';

COMMIT;