BEGIN;

-- Enums
CREATE TYPE UserRole AS ENUM ('admin', 'senior_service', 'service');
CREATE TYPE EntityStatus AS ENUM ('active', 'inactive', 'deleted');

-- Users
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NULL,
    onetime_password_hash TEXT NULL,
    role UserRole NOT NULL,
    status EntityStatus NOT NULL ,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);

COMMENT ON TABLE users IS 'System users who perform actions in jotti';
COMMENT ON COLUMN users.name IS 'Full name of the user';
COMMENT ON COLUMN users.username IS 'Unique username';
COMMENT ON COLUMN users.password_hash IS 'Argon2id password hash; NULL if user has not set a password (on first login)';
COMMENT ON COLUMN users.onetime_password_hash IS 'Argon2id password hash for a one-time password. That can be used to setup a new user or reset their password as an admin. NULL if not set';
COMMENT ON COLUMN users.role IS 'Role of the user, determining access rights';
COMMENT ON COLUMN users.status IS 'Account status: active, inactive, or deleted';
COMMENT ON COLUMN users.created_at IS 'Creation timestamp (UTC)';

-- Create first admin user (without onetime password)
INSERT INTO users (username, name, role, onetime_password_hash, status, created_at) VALUES (
  'nico', 'Nico Gräf', 'admin', '$argon2id$v=19$m=64,t=2,p=2$ekV4Uzg2cUhVTTBUaTJJVw$4Sfsc6eRVIWXSzgNoWaybDBws3c830yC6IMcdUDG1ns', 'active', now()
);

-- Tables
CREATE TABLE IF NOT EXISTS tables (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    status EntityStatus NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tables_status ON tables(status);

COMMENT ON TABLE tables IS 'Customers sit at tables and place orders from there.';
COMMENT ON COLUMN tables.name IS 'Name or number of the table (e.g., "Table 1")';
COMMENT ON COLUMN tables.status IS 'Table status: active, inactive, or deleted';
COMMENT ON COLUMN tables.created_at IS 'Creation timestamp (UTC)';

-- Products
CREATE TYPE ProductCategory AS ENUM ('food', 'beverage', 'other');

CREATE TABLE IF NOT EXISTS products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category ProductCategory NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE products IS 'Products that can be ordered by customers.';
COMMENT ON COLUMN products.name IS 'Name of the product';
COMMENT ON COLUMN products.category IS 'Category of the product: food, beverage, or other';
COMMENT ON COLUMN products.created_at IS 'Creation timestamp (UTC)';


-- Product Varaiants

CREATE TABLE IF NOT EXISTS product_variants (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT REFERENCES products(id) NOT NULL,
    name TEXT NOT NULL,
    price_cents INT NOT NULL,
    status EntityStatus NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_product_variants_status ON product_variants(status);

COMMENT ON TABLE product_variants IS 'Variants of products that can be ordered by customers (different sizes, options, etc.).';
COMMENT ON COLUMN product_variants.name IS 'Name of the product variant';
COMMENT ON COLUMN product_variants.price_cents IS 'Price in cents (e.g., 199 for €1.99)';
COMMENT ON COLUMN product_variants.status IS 'Product variant status: active, inactive, or deleted';
COMMENT ON COLUMN product_variants.created_at IS 'Creation timestamp (UTC)';


-- Events table for event sourcing. Stores all events related to orders, payments, and admin actions.
-- Append-only, never updated or deleted (INSERT and SELECT only).
CREATE TABLE IF NOT EXISTS events (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(id) NOT NULL,
    type TEXT NOT NULL,
    subject TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    data JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_events_user_id ON events(user_id);
CREATE INDEX IF NOT EXISTS idx_events_subject ON events(subject);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(type);
CREATE INDEX IF NOT EXISTS idx_events_subject_type ON events(subject, type);

-- Restrict public role to SELECT + INSERT only (defense-in-depth for non-owner roles)
REVOKE ALL ON TABLE events FROM PUBLIC;
GRANT SELECT, INSERT ON TABLE events TO PUBLIC;

-- Triggers to enforce append-only immutability for ALL roles, including the table owner.
-- REVOKE/GRANT alone is not sufficient because PostgreSQL table owners bypass privilege checks.
CREATE OR REPLACE FUNCTION prevent_event_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'events table is append-only: % not allowed', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER events_no_update
    BEFORE UPDATE ON events FOR EACH ROW
    EXECUTE FUNCTION prevent_event_mutation();

CREATE TRIGGER events_no_delete
    BEFORE DELETE ON events FOR EACH ROW
    EXECUTE FUNCTION prevent_event_mutation();

CREATE TRIGGER events_no_truncate
    BEFORE TRUNCATE ON events FOR EACH STATEMENT
    EXECUTE FUNCTION prevent_event_mutation();

COMMENT ON TABLE events IS 'Event log for orders/payments and admin actions (event-sourcing)';
COMMENT ON COLUMN events.user_id IS 'Actor who triggered the event (nullable)';
COMMENT ON COLUMN events.type IS 'Event type identifier, e.g., bestellung-aufgegeben:v1';
COMMENT ON COLUMN events.subject IS 'Aggregate key, e.g. "table:42" for table ID 42';
COMMENT ON COLUMN events.timestamp IS 'Event time (UTC)';
COMMENT ON COLUMN events.data IS 'Event data (jsonb), versioned by type';

COMMIT;