BEGIN;

CREATE TABLE IF NOT EXISTS tables (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE tables IS 'Customers sit at tables and place orders from there.';
COMMENT ON COLUMN tables.id IS 'Surrogate identity primary key';
COMMENT ON COLUMN tables.name IS 'Name or number of the table (e.g., "Table 1")';
COMMENT ON COLUMN tables.created_at IS 'Creation timestamp (UTC)';

COMMIT;