//go:build unit

package kasse

import (
	"encoding/json"
	"testing"
	"time"

	e "github.com/nicograef/jotti/backend/domain/event"
)

func mustCreateOrderEvent(t *testing.T, subject string, userID int, products []Position) e.Event {
	t.Helper()
	event, err := NewBestellungAufgenommenEvent(subject, userID, "TestUser", products, "")
	if err != nil {
		t.Fatalf("failed to create order event: %v", err)
	}
	return event
}

func mustCreatePaymentEvent(t *testing.T, subject string, userID int, positions []Position, gesamtZahlungCents int) e.Event {
	t.Helper()
	event, err := NewZahlungKassiertEvent(subject, userID, "TestUser", positions, gesamtZahlungCents, "")
	if err != nil {
		t.Fatalf("failed to create payment event: %v", err)
	}
	return event
}

func mustCreateCancelationEvent(t *testing.T, subject string, userID int, zahlungID string, positions []Position, gesamtStornierungCents int) e.Event {
	t.Helper()
	event, err := NewStornierungErteiltEvent(subject, userID, "TestUser", zahlungID, positions, gesamtStornierungCents, "Test")
	if err != nil {
		t.Fatalf("failed to create cancelation event: %v", err)
	}
	return event
}

func mustCreateKorrekturEvent(t *testing.T, subject string, userID int, positions []Position, gesamtCents int) e.Event {
	t.Helper()
	event, err := NewBestellungKorrigiertEvent(subject, userID, "TestUser", positions, gesamtCents, "Test")
	if err != nil {
		t.Fatalf("failed to create korrektur event: %v", err)
	}
	return event
}

const testZahlungID = "11111111-1111-1111-1111-111111111111"

func mustCreateDeliveryEvent(t *testing.T, subject string, userID int, positions []Position) e.Event {
	t.Helper()
	event, err := NewAusgabeBestaetigtEvent(subject, userID, "TestUser", positions, "")
	if err != nil {
		t.Fatalf("failed to create delivery event: %v", err)
	}
	return event
}

// helper to create a test Position with fat event fields
func testPosition(varianteID int, produktName, varianteName, kategorie string, einzelpreis, menge int) Position {
	steuersatz := "regel"
	switch kategorie {
	case "essen":
		steuersatz = "ermaessigt"
	case "getraenk":
		steuersatz = "regel"
	case "sonstiges":
		steuersatz = "befreit"
	}

	return Position{
		// PositionID will be generated by NewBestellungAufgenommenEvent
		VarianteID:       varianteID,
		ProduktName:      produktName,
		VarianteName:     varianteName,
		Kategorie:        kategorie,
		Steuersatz:       steuersatz,
		EinzelpreisCents: einzelpreis,
		Menge:            menge,
	}
}

// positionsFromOrder extracts full Positions from an order event with adjusted menge
func positionsFromOrder(t *testing.T, orderEvent e.Event, menge int) []Position {
	t.Helper()
	bestellung, err := buildBestellungFromEvent(orderEvent)
	if err != nil {
		t.Fatalf("failed to build bestellung from event: %v", err)
	}
	positions := make([]Position, len(bestellung.Positionen))
	for i, pos := range bestellung.Positionen {
		positions[i] = pos
		positions[i].Menge = menge
	}
	return positions
}

const testSubject = "kassensitzung-1/tisch-42"

func TestApplyEvent_BestellungOnEmptyTable(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if state.SaldoCents != 1000 {
		t.Fatalf("expected SaldoCents 1000, got %d", state.SaldoCents)
	}
	if len(state.UnbezahltePositionen) != 1 {
		t.Fatalf("expected 1 unbezahlte position, got %d", len(state.UnbezahltePositionen))
	}
	if state.UnbezahltePositionen[0].Menge != 2 {
		t.Fatalf("expected Menge 2, got %d", state.UnbezahltePositionen[0].Menge)
	}
	if len(state.AusstehendePositionen) != 1 {
		t.Fatalf("expected 1 ungelieferte position, got %d", len(state.AusstehendePositionen))
	}
	if state.AusstehendePositionen[0].Menge != 2 {
		t.Fatalf("expected Menge 2, got %d", state.AusstehendePositionen[0].Menge)
	}
	if state.GesamtZahlungenCents != 0 {
		t.Fatalf("expected GesamtZahlungenCents 0, got %d", state.GesamtZahlungenCents)
	}
	if state.LastEventID != 1 {
		t.Fatalf("expected LastEventID 1, got %d", state.LastEventID)
	}
	if state.LastEventVersion != 1 {
		t.Fatalf("expected LastEventVersion 1, got %d", state.LastEventVersion)
	}
}

func TestApplyEvent_ZahlungReducesSaldoAndUnbezahlt(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	positions := positionsFromOrder(t, orderEvent, 1)
	paymentEvent := mustCreatePaymentEvent(t, testSubject, 1, positions, 500)
	paymentEvent.ID = 2
	paymentEvent.Version = 2

	state, err = ApplyEvent(state, paymentEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if state.SaldoCents != 500 {
		t.Fatalf("expected SaldoCents 500, got %d", state.SaldoCents)
	}
	if state.GesamtZahlungenCents != 500 {
		t.Fatalf("expected GesamtZahlungenCents 500, got %d", state.GesamtZahlungenCents)
	}
	if len(state.UnbezahltePositionen) != 1 {
		t.Fatalf("expected 1 unbezahlte position, got %d", len(state.UnbezahltePositionen))
	}
	if state.UnbezahltePositionen[0].Menge != 1 {
		t.Fatalf("expected Menge 1, got %d", state.UnbezahltePositionen[0].Menge)
	}
	if state.LastEventID != 2 {
		t.Fatalf("expected LastEventID 2, got %d", state.LastEventID)
	}
}

func TestApplyEvent_KorrekturReducesSaldoAndUnbezahlt(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// Geldneutrale Korrektur einer noch unbezahlten Position.
	positions := positionsFromOrder(t, orderEvent, 1)
	cancelEvent := mustCreateKorrekturEvent(t, testSubject, 1, positions, 500)
	cancelEvent.ID = 2
	cancelEvent.Version = 2

	state, err = ApplyEvent(state, cancelEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if state.SaldoCents != 500 {
		t.Fatalf("expected SaldoCents 500, got %d", state.SaldoCents)
	}
	if len(state.UnbezahltePositionen) != 1 {
		t.Fatalf("expected 1 unbezahlte position, got %d", len(state.UnbezahltePositionen))
	}
	if state.UnbezahltePositionen[0].Menge != 1 {
		t.Fatalf("expected Menge 1, got %d", state.UnbezahltePositionen[0].Menge)
	}
	// Stornierung also reduces ausstehende
	if len(state.AusstehendePositionen) != 1 {
		t.Fatalf("expected 1 ungelieferte position, got %d", len(state.AusstehendePositionen))
	}
	if state.AusstehendePositionen[0].Menge != 1 {
		t.Fatalf("expected Menge 1, got %d", state.AusstehendePositionen[0].Menge)
	}
}

func TestApplyEvent_UmbuchungMovesPositionsBetweenTische(t *testing.T) {
	const zNr = 1
	const quellTischID = 42
	const zielTischID = 7
	quellSubject := TischSessionSubject(zNr, quellTischID)
	zielSubject := TischSessionSubject(zNr, zielTischID)

	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, quellSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	quellState, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// Eine von zwei Positionen auf den Zieltisch umbuchen.
	umbuchPositionen := positionsFromOrder(t, orderEvent, 1)
	quellEvent, zielEvent, err := NewBestellungUmgebuchtEvents(zNr, quellTischID, zielTischID, 1, "TestUser", umbuchPositionen, 500, "Umbuchung auf Tisch Ziel", "Umbuchung von Tisch Quelle")
	if err != nil {
		t.Fatalf("failed to create umbuchung events: %v", err)
	}
	quellEvent.ID, quellEvent.Version = 2, 2
	zielEvent.ID, zielEvent.Version = 3, 1

	// Abgang auf dem Quelltisch: Saldo sinkt, eine Position bleibt.
	quellState, err = ApplyEvent(quellState, quellEvent)
	if err != nil {
		t.Fatalf("expected no error applying abgang, got %v", err)
	}
	if quellState.SaldoCents != 500 {
		t.Fatalf("expected source SaldoCents 500, got %d", quellState.SaldoCents)
	}
	if len(quellState.UnbezahltePositionen) != 1 || quellState.UnbezahltePositionen[0].Menge != 1 {
		t.Fatalf("expected 1 unbezahlte position with menge 1, got %+v", quellState.UnbezahltePositionen)
	}
	if len(quellState.AusstehendePositionen) != 1 || quellState.AusstehendePositionen[0].Menge != 1 {
		t.Fatalf("expected 1 ausstehende position with menge 1, got %+v", quellState.AusstehendePositionen)
	}

	// Zugang auf dem leeren Zieltisch: wie eine frische Bestellung.
	zielState, err := ApplyEvent(TischSession{Subject: zielSubject}, zielEvent)
	if err != nil {
		t.Fatalf("expected no error applying zugang, got %v", err)
	}
	if zielState.SaldoCents != 500 {
		t.Fatalf("expected target SaldoCents 500, got %d", zielState.SaldoCents)
	}
	if len(zielState.UnbezahltePositionen) != 1 || zielState.UnbezahltePositionen[0].Menge != 1 {
		t.Fatalf("expected 1 unbezahlte position with menge 1, got %+v", zielState.UnbezahltePositionen)
	}
	if len(zielState.AusstehendePositionen) != 1 || zielState.AusstehendePositionen[0].Menge != 1 {
		t.Fatalf("expected 1 ausstehende position with menge 1, got %+v", zielState.AusstehendePositionen)
	}
	if zielState.ErsteBestellungLogTime == nil {
		t.Fatal("expected target ErsteBestellungLogTime to be set by the zugang")
	}
	// Der Zugang trägt frische PositionIDs (eigenständig auf dem Zieltisch).
	if zielState.UnbezahltePositionen[0].PositionID == quellState.UnbezahltePositionen[0].PositionID {
		t.Fatal("expected target position to carry a fresh PositionID")
	}
}

func TestApplyEvent_AusgabeReducesOnlyAusstehend(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	positions := positionsFromOrder(t, orderEvent, 2)
	deliveryEvent := mustCreateDeliveryEvent(t, testSubject, 1, positions)
	deliveryEvent.ID = 2
	deliveryEvent.Version = 2

	state, err = ApplyEvent(state, deliveryEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// Saldo unchanged
	if state.SaldoCents != 1000 {
		t.Fatalf("expected SaldoCents 1000, got %d", state.SaldoCents)
	}
	// Unbezahlt unchanged
	if len(state.UnbezahltePositionen) != 1 {
		t.Fatalf("expected 1 unbezahlte position, got %d", len(state.UnbezahltePositionen))
	}
	if state.UnbezahltePositionen[0].Menge != 2 {
		t.Fatalf("expected Menge 2, got %d", state.UnbezahltePositionen[0].Menge)
	}
	// Ungeliefert reduced to 0
	if len(state.AusstehendePositionen) != 0 {
		t.Fatalf("expected 0 ungelieferte positionen, got %d", len(state.AusstehendePositionen))
	}
}

func TestApplyEvent_MultipleEventsSequentially(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 3),
		testPosition(2, "Wurst", "Bratwurst", "essen", 400, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	// Apply order: saldo = 500*3 + 400*2 = 2300
	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != 2300 {
		t.Fatalf("expected SaldoCents 2300, got %d", state.SaldoCents)
	}

	// Deliver all beer
	bestellung, err := buildBestellungFromEvent(orderEvent)
	if err != nil {
		t.Fatalf("failed to build bestellung: %v", err)
	}
	beerPos := []Position{bestellung.Positionen[0]}
	beerPos[0].Menge = 3
	deliveryEvent := mustCreateDeliveryEvent(t, testSubject, 1, beerPos)
	deliveryEvent.ID = 2
	deliveryEvent.Version = 2

	state, err = ApplyEvent(state, deliveryEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	// Saldo unchanged
	if state.SaldoCents != 2300 {
		t.Fatalf("expected SaldoCents 2300, got %d", state.SaldoCents)
	}
	// 2 ausstehende (only wurst remaining)
	if len(state.AusstehendePositionen) != 1 {
		t.Fatalf("expected 1 ungelieferte position, got %d", len(state.AusstehendePositionen))
	}

	// Pay for 1 beer (500)
	beerPayPos := []Position{bestellung.Positionen[0]}
	beerPayPos[0].Menge = 1
	paymentEvent := mustCreatePaymentEvent(t, testSubject, 1, beerPayPos, 500)
	paymentEvent.ID = 3
	paymentEvent.Version = 3

	state, err = ApplyEvent(state, paymentEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != 1800 {
		t.Fatalf("expected SaldoCents 1800, got %d", state.SaldoCents)
	}
	if state.GesamtZahlungenCents != 500 {
		t.Fatalf("expected GesamtZahlungenCents 500, got %d", state.GesamtZahlungenCents)
	}

	// Cancel 1 wurst (400) — still unbezahlt, so a geldneutral correction.
	wurstPos := []Position{bestellung.Positionen[1]}
	wurstPos[0].Menge = 1
	cancelEvent := mustCreateKorrekturEvent(t, testSubject, 1, wurstPos, 400)
	cancelEvent.ID = 4
	cancelEvent.Version = 4

	state, err = ApplyEvent(state, cancelEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != 1400 {
		t.Fatalf("expected SaldoCents 1400, got %d", state.SaldoCents)
	}
	if state.LastEventID != 4 {
		t.Fatalf("expected LastEventID 4, got %d", state.LastEventID)
	}
	if state.LastEventVersion != 4 {
		t.Fatalf("expected LastEventVersion 4, got %d", state.LastEventVersion)
	}
}

func TestApplyEvent_BestellungTagsBesteller(t *testing.T) {
	products := []Position{testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2)}
	orderEvent, err := NewBestellungAufgenommenEvent(testSubject, 7, "Anna", products, "")
	if err != nil {
		t.Fatalf("failed to create order event: %v", err)
	}
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if state.UnbezahltePositionen[0].BestellerUserID != 7 || state.UnbezahltePositionen[0].BestellerName != "Anna" {
		t.Errorf("expected unbezahlt besteller 7/Anna, got %d/%q",
			state.UnbezahltePositionen[0].BestellerUserID, state.UnbezahltePositionen[0].BestellerName)
	}
	if state.AusstehendePositionen[0].BestellerUserID != 7 || state.AusstehendePositionen[0].BestellerName != "Anna" {
		t.Errorf("expected ausstehend besteller 7/Anna, got %d/%q",
			state.AusstehendePositionen[0].BestellerUserID, state.AusstehendePositionen[0].BestellerName)
	}
}

func TestApplyEvent_MultipleBestellerAtSameTable(t *testing.T) {
	annaOrder, err := NewBestellungAufgenommenEvent(testSubject, 7, "Anna", []Position{testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 1)}, "")
	if err != nil {
		t.Fatalf("failed to create anna order: %v", err)
	}
	annaOrder.ID, annaOrder.Version = 1, 1

	bertOrder, err := NewBestellungAufgenommenEvent(testSubject, 8, "Bert", []Position{testPosition(2, "Wurst", "Bratwurst", "essen", 400, 1)}, "")
	if err != nil {
		t.Fatalf("failed to create bert order: %v", err)
	}
	bertOrder.ID, bertOrder.Version = 2, 2

	state, err := ApplyEvent(TischSession{}, annaOrder)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	state, err = ApplyEvent(state, bertOrder)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	bestellerByProdukt := map[string]string{}
	for _, pos := range state.AusstehendePositionen {
		bestellerByProdukt[pos.ProduktName] = pos.BestellerName
	}
	if bestellerByProdukt["Beer"] != "Anna" {
		t.Errorf("expected Beer ordered by Anna, got %q", bestellerByProdukt["Beer"])
	}
	if bestellerByProdukt["Wurst"] != "Bert" {
		t.Errorf("expected Wurst ordered by Bert, got %q", bestellerByProdukt["Wurst"])
	}
}

func TestApplyEvent_PaymentCancelDeliveryKeepBestellerTag(t *testing.T) {
	products := []Position{testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 3)}
	orderEvent, err := NewBestellungAufgenommenEvent(testSubject, 7, "Anna", products, "")
	if err != nil {
		t.Fatalf("failed to create order event: %v", err)
	}
	orderEvent.ID, orderEvent.Version = 1, 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// A colleague (Bert) delivers and pays part of Anna's order — the besteller tag must survive.
	deliverPos := positionsFromOrder(t, orderEvent, 1)
	deliveryEvent := mustCreateDeliveryEvent(t, testSubject, 8, deliverPos)
	deliveryEvent.ID, deliveryEvent.Version = 2, 2
	state, err = ApplyEvent(state, deliveryEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	payPos := positionsFromOrder(t, orderEvent, 1)
	paymentEvent := mustCreatePaymentEvent(t, testSubject, 8, payPos, 500)
	paymentEvent.ID, paymentEvent.Version = 3, 3
	state, err = ApplyEvent(state, paymentEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if state.AusstehendePositionen[0].BestellerName != "Anna" {
		t.Errorf("expected ausstehend besteller to stay Anna, got %q", state.AusstehendePositionen[0].BestellerName)
	}
	if state.UnbezahltePositionen[0].BestellerName != "Anna" {
		t.Errorf("expected unbezahlt besteller to stay Anna, got %q", state.UnbezahltePositionen[0].BestellerName)
	}
}

// TestApplyEvent_DoesNotMutateInputState belegt, dass ApplyEvent den übergebenen
// State (inkl. seiner Position-Slices) nicht mutiert — kein Backing-Array-Alias.
// Dieser Test schlägt ohne die Klon-Fixes in accumulatePositionen/
// reduceByPosition*/tagBesteller fehl, weil die Helfer das Backing-Array der
// Eingabe direkt modifizieren.
func TestApplyEvent_DoesNotMutateInputState(t *testing.T) {
	products := []Position{testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 3)}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID, orderEvent.Version = 1, 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(state.UnbezahltePositionen) != 1 {
		t.Fatalf("expected 1 unbezahlte position, got %d", len(state.UnbezahltePositionen))
	}

	// Menge und Länge vor dem zweiten ApplyEvent einfrieren.
	wantMenge := state.UnbezahltePositionen[0].Menge       // = 3
	wantLen := len(state.UnbezahltePositionen)             // = 1
	wantAusstLen := len(state.AusstehendePositionen)       // = 1
	wantAusstMenge := state.AusstehendePositionen[0].Menge // = 3

	// Korrektur über 1 Einheit: ruft reduceByPositionStrict (UnbezahltePositionen) UND
	// reduceByPosition (AusstehendePositionen) auf — beide Klon-Pfade werden geprüft.
	// Ohne den make+copy-Klon würden beide Helfer das Backing-Array des Input-State mutieren.
	korrekturPositionen := positionsFromOrder(t, orderEvent, 1)
	korrekturEvent := mustCreateKorrekturEvent(t, testSubject, 1, korrekturPositionen, 500)
	korrekturEvent.ID, korrekturEvent.Version = 2, 2

	state2, err := ApplyEvent(state, korrekturEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// Der ursprüngliche state darf nicht verändert worden sein.
	if len(state.UnbezahltePositionen) != wantLen {
		t.Errorf("original state UnbezahltePositionen length mutated: was %d, now %d",
			wantLen, len(state.UnbezahltePositionen))
	}
	if state.UnbezahltePositionen[0].Menge != wantMenge {
		t.Errorf("ApplyEvent mutierte den Input-State: UnbezahltePositionen[0].Menge = %d, want %d",
			state.UnbezahltePositionen[0].Menge, wantMenge)
	}
	if len(state.AusstehendePositionen) != wantAusstLen {
		t.Errorf("original state AusstehendePositionen length mutated: was %d, now %d",
			wantAusstLen, len(state.AusstehendePositionen))
	}
	// Feld-Level-Alias: reduceByPosition schreibt list[i].Menge -= 1 in das Backing-Array.
	// Ohne den make+copy-Klon wäre state.AusstehendePositionen[0].Menge nach dem ApplyEvent 2.
	if state.AusstehendePositionen[0].Menge != wantAusstMenge {
		t.Errorf("original state AusstehendePositionen[0].Menge mutated: was %d, now %d",
			wantAusstMenge, state.AusstehendePositionen[0].Menge)
	}

	// Zur Sicherheit: state2 muss korrekte Werte haben.
	if state2.UnbezahltePositionen[0].Menge != 2 {
		t.Errorf("new state UnbezahltePositionen[0].Menge = %d, want 2", state2.UnbezahltePositionen[0].Menge)
	}
	if state2.AusstehendePositionen[0].Menge != 2 {
		t.Errorf("new state AusstehendePositionen[0].Menge = %d, want 2", state2.AusstehendePositionen[0].Menge)
	}
}

func TestApplyEvent_UnknownEventType_ReturnsError(t *testing.T) {
	evt := e.Event{
		ID:      1,
		Type:    "unknown.event:v1",
		Data:    json.RawMessage(`{}`),
		Version: 1,
	}

	_, err := ApplyEvent(TischSession{}, evt)
	if err == nil {
		t.Fatal("expected error for unknown event type, got nil")
	}
}

// TestApplyEvent_WarenruecknahmeAfterPayment belegt, dass eine kassenwirksame
// Warenrücknahme bezahlter Positionen den offenen Betrag nicht ins Minus dreht: der
// Saldo bleibt 0, die am Tisch vereinnahmten Zahlungen werden um die Rückgabe gemindert
// und die zurückgenommene Position verschwindet aus der Ausstehend-Liste.
func TestApplyEvent_WarenruecknahmeAfterPayment(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// Pay for all 2 beers
	payPositions := positionsFromOrder(t, orderEvent, 2)
	payEvent := mustCreatePaymentEvent(t, testSubject, 1, payPositions, 1000)
	payEvent.ID = 2
	payEvent.Version = 2

	state, err = ApplyEvent(state, payEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != 0 {
		t.Fatalf("expected SaldoCents 0, got %d", state.SaldoCents)
	}

	// Warenrücknahme von 1 Bier nach der Zahlung — der offene Betrag bleibt 0.
	cancelPositions := positionsFromOrder(t, orderEvent, 1)
	cancelEvent := mustCreateCancelationEvent(t, testSubject, 1, testZahlungID, cancelPositions, 500)
	cancelEvent.ID = 3
	cancelEvent.Version = 3

	state, err = ApplyEvent(state, cancelEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != 0 {
		t.Fatalf("expected SaldoCents 0 (offener Betrag nie negativ), got %d", state.SaldoCents)
	}
	// Die Bar-Rückgabe mindert die vereinnahmten Zahlungen.
	if state.GesamtZahlungenCents != 500 {
		t.Fatalf("expected GesamtZahlungenCents 500, got %d", state.GesamtZahlungenCents)
	}
	// Unbezahlt was already empty (paid), stays empty
	if len(state.UnbezahltePositionen) != 0 {
		t.Fatalf("expected 0 unbezahlte positionen, got %d", len(state.UnbezahltePositionen))
	}
	// Die zurückgenommene Position verschwindet aus der Ausstehend-Liste.
	if state.AusstehendePositionen[0].Menge != 1 {
		t.Fatalf("expected 1 ausstehende position remaining, got %+v", state.AusstehendePositionen)
	}
}

func TestApplyEvent_SetsErsteBestellungLogTimeOnlyOnce(t *testing.T) {
	products := []Position{testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 1)}

	firstOrder, err := NewBestellungAufgenommenEvent(testSubject, 1, "TestUser", products, "")
	if err != nil {
		t.Fatalf("failed to create first order event: %v", err)
	}
	firstOrder.ID = 1
	firstOrder.Version = 1
	firstOrder.Time = time.Date(2026, 5, 1, 18, 1, 0, 0, time.UTC)

	state, err := ApplyEvent(TischSession{}, firstOrder)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.ErsteBestellungLogTime == nil {
		t.Fatal("expected ersteBestellungLogTime to be set")
	}

	wantFirst := firstOrder.Time
	if !state.ErsteBestellungLogTime.Equal(wantFirst) {
		t.Fatalf("expected first event time %s, got %s", wantFirst.Format(time.RFC3339), state.ErsteBestellungLogTime.Format(time.RFC3339))
	}

	secondOrder, err := NewBestellungAufgenommenEvent(testSubject, 1, "TestUser", products, "")
	if err != nil {
		t.Fatalf("failed to create second order event: %v", err)
	}
	secondOrder.ID = 2
	secondOrder.Version = 2
	secondOrder.Time = time.Date(2026, 5, 1, 18, 5, 0, 0, time.UTC)

	state, err = ApplyEvent(state, secondOrder)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.ErsteBestellungLogTime == nil {
		t.Fatal("expected ersteBestellungLogTime to stay set")
	}
	if !state.ErsteBestellungLogTime.Equal(wantFirst) {
		t.Fatalf("expected log time to stay on first order %s, got %s", wantFirst.Format(time.RFC3339), state.ErsteBestellungLogTime.Format(time.RFC3339))
	}
}
