//go:build unit

package kasse

import (
	"encoding/json"
	"testing"
	"time"

	e "github.com/nicograef/jotti/backend/domain/event"
)

func mustCreateOrderEvent(t *testing.T, subject string, userID int, products []Position) e.Event {
	t.Helper()
	event, err := NewBestellungAufgenommenEvent(subject, userID, "TestUser", products, "")
	if err != nil {
		t.Fatalf("failed to create order event: %v", err)
	}
	return event
}

func mustCreatePaymentEvent(t *testing.T, subject string, userID int, positions []Position, gesamtZahlungCents int) e.Event {
	t.Helper()
	event, err := NewZahlungKassiertEvent(subject, userID, "TestUser", positions, gesamtZahlungCents, "")
	if err != nil {
		t.Fatalf("failed to create payment event: %v", err)
	}
	return event
}

func mustCreateCancelationEvent(t *testing.T, subject string, userID int, positions []Position, gesamtStornierungCents int) e.Event {
	t.Helper()
	event, err := NewStornierungErteiltEvent(subject, userID, "TestUser", positions, gesamtStornierungCents, "Test")
	if err != nil {
		t.Fatalf("failed to create cancelation event: %v", err)
	}
	return event
}

func mustCreateDeliveryEvent(t *testing.T, subject string, userID int, positions []Position) e.Event {
	t.Helper()
	event, err := NewAusgabeBestaetigtEvent(subject, userID, "TestUser", positions, "")
	if err != nil {
		t.Fatalf("failed to create delivery event: %v", err)
	}
	return event
}

func mustCreateAuszahlungEvent(t *testing.T, subject string, userID int, betragCents int, kommentar string) e.Event {
	t.Helper()
	event, err := NewAuszahlungGeleistetEvent(subject, userID, "TestUser", betragCents, kommentar)
	if err != nil {
		t.Fatalf("failed to create auszahlung event: %v", err)
	}
	return event
}

// helper to create a test Position with fat event fields
func testPosition(varianteID int, produktName, varianteName, kategorie string, einzelpreis, menge int) Position {
	steuersatz := "regel"
	switch kategorie {
	case "essen":
		steuersatz = "ermaessigt"
	case "getraenk":
		steuersatz = "regel"
	case "sonstiges":
		steuersatz = "befreit"
	}

	return Position{
		// PositionID will be generated by NewBestellungAufgenommenEvent
		VarianteID:   varianteID,
		ProduktName:  produktName,
		VarianteName: varianteName,
		Kategorie:    kategorie,
		Steuersatz:   steuersatz,
		Einzelpreis:  einzelpreis,
		Menge:        menge,
	}
}

// positionsFromOrder extracts full Positions from an order event with adjusted menge
func positionsFromOrder(t *testing.T, orderEvent e.Event, menge int) []Position {
	t.Helper()
	bestellung, err := buildBestellungFromEvent(orderEvent)
	if err != nil {
		t.Fatalf("failed to build bestellung from event: %v", err)
	}
	positions := make([]Position, len(bestellung.Positionen))
	for i, pos := range bestellung.Positionen {
		positions[i] = pos
		positions[i].Menge = menge
	}
	return positions
}

const testSubject = "kassensitzung-1/tisch-42"

func TestApplyEvent_BestellungOnEmptyTable(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if state.SaldoCents != 1000 {
		t.Fatalf("expected SaldoCents 1000, got %d", state.SaldoCents)
	}
	if len(state.UnbezahltePositionen) != 1 {
		t.Fatalf("expected 1 unbezahlte position, got %d", len(state.UnbezahltePositionen))
	}
	if state.UnbezahltePositionen[0].Menge != 2 {
		t.Fatalf("expected Menge 2, got %d", state.UnbezahltePositionen[0].Menge)
	}
	if len(state.AusstehendePositionen) != 1 {
		t.Fatalf("expected 1 ungelieferte position, got %d", len(state.AusstehendePositionen))
	}
	if state.AusstehendePositionen[0].Menge != 2 {
		t.Fatalf("expected Menge 2, got %d", state.AusstehendePositionen[0].Menge)
	}
	if state.GesamtZahlungenCents != 0 {
		t.Fatalf("expected GesamtZahlungenCents 0, got %d", state.GesamtZahlungenCents)
	}
	if state.LastEventID != 1 {
		t.Fatalf("expected LastEventID 1, got %d", state.LastEventID)
	}
	if state.LastEventVersion != 1 {
		t.Fatalf("expected LastEventVersion 1, got %d", state.LastEventVersion)
	}
}

func TestApplyEvent_ZahlungReducesSaldoAndUnbezahlt(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	positions := positionsFromOrder(t, orderEvent, 1)
	paymentEvent := mustCreatePaymentEvent(t, testSubject, 1, positions, 500)
	paymentEvent.ID = 2
	paymentEvent.Version = 2

	state, err = ApplyEvent(state, paymentEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if state.SaldoCents != 500 {
		t.Fatalf("expected SaldoCents 500, got %d", state.SaldoCents)
	}
	if state.GesamtZahlungenCents != 500 {
		t.Fatalf("expected GesamtZahlungenCents 500, got %d", state.GesamtZahlungenCents)
	}
	if len(state.UnbezahltePositionen) != 1 {
		t.Fatalf("expected 1 unbezahlte position, got %d", len(state.UnbezahltePositionen))
	}
	if state.UnbezahltePositionen[0].Menge != 1 {
		t.Fatalf("expected Menge 1, got %d", state.UnbezahltePositionen[0].Menge)
	}
	if state.LastEventID != 2 {
		t.Fatalf("expected LastEventID 2, got %d", state.LastEventID)
	}
}

func TestApplyEvent_StornierungReducesSaldoAndUnbezahlt(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	positions := positionsFromOrder(t, orderEvent, 1)
	cancelEvent := mustCreateCancelationEvent(t, testSubject, 1, positions, 500)
	cancelEvent.ID = 2
	cancelEvent.Version = 2

	state, err = ApplyEvent(state, cancelEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if state.SaldoCents != 500 {
		t.Fatalf("expected SaldoCents 500, got %d", state.SaldoCents)
	}
	if len(state.UnbezahltePositionen) != 1 {
		t.Fatalf("expected 1 unbezahlte position, got %d", len(state.UnbezahltePositionen))
	}
	if state.UnbezahltePositionen[0].Menge != 1 {
		t.Fatalf("expected Menge 1, got %d", state.UnbezahltePositionen[0].Menge)
	}
	// Stornierung also reduces ausstehende
	if len(state.AusstehendePositionen) != 1 {
		t.Fatalf("expected 1 ungelieferte position, got %d", len(state.AusstehendePositionen))
	}
	if state.AusstehendePositionen[0].Menge != 1 {
		t.Fatalf("expected Menge 1, got %d", state.AusstehendePositionen[0].Menge)
	}
}

func TestApplyEvent_UmbuchungMovesPositionsBetweenTische(t *testing.T) {
	const zNr = 1
	const quellTischID = 42
	const zielTischID = 7
	quellSubject := TischSessionSubject(zNr, quellTischID)
	zielSubject := TischSessionSubject(zNr, zielTischID)

	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, quellSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	quellState, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// Eine von zwei Positionen auf den Zieltisch umbuchen.
	umbuchPositionen := positionsFromOrder(t, orderEvent, 1)
	quellEvent, zielEvent, err := NewBestellungUmgebuchtEvents(zNr, quellTischID, zielTischID, 1, "TestUser", umbuchPositionen, 500, "Umbuchung auf Tisch Ziel", "Umbuchung von Tisch Quelle")
	if err != nil {
		t.Fatalf("failed to create umbuchung events: %v", err)
	}
	quellEvent.ID, quellEvent.Version = 2, 2
	zielEvent.ID, zielEvent.Version = 3, 1

	// Abgang auf dem Quelltisch: Saldo sinkt, eine Position bleibt.
	quellState, err = ApplyEvent(quellState, quellEvent)
	if err != nil {
		t.Fatalf("expected no error applying abgang, got %v", err)
	}
	if quellState.SaldoCents != 500 {
		t.Fatalf("expected source SaldoCents 500, got %d", quellState.SaldoCents)
	}
	if len(quellState.UnbezahltePositionen) != 1 || quellState.UnbezahltePositionen[0].Menge != 1 {
		t.Fatalf("expected 1 unbezahlte position with menge 1, got %+v", quellState.UnbezahltePositionen)
	}
	if len(quellState.AusstehendePositionen) != 1 || quellState.AusstehendePositionen[0].Menge != 1 {
		t.Fatalf("expected 1 ausstehende position with menge 1, got %+v", quellState.AusstehendePositionen)
	}

	// Zugang auf dem leeren Zieltisch: wie eine frische Bestellung.
	zielState, err := ApplyEvent(TischSession{Subject: zielSubject}, zielEvent)
	if err != nil {
		t.Fatalf("expected no error applying zugang, got %v", err)
	}
	if zielState.SaldoCents != 500 {
		t.Fatalf("expected target SaldoCents 500, got %d", zielState.SaldoCents)
	}
	if len(zielState.UnbezahltePositionen) != 1 || zielState.UnbezahltePositionen[0].Menge != 1 {
		t.Fatalf("expected 1 unbezahlte position with menge 1, got %+v", zielState.UnbezahltePositionen)
	}
	if len(zielState.AusstehendePositionen) != 1 || zielState.AusstehendePositionen[0].Menge != 1 {
		t.Fatalf("expected 1 ausstehende position with menge 1, got %+v", zielState.AusstehendePositionen)
	}
	if zielState.ErsteBestellungLogTime == nil {
		t.Fatal("expected target ErsteBestellungLogTime to be set by the zugang")
	}
	// Der Zugang trägt frische PositionIDs (eigenständig auf dem Zieltisch).
	if zielState.UnbezahltePositionen[0].PositionID == quellState.UnbezahltePositionen[0].PositionID {
		t.Fatal("expected target position to carry a fresh PositionID")
	}
}

func TestApplyEvent_AusgabeReducesOnlyAusstehend(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	positions := positionsFromOrder(t, orderEvent, 2)
	deliveryEvent := mustCreateDeliveryEvent(t, testSubject, 1, positions)
	deliveryEvent.ID = 2
	deliveryEvent.Version = 2

	state, err = ApplyEvent(state, deliveryEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// Saldo unchanged
	if state.SaldoCents != 1000 {
		t.Fatalf("expected SaldoCents 1000, got %d", state.SaldoCents)
	}
	// Unbezahlt unchanged
	if len(state.UnbezahltePositionen) != 1 {
		t.Fatalf("expected 1 unbezahlte position, got %d", len(state.UnbezahltePositionen))
	}
	if state.UnbezahltePositionen[0].Menge != 2 {
		t.Fatalf("expected Menge 2, got %d", state.UnbezahltePositionen[0].Menge)
	}
	// Ungeliefert reduced to 0
	if len(state.AusstehendePositionen) != 0 {
		t.Fatalf("expected 0 ungelieferte positionen, got %d", len(state.AusstehendePositionen))
	}
}

func TestApplyEvent_MultipleEventsSequentially(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 3),
		testPosition(2, "Wurst", "Bratwurst", "essen", 400, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	// Apply order: saldo = 500*3 + 400*2 = 2300
	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != 2300 {
		t.Fatalf("expected SaldoCents 2300, got %d", state.SaldoCents)
	}

	// Deliver all beer
	bestellung, err := buildBestellungFromEvent(orderEvent)
	if err != nil {
		t.Fatalf("failed to build bestellung: %v", err)
	}
	beerPos := []Position{bestellung.Positionen[0]}
	beerPos[0].Menge = 3
	deliveryEvent := mustCreateDeliveryEvent(t, testSubject, 1, beerPos)
	deliveryEvent.ID = 2
	deliveryEvent.Version = 2

	state, err = ApplyEvent(state, deliveryEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	// Saldo unchanged
	if state.SaldoCents != 2300 {
		t.Fatalf("expected SaldoCents 2300, got %d", state.SaldoCents)
	}
	// 2 ausstehende (only wurst remaining)
	if len(state.AusstehendePositionen) != 1 {
		t.Fatalf("expected 1 ungelieferte position, got %d", len(state.AusstehendePositionen))
	}

	// Pay for 1 beer (500)
	beerPayPos := []Position{bestellung.Positionen[0]}
	beerPayPos[0].Menge = 1
	paymentEvent := mustCreatePaymentEvent(t, testSubject, 1, beerPayPos, 500)
	paymentEvent.ID = 3
	paymentEvent.Version = 3

	state, err = ApplyEvent(state, paymentEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != 1800 {
		t.Fatalf("expected SaldoCents 1800, got %d", state.SaldoCents)
	}
	if state.GesamtZahlungenCents != 500 {
		t.Fatalf("expected GesamtZahlungenCents 500, got %d", state.GesamtZahlungenCents)
	}

	// Cancel 1 wurst (400)
	wurstPos := []Position{bestellung.Positionen[1]}
	wurstPos[0].Menge = 1
	cancelEvent := mustCreateCancelationEvent(t, testSubject, 1, wurstPos, 400)
	cancelEvent.ID = 4
	cancelEvent.Version = 4

	state, err = ApplyEvent(state, cancelEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != 1400 {
		t.Fatalf("expected SaldoCents 1400, got %d", state.SaldoCents)
	}
	if state.LastEventID != 4 {
		t.Fatalf("expected LastEventID 4, got %d", state.LastEventID)
	}
	if state.LastEventVersion != 4 {
		t.Fatalf("expected LastEventVersion 4, got %d", state.LastEventVersion)
	}
}

func TestApplyEvent_BestellungTagsBesteller(t *testing.T) {
	products := []Position{testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2)}
	orderEvent, err := NewBestellungAufgenommenEvent(testSubject, 7, "Anna", products, "")
	if err != nil {
		t.Fatalf("failed to create order event: %v", err)
	}
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if state.UnbezahltePositionen[0].BestellerUserID != 7 || state.UnbezahltePositionen[0].BestellerName != "Anna" {
		t.Errorf("expected unbezahlt besteller 7/Anna, got %d/%q",
			state.UnbezahltePositionen[0].BestellerUserID, state.UnbezahltePositionen[0].BestellerName)
	}
	if state.AusstehendePositionen[0].BestellerUserID != 7 || state.AusstehendePositionen[0].BestellerName != "Anna" {
		t.Errorf("expected ausstehend besteller 7/Anna, got %d/%q",
			state.AusstehendePositionen[0].BestellerUserID, state.AusstehendePositionen[0].BestellerName)
	}
}

func TestApplyEvent_MultipleBestellerAtSameTable(t *testing.T) {
	annaOrder, err := NewBestellungAufgenommenEvent(testSubject, 7, "Anna", []Position{testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 1)}, "")
	if err != nil {
		t.Fatalf("failed to create anna order: %v", err)
	}
	annaOrder.ID, annaOrder.Version = 1, 1

	bertOrder, err := NewBestellungAufgenommenEvent(testSubject, 8, "Bert", []Position{testPosition(2, "Wurst", "Bratwurst", "essen", 400, 1)}, "")
	if err != nil {
		t.Fatalf("failed to create bert order: %v", err)
	}
	bertOrder.ID, bertOrder.Version = 2, 2

	state, err := ApplyEvent(TischSession{}, annaOrder)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	state, err = ApplyEvent(state, bertOrder)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	bestellerByProdukt := map[string]string{}
	for _, pos := range state.AusstehendePositionen {
		bestellerByProdukt[pos.ProduktName] = pos.BestellerName
	}
	if bestellerByProdukt["Beer"] != "Anna" {
		t.Errorf("expected Beer ordered by Anna, got %q", bestellerByProdukt["Beer"])
	}
	if bestellerByProdukt["Wurst"] != "Bert" {
		t.Errorf("expected Wurst ordered by Bert, got %q", bestellerByProdukt["Wurst"])
	}
}

func TestApplyEvent_PaymentCancelDeliveryKeepBestellerTag(t *testing.T) {
	products := []Position{testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 3)}
	orderEvent, err := NewBestellungAufgenommenEvent(testSubject, 7, "Anna", products, "")
	if err != nil {
		t.Fatalf("failed to create order event: %v", err)
	}
	orderEvent.ID, orderEvent.Version = 1, 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// A colleague (Bert) delivers and pays part of Anna's order — the besteller tag must survive.
	deliverPos := positionsFromOrder(t, orderEvent, 1)
	deliveryEvent := mustCreateDeliveryEvent(t, testSubject, 8, deliverPos)
	deliveryEvent.ID, deliveryEvent.Version = 2, 2
	state, err = ApplyEvent(state, deliveryEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	payPos := positionsFromOrder(t, orderEvent, 1)
	paymentEvent := mustCreatePaymentEvent(t, testSubject, 8, payPos, 500)
	paymentEvent.ID, paymentEvent.Version = 3, 3
	state, err = ApplyEvent(state, paymentEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if state.AusstehendePositionen[0].BestellerName != "Anna" {
		t.Errorf("expected ausstehend besteller to stay Anna, got %q", state.AusstehendePositionen[0].BestellerName)
	}
	if state.UnbezahltePositionen[0].BestellerName != "Anna" {
		t.Errorf("expected unbezahlt besteller to stay Anna, got %q", state.UnbezahltePositionen[0].BestellerName)
	}
}

func TestApplyEvent_UnknownEventType_ReturnsError(t *testing.T) {
	evt := e.Event{
		ID:      1,
		Type:    "unknown.event:v1",
		Data:    json.RawMessage(`{}`),
		Version: 1,
	}

	_, err := ApplyEvent(TischSession{}, evt)
	if err == nil {
		t.Fatal("expected error for unknown event type, got nil")
	}
}

func TestApplyEvent_StornierungAfterPayment_NegativeSaldo(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// Pay for all 2 beers
	payPositions := positionsFromOrder(t, orderEvent, 2)
	payEvent := mustCreatePaymentEvent(t, testSubject, 1, payPositions, 1000)
	payEvent.ID = 2
	payEvent.Version = 2

	state, err = ApplyEvent(state, payEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != 0 {
		t.Fatalf("expected SaldoCents 0, got %d", state.SaldoCents)
	}

	// Cancel 1 beer after payment — should result in negative saldo
	cancelPositions := positionsFromOrder(t, orderEvent, 1)
	cancelEvent := mustCreateCancelationEvent(t, testSubject, 1, cancelPositions, 500)
	cancelEvent.ID = 3
	cancelEvent.Version = 3

	state, err = ApplyEvent(state, cancelEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != -500 {
		t.Fatalf("expected SaldoCents -500, got %d", state.SaldoCents)
	}
	// Unbezahlt was already empty (paid), stays empty
	if len(state.UnbezahltePositionen) != 0 {
		t.Fatalf("expected 0 unbezahlte positionen, got %d", len(state.UnbezahltePositionen))
	}
}

func TestApplyEvent_AuszahlungIncreasesSaldo(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	orderEvent.ID = 1
	orderEvent.Version = 1

	state, err := ApplyEvent(TischSession{}, orderEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// Pay for all 2 beers
	payPositions := positionsFromOrder(t, orderEvent, 2)
	payEvent := mustCreatePaymentEvent(t, testSubject, 1, payPositions, 1000)
	payEvent.ID = 2
	payEvent.Version = 2

	state, err = ApplyEvent(state, payEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != 0 {
		t.Fatalf("expected SaldoCents 0, got %d", state.SaldoCents)
	}

	// Cancel 1 beer after payment — negative saldo
	cancelPositions := positionsFromOrder(t, orderEvent, 1)
	cancelEvent := mustCreateCancelationEvent(t, testSubject, 1, cancelPositions, 500)
	cancelEvent.ID = 3
	cancelEvent.Version = 3

	state, err = ApplyEvent(state, cancelEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != -500 {
		t.Fatalf("expected SaldoCents -500, got %d", state.SaldoCents)
	}

	// Auszahlung: pay out 500 cents
	auszahlungEvent := mustCreateAuszahlungEvent(t, testSubject, 1, 500, "Rueckzahlung")
	auszahlungEvent.ID = 4
	auszahlungEvent.Version = 4

	state, err = ApplyEvent(state, auszahlungEvent)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.SaldoCents != 0 {
		t.Fatalf("expected SaldoCents 0 after auszahlung, got %d", state.SaldoCents)
	}
	if state.LastEventID != 4 {
		t.Fatalf("expected LastEventID 4, got %d", state.LastEventID)
	}
}

func TestComputeNichtStorniertePositionen_IgnoresAuszahlung(t *testing.T) {
	products := []Position{
		testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 2),
	}
	orderEvent := mustCreateOrderEvent(t, testSubject, 1, products)
	positions := positionsFromOrder(t, orderEvent, 2)
	payEvent := mustCreatePaymentEvent(t, testSubject, 1, positions, 1000)
	auszahlungEvent := mustCreateAuszahlungEvent(t, testSubject, 1, 500, "Rueckzahlung")

	nichtStorniert, err := ComputeNichtStorniertePositionen([]e.Event{orderEvent, payEvent, auszahlungEvent})
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	// 2 beers still not cancelled
	if len(nichtStorniert) != 1 || nichtStorniert[0].Menge != 2 {
		t.Fatalf("expected 2 beers not cancelled, got %v", nichtStorniert)
	}
}

func TestApplyEvent_SetsErsteBestellungLogTimeOnlyOnce(t *testing.T) {
	products := []Position{testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 1)}

	firstTSE := &TSEData{
		TransactionNumber: 1001,
		SignatureCounter:  1,
		SerialNumberTSE:   "TSE-1",
		LogTimeStart:      "2026-05-01T18:01:00Z",
		LogTimeEnd:        "2026-05-01T18:01:01Z",
		Signature:         "SIG-1",
		ProcessType:       "Bestellung-V1",
	}
	firstOrder, err := NewBestellungAufgenommenEvent(testSubject, 1, "TestUser", products, "")
	if err != nil {
		t.Fatalf("failed to create first order event: %v", err)
	}
	firstOrder, err = EmbedTSEInBestellungAufgenommen(firstOrder, "tx-erste-bestellung", firstTSE)
	if err != nil {
		t.Fatalf("failed to embed TSE into first order event: %v", err)
	}
	firstOrder.ID = 1
	firstOrder.Version = 1

	state, err := ApplyEvent(TischSession{}, firstOrder)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.ErsteBestellungLogTime == nil {
		t.Fatal("expected ersteBestellungLogTime to be set")
	}

	wantFirst, _ := time.Parse(time.RFC3339, "2026-05-01T18:01:00Z")
	if !state.ErsteBestellungLogTime.Equal(wantFirst) {
		t.Fatalf("expected first log time %s, got %s", wantFirst.Format(time.RFC3339), state.ErsteBestellungLogTime.Format(time.RFC3339))
	}

	secondTSE := &TSEData{
		TransactionNumber: 1002,
		SignatureCounter:  2,
		SerialNumberTSE:   "TSE-1",
		LogTimeStart:      "2026-05-01T18:05:00Z",
		LogTimeEnd:        "2026-05-01T18:05:01Z",
		Signature:         "SIG-2",
		ProcessType:       "Bestellung-V1",
	}
	secondOrder, err := NewBestellungAufgenommenEvent(testSubject, 1, "TestUser", products, "")
	if err != nil {
		t.Fatalf("failed to create second order event: %v", err)
	}
	secondOrder, err = EmbedTSEInBestellungAufgenommen(secondOrder, "tx-zweite-bestellung", secondTSE)
	if err != nil {
		t.Fatalf("failed to embed TSE into second order event: %v", err)
	}
	secondOrder.ID = 2
	secondOrder.Version = 2

	state, err = ApplyEvent(state, secondOrder)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.ErsteBestellungLogTime == nil {
		t.Fatal("expected ersteBestellungLogTime to stay set")
	}
	if !state.ErsteBestellungLogTime.Equal(wantFirst) {
		t.Fatalf("expected log time to stay on first order %s, got %s", wantFirst.Format(time.RFC3339), state.ErsteBestellungLogTime.Format(time.RFC3339))
	}
}

func TestApplyEvent_ErsteBestellungLogTime_FallbackAufEventZeit(t *testing.T) {
	products := []Position{testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 1)}

	// Bestellung ohne TSE-Daten (z. B. waehrend eines TSE-Ausfalls erfasst).
	order, err := NewBestellungAufgenommenEvent(testSubject, 1, "TestUser", products, "")
	if err != nil {
		t.Fatalf("failed to create order event: %v", err)
	}
	order.ID = 1
	order.Version = 1

	state, err := ApplyEvent(TischSession{}, order)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if state.ErsteBestellungLogTime == nil {
		t.Fatal("expected ersteBestellungLogTime fallback to event time")
	}
	if !state.ErsteBestellungLogTime.Equal(order.Time.UTC()) {
		t.Fatalf("expected event time %s, got %s", order.Time.UTC().Format(time.RFC3339), state.ErsteBestellungLogTime.Format(time.RFC3339))
	}
}

func TestApplyEvent_BestellungWithInvalidLogTime_ReturnsError(t *testing.T) {
	products := []Position{testPosition(1, "Beer", "Pils 0.5l", "getraenk", 500, 1)}

	tseData := &TSEData{
		TransactionNumber: 1001,
		SignatureCounter:  1,
		SerialNumberTSE:   "TSE-1",
		LogTimeStart:      "invalid",
		LogTimeEnd:        "2026-05-01T18:01:01Z",
		Signature:         "SIG-1",
		ProcessType:       "Bestellung-V1",
	}

	order, err := NewBestellungAufgenommenEvent(testSubject, 1, "TestUser", products, "")
	if err != nil {
		t.Fatalf("failed to create order event: %v", err)
	}
	evt, err := EmbedTSEInBestellungAufgenommen(order, "tx-invalid-logtime", tseData)
	if err != nil {
		t.Fatalf("failed to embed TSE into order event: %v", err)
	}

	_, err = ApplyEvent(TischSession{}, evt)
	if err == nil {
		t.Fatal("expected parse error for invalid log time, got nil")
	}
}
